### ISSUE TITLE
ERROR com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent - Failed Sync Process java.lang.IllegalArgumentException: No output fields defined for component:stream wordNormalizer_componentId:default at backtype.storm.task.GeneralTopologyContext.getComponentOutputFields(GeneralTopologyContext.j...

### ISSUE THREAD

**Issue by sdcuike** [alibaba/jstorm#101]
问题来源：[http://my.oschina.net/doctor2014/blog/406431](http://my.oschina.net/doctor2014/blog/406431).
请问：emit，declareStream带streamId，对fieldsGrouping有影响吗。数据分组有什么限制吗。

**Comment by longdafeng** [comment]
所有emit 都会带streamid, 如果你没有设置streamid， 系统会给你补上"default" streamid

你这个问题没有遇到，我先关了
