### ISSUE TITLE
请问下jstorm团队有没有用nettty替换zeromq的安装文档？

### ISSUE THREAD

**Issue by longting** [alibaba/jstorm#111]
请问下jstorm团队有没有用nettty替换zeromq的安装文档？

java.library.path: zeromq 和java zeromq library的安装目录

**Comment by longdafeng** [comment]
默认是netty

以后会把zeromq给去掉


你如果用rpm安装的话，都会自动安装zeromq


Regards
longda

发件人:  longting
答复:  alibaba/jstorm
日期:  2015年7月18日 星期六 上午10:52
至:  alibaba/jstorm
主题:  [jstorm] 请问下jstorm团队有没有用nettty替换zeromq的安装文档？ (#111)


请问下jstorm团队有没有用nettty替换zeromq的安装文档？

java.library.path: zeromq 和java zeromq library的安装目录
