### ISSUE TITLE
利用cgroup限定cpu资源使用

### ISSUE THREAD

**Issue by chenatu** [alibaba/jstorm#118]
我们平台想利用jstorm的cgroup机制来限定cpu usage。/etc/cgconfig.conf配置如下

    mount {
            cpuset  = /cgroup/cpuset;
            cpu     = /cgroup/cpu;
            cpuacct = /cgroup/cpuacct;
            memory  = /cgroup/memory;
            devices = /cgroup/devices;
            freezer = /cgroup/freezer;
            net_cls = /cgroup/net_cls;
            blkio   = /cgroup/blkio;
    }
    
    group jstorm {
           perm {
                   task {
                          uid = 501;
                          gid = 501;
                   }
                   admin {
                          uid = 501;
                          gid = 501;
                   }
           }
           cpu {
                cpu.rt_period_us = 1000000;
                cpu.rt_runtime_us = 100000;
           }
           #cpuset {
           #        cpuset.cpus = 1;
           #        cpuset.mems = 0;
           #}
    }

我们期待的效果是能将cpu使用控制在10%左右。我们已经设置supervisor.enable.cgroup: true。提交了topology，supervisor分配了两个worker来执行。我们用top观察，发现worker进程的cpu使用远超100%。 请问如何利用cgroup限定cpu usage呢？

**Comment by longdafeng** [comment]
这个地方设置每个worker最多用几个核， 
worker.cpu.core.upper.limit: 3

cgroup配置
```
mount {
        cpuset  = /cgroup/cpuset;
        cpu     = /cgroup/cpu;
        cpuacct = /cgroup/cpuacct;
        memory  = /cgroup/memory;
        devices = /cgroup/devices;
        freezer = /cgroup/freezer;
        net_cls = /cgroup/net_cls;
        blkio   = /cgroup/blkio;
}

group jstorm {
       perm {
               task {
                      uid = 501;
                      gid = 501;
               }
               admin {
                      uid = 501;
                      gid = 501;
               }
       }
       #cpu {
       #     cpu.rt_period_us = 1000000;
       #     cpu.rt_runtime_us = 100000;
       #}
       #cpuset {
       #        cpuset.cpus = 1;
       #        cpuset.mems = 0;
       #}
}
```
