### ISSUE TITLE
官网下载的jstorm-ui2.1.0.war 里面log4j-over-slf4j.jar slf4j-log4j12.jar同时存在，导致冲突，ui不能正常启动。

### ISSUE THREAD

**Issue by Dollyn** [alibaba/jstorm#124]
自己下的源码打包也是一样的，手动删除log4j-over-slf4j.jar后可以正常启动，
虽然问题不算大，但始终很影响用户体验

**Comment by unsleepy22** [comment]
提交的时候加个参数：exclude-jars slf4j-log4j12.jar

**Comment by longdafeng** [comment]
@unsleepy22  你把它解决吧

**Comment by longdafeng** [comment]
@Dollyn ， 以后遇到问题， 提出issue后， 可以给我们提patch哦， 直接提pull request， 然后我们merge 进来

**Comment by longdafeng** [comment]
fixed in 2.1.1
