### ISSUE TITLE
README.md文件中有两个Contributor的链接地址重复

### ISSUE THREAD

**Issue by PengboNi** [alibaba/jstorm#125]
[README.md](https://github.com/alibaba/jstorm/blob/master/README.md)中如下两个Contributor的跳转链接是一样的，这两个是一个人？

[贺小桥@Hexiaoqiao](https://github.com/Hexiaoqiao)<br/>
[姜宪瑶@jxysoft](https://github.com/Hexiaoqiao)<br/>

**Comment by longdafeng** [comment]
不是一个人， 谢谢

**Comment by longdafeng** [comment]
already fix
