### ISSUE TITLE
jstorm.core这个包居然把logback-test.xml带进去了

### ISSUE THREAD

**Issue by Dollyn** [alibaba/jstorm#128]
RT，由于logback优先找logback-test.xml，自带这个文件会导致用户的配置文件不起作用。而且由于没有任何提示，只有看源码并debug才能找到问题原因，非常坑

**Comment by longdafeng** [comment]
这个是本地模式才会使用到， 在集群中运行时，使用的jstorm.logback.xml, 在提交任务时，用client_logback.xml，  你是什么情况下发生冲突呢

**Comment by Dollyn** [comment]
确实是本地模式运行的时候出现的问题。

**Comment by longdafeng** [comment]
fixed in 2.1.1
