### ISSUE TITLE
2.1.0版本配置文件storm.yaml.example中配置项存在缩进，导致无法启动

### ISSUE THREAD

**Issue by michael8335** [alibaba/jstorm#129]
2.1.0版本配置文件storm.yaml.example中配置项存在缩进（LInux），导致无法启动，需要手动删除前面的缩进，example文件中应该删除前面的缩进，方便使用

**Comment by unsleepy22** [comment]
storm.yaml.bak?

**Comment by unsleepy22** [comment]
storm.yaml.bak里有几处是tab，但是是注释里的，应该不影响的

**Comment by longdafeng** [comment]
already fixed
