### ISSUE TITLE
关于Ack和Fail机制

### ISSUE THREAD

**Issue by xiaoyao2102** [alibaba/jstorm#131]
我的Topo就是一个简单的线性结构，一层Spout一层Bolt做过滤最后一层Bolt做计算。
理论上来说，Spout的ack方法的执行需要两层Bolt都调用ack方法，而fail方法的执行只要其中一个Bolt调用fail或者超时就会执行。

目前我看到的现象是，只要过滤层调用了ack，不管做计算的Bolt是否调用ack或fail或超时，Spout的ack方法都会被调用，而且如果过滤层调用了fail或超时就会导致Spout调用fail。

请问这个现象该如何解释？是最开始的理解就有错误么？

**Comment by unsleepy22** [comment]
ack机制的原理是，从spout和下游所有bolt开始，都会向acker发送ack消息，这样才能形成一棵完整的tuple tree并判断消息是否被成功处理。而fail就相对简单一些，是可以做熔断的，即任意一个bolt处理失败了，我们就可以认为这个tuple处理失败。

**Comment by xiaoyao2102** [comment]
谢谢回答！:+1:
