### ISSUE TITLE
JDK8中无法启动问题

### ISSUE THREAD

**Issue by kentkwan** [alibaba/jstorm#132]
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=64m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
Java HotSpot(TM) 64-Bit Server VM warning: CMSFullGCsBeforeCompaction is deprecated and will likely be removed in a future release.

**Comment by unsleepy22** [comment]
will fix in next release
