### ISSUE TITLE
KafkaSpout报错 java.util.NoSuchElementException

### ISSUE THREAD

**Issue by Dollyn** [alibaba/jstorm#133]
java.util.NoSuchElementException at java.util.TreeMap.key(TreeMap.java:1221) at java.util.TreeMap.firstKey(TreeMap.java:285) at java.util.TreeSet.first(TreeSet.java:394) at storm.kafka.PartitionManager.lastCompletedOffset(PartitionManager.java:252) at storm.kafka.PartitionManager.commit(PartitionManager.java:224) at storm.kafka.KafkaSpout.commit(KafkaSpout.java:191) at storm.kafka.KafkaSpout.nextTuple(KafkaSpout.java:156) at com.alibaba.jstorm.task.execute.spout.SpoutExecutors.nextTuple(SpoutExecutors.java:147) at com.alibaba.jstorm.task.execute.spout.MultipleThreadSpoutExecutors.run(MultipleThreadSpoutExecutors.java:73) at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:51) at java.lang.Thread.run(Thread.java:745) ;

简单看了一眼代码，太诡异，难道是线程安全问题？

    public long lastCompletedOffset() {
        if (_pending.isEmpty()) {
            return _emittedToOffset;
        } else {
            return _pending.first();            /// 252行
        }
    }

版本是0.9.6.3

**Comment by longdafeng** [comment]
你把你源码用jdk 6 编译 试一下

**Comment by liuxuan207** [comment]
是线程安全导致

**Comment by Dollyn** [comment]
额，那这算是bug么，因为这里应该没有业务代码的问题

@longdafeng 设置编译级别不够，必须要jdk6编译吗

我看2.1.0代码好像没有这个类了， 是不是更稳定一点...


另外，还有个问题。。。
kafkaspout 的 deserialize-queue is full; 是什么情况啊，sendtps, recv tps都很低只有几百的样子

**Comment by bastiliu** [comment]
看下你的spout ack()/fail()里是不是对相关数据进行修改操作了。JStorm里spout默认是多线程模式，ack/fail和nextTuple在两个线程里，要注意线程安全

**Comment by Dollyn** [comment]
都是IBasicBolt，没有手动ack

**Comment by Dollyn** [comment]
不好意思，没看清楚， Spout不是我们自己写的，直接用现成的storm-kafka

**Comment by shuopei** [comment]
这两天踩到同样一个坑里了，KafkaSpout不是线程安全的，所以需要使用SingleThreadSpoutExecutors，在storm的配置文件中配置spout.single.thread: true，即可解决。

**Comment by zeromem** [comment]
jstorm 2.11，使用sotrm-kafka，kafka数据4个分区，kafka spout设置4个实例。
使用默认设置时spout启动的MultipleThreadSpoutExecutors，每次运行topology，总是在读完kafka数据之后，有几个spout实例会报NoSuchElementException这个异常。
然后估计是这个原因，导致spout会重发tuple。（我的topology又必须保证tuple不丢不重）
然后添加了spout.single.thread: true的设置，没再出现异常了，tuple在数据库看来也是exactly once了。

**Comment by darouwan** [comment]
@zeromem spout.single.thread: true是配置在storm.yaml里面吗？每个supervisor都需要配置？

**Comment by Dollyn** [comment]
一般是在拓扑的配置文件里，根据你的代码，保证这个key-value在下面这个conf里就行了：

`StormSubmitter.submitTopology(streamName, conf, builder.createTopology());`

**Comment by darouwan** [comment]
@Dollyn 谢谢~那如果用原生的kafkaspout，有版本限制吗？jstorm2.1.1使用0.9.5的kafka spout是否可以？
