### ISSUE TITLE
[Discussion]JStorm on YARN 资源申请问题

### ISSUE THREAD

**Issue by millyFan** [alibaba/jstorm#134]
在最新版的JStorm中，JStorm on YARN调度资源的方式是什么呢？是按照Storm on YARN那种的以节点为单位申请的资源，之后再二级调度给自己的Topology分配资源，还是像Heron那样的所有Topology的资源申请完全托管给YARN这样的一级调度呢？

**Comment by longdafeng** [comment]
其实背后的问题是， 一级调度和二级调度的取舍问题。

什么时候使用一级调度， 类似heron或spark yarn模式， 这种模式下， 优点是， 调度的粒度会比较细， 资源不存在浪费问题。 缺点是， 这种模式下的app， 可能需要做大量修改去适配yarn或mesos。

选择 storm-on-yarn 模式下， 缺点就是存在资源浪费， 优点是， app不需要任何修改就可以去适配yarn或mesos。


个人建议：
1. 当集群规模小的时候， 选择类似heron或spark yarn 模式下，会更合理一下。 资源利用率会更充分一些。
2. 当集群规模比较大的时候， 我个人还是倾向于二级调度系统， 因为，
2.1 比较容易保持应用的独立性， 像jstorm 的调度系统非常复杂， 有3级调度， 如果移植到yarn上，这个调度系统改造工作量非常大， 另外supervisor需要适配 yarn的container。
2.2 更容易去做分组的概念， 比如一个bu 一个逻辑集群， 每个逻辑集群相互之间不打扰。而且每个逻辑集群的quato 很容易控制。
2.3  不过，现在即使是storm-on-yarn 这种模式， 存在大量问题， 随着大公司使用， 这种方式问题会逐渐被fix
