### ISSUE TITLE
jstorm-ui Error提示不及时更新

### ISSUE THREAD

**Issue by penuel-leo** [alibaba/jstorm#138]
如果出现错误，在ui上Error显示Y，后续正常或者重启之后，几个小时之后依然显示的是Y（有Error存在），容易引起误解

**Comment by wuchong** [comment]
UI Error的显示策略是最近一段时间内有错误发生并在该错误的存活时间内，就会显示（task dead错误存在的时间会比较长， 目前是3天;  queue full 一般是3分钟）。
