### ISSUE TITLE
jstorm nimbus cpu使用率偏高，哪些参数可以调节

### ISSUE THREAD

**Issue by hansonzh** [alibaba/jstorm#141]

**Comment by unsleepy22** [comment]
cpu使用率是多少，JVM参数贴一下，看一下哪个线程占用的cpu最多

**Comment by hansonzh** [comment]
java基本用的是默认的参数。貌似是以下线程的问题：
"TopologyMetricsRunnable" prio=10 tid=0x00007ffeb85ff000 nid=0x6222 runnable [0x00007ffe8c2fc000]
   java.lang.Thread.State: RUNNABLE
	at com.alibaba.jstorm.daemon.nimbus.TopologyMetricsRunnable.run(TopologyMetricsRunnable.java:254)

**Comment by unsleepy22** [comment]
fixed. 用最新的代码重新build一下～

**Comment by hansonzh** [comment]
最新的代码是当前github上的代码？可以在生产环境上用么？

**Comment by unsleepy22** [comment]
是的，可以直接在生产使用。
