### ISSUE TITLE
新手    从启动tomcat到打开jstorm网页 能否再提供更加详细的步骤 

### ISSUE THREAD

**Issue by yuanlai** [alibaba/jstorm#142]
比如启动jstorm时需要修改哪些配置信息
nimbus和supervisor是内置的 还是要额外安装
tomcat启动后 jstorm访问是默认网址 还是别的

**Comment by wuchong** [comment]
>比如启动jstorm时需要修改哪些配置信息

参考 [安装jstorm需要修改的配置参数](https://github.com/alibaba/jstorm/wiki/%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85#%E5%AE%89%E8%A3%85jstorm)

>nimbus和supervisor是内置的 还是要额外安装

jstorm core已经内置了nimbus和supervisor。 只有ui是需要另外安装的，且ui的安装不依赖jstorm环境。

>tomcat启动后 jstorm访问是默认网址 还是别的

jstorm ui的安装参考 [Web UI 安装](https://github.com/alibaba/jstorm/wiki/%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85#%E5%AE%89%E8%A3%85jstorm-web-ui)

首先你将 jstorm-ui.war 拷贝到 tomcat/webapps ，当tomcat启动后， 该war包会自动被解压到  jstorm-ui 文件夹。如果你不改这个文件名， 则需要访问 `http://hostname:8080/jstorm-ui/`。 建议讲解压出来的文件夹名换成 ROOT ， 或者ROOT软链接到该文件夹，则可以通过 `http://hostname:8080/`直接访问了。

**Comment by yuanlai** [comment]
发现一个问题 
jstorm bin目录下start.sh默认的path路径和自己机器本身的有冲突 改了后才能正确启动
那问题来了 war包默认的ui路径是什么 是不是也要修改

**Comment by wuchong** [comment]
ui 不需要修改。 直接把war包丢到tomcat容器里就行

**Comment by longdafeng** [comment]
$JSTORM_HOME/bin/start.sh 是按照阿里的运维标准进行设置的

你需要设置一下环境变量 

$JAVA_HOME

另外，如果是rpm安装， jstorm是安装到admin账户下的

**Comment by unsleepy22** [comment]
@wuchong 可以考虑加个web ui部署的文档

**Comment by yuanlai** [comment]
乌班图系统 一定要建一个admin管理员把jstorm放在下面吗 其他的文件呢 比如zookeeper

**Comment by wuchong** [comment]
@yuanlai  jstorm不限制安装的用户，可以用其他用户安装jstorm，安装在任意目录， 在安装完后需要配置 `JSTORM_HOME` 和 `PATH`

```
vi ~/.bashrc

export JSTORM_HOME=/XXXXX/XXXX

export PATH=$PATH:$JSTORM_HOME/bin
```

zookeeper  也没有限制，参考zookeeper的安装手册
