### ISSUE TITLE
访问UI首页时报错

### ISSUE THREAD

**Issue by ecliar** [alibaba/jstorm#143]
![image](https://cloud.githubusercontent.com/assets/1331705/11708416/18074188-9f4a-11e5-842f-04f39e45b14b.png)

190167 [qtp1806121021-18] ERROR com.alibaba.jstorm.ui.utils.UIUtils - java.lang.RuntimeException: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection timed out: connect
java.lang.RuntimeException: java.lang.RuntimeException: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection timed out: connect
	at backtype.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:80) ~[jstorm-core-2.1.0.jar:na]
	at backtype.storm.utils.NimbusClient.getConfiguredClient(NimbusClient.java:45) ~[jstorm-core-2.1.0.jar:na]
	at backtype.storm.utils.NimbusClient.getConfiguredClient(NimbusClient.java:40) ~[jstorm-core-2.1.0.jar:na]
	at com.alibaba.jstorm.ui.utils.NimbusClientManager.getNimbusClient(NimbusClientManager.java:65) ~[classes/:na]
	at com.alibaba.jstorm.ui.utils.UIUtils.flushClusterCache(UIUtils.java:163) [classes/:na]
	at com.alibaba.jstorm.ui.utils.UIUtils.readUiConfig(UIUtils.java:143) [classes/:na]
	at com.alibaba.jstorm.ui.utils.UIUtils.<clinit>(UIUtils.java:97) [classes/:na]
	at com.alibaba.jstorm.ui.controller.ClustersController.show(ClustersController.java:42) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]

**Comment by unsleepy22** [comment]
@wuchong take a look~

**Comment by wuchong** [comment]
能看下你的集群配置吗？

**Comment by ecliar** [comment]
########### These MUST be filled in for a storm configuration
 storm.zookeeper.servers:
     - "58.215.*.*"

 storm.zookeeper.root: "/jstorm"
 
 #nimbus.host is being used by $JSTORM_HOME/bin/start.sh
 #it only support IP, please don't set hostname
 # For example 
 # nimbus.host: "10.132.168.10, 10.132.168.45"
 nimbus.host: "58.215.*.*"
 
# %JSTORM_HOME% is the jstorm home directory
 storm.local.dir: "%JSTORM_HOME%/data"
 
 java.library.path: "/usr/local/lib:/opt/local/lib:/usr/lib"



# if supervisor.slots.ports is null, 
# the port list will be generated by cpu cores and system memory size 
# for example, if there are 24 cpu cores and supervisor.slots.port.cpu.weight is 1.2
# then there are 24/1.2 ports for cpu, 
# there are system_physical_memory_size/worker.memory.size ports for memory 
# The final port number is min(cpu_ports, memory_port)
 supervisor.slots.ports.base: 6800
 supervisor.slots.port.cpu.weight: 1
 supervisor.slots.ports: null
#supervisor.slots.ports:
#    - 6800
#    - 6801
#    - 6802
#    - 6803

# Default disable user-define classloader
# If there are jar conflict between jstorm and application, 
# please enable it 
 topology.enable.classloader: false

# enable supervisor use cgroup to make resource isolation
# Before enable it, you should make sure:
# 	1. Linux version (>= 2.6.18)
# 	2. Have installed cgroup (check the file's existence:/proc/cgroups)
#	3. You should start your supervisor on root
# You can get more about cgroup:
#   http://t.cn/8s7nexU
 supervisor.enable.cgroup: false


### Netty will send multiple messages in one batch  
### Setting true will improve throughput, but more latency
 storm.messaging.netty.transfer.async.batch: true

### if this setting  is true, it will use disruptor as internal queue, which size is limited
### otherwise, it will use LinkedBlockingDeque as internal queue , which size is unlimited
### generally when this setting is true, the topology will be more stable,
### but when there is a data loop flow, for example A -> B -> C -> A
### and the data flow occur blocking, please set this as false
 topology.buffer.size.limited: true
 
### default worker memory size, unit is byte
 worker.memory.size: 2147483648

# Metrics Monitor
# topology.performance.metrics: it is the switch flag for performance 
# purpose. When it is disabled, the data of timer and histogram metrics 
# will not be collected.
# topology.alimonitor.metrics.post: If it is disable, metrics data
# will only be printed to log. If it is enabled, the metrics data will be
# posted to alimonitor besides printing to log.
 topology.performance.metrics: true
 topology.alimonitor.metrics.post: false

# UI MultiCluster
# Following is an example of multicluster UI configuration
 ui.clusters:
     - {
         name: "jstorm.share",
         zkRoot: "/jstorm",
         zkServers:
             [ "58.215.*.*"],
         zkPort: 2181,
       }


--------------------------
这是ui的storm.yaml

**Comment by wuchong** [comment]
你集群(nimbus)的配置也是用的这一套吗？

**Comment by ecliar** [comment]
是的

**Comment by ecliar** [comment]
我调试源码时就是没找到它连哪里，我的zookeeper是OK的

**Comment by wuchong** [comment]
这个错是连接nimbus超时。 不知道是不是nimbus启动有问题。

**Comment by longdafeng** [comment]
应该是你yaml 格式不对， 你找个yaml 分析器，看是否可以分析你的数据。

很有可能是你空格没有对齐


统一ui 这个功能，我们天天用的， 非常好用
