### ISSUE TITLE
Jstorm 可以接入C++的应用吗？ 有开发样例吗？

### ISSUE THREAD

**Issue by inbei** [alibaba/jstorm#144]
我是做C++开发的，请问有JStorm接入C++应用的开发样例吗？谢谢！

**Comment by longdafeng** [comment]
可以支持多语言， 但如果不是运行在jvm上的语言，性能都是非常差的。

怎么运行多语言， 麻烦参考 

https://github.com/apache/storm/blob/master/examples/storm-starter/src/jvm/storm/starter/WordCountTopology.java
