### ISSUE TITLE
单机部署jstorm,运行后一直提示错误:TopologyMetricsRunnable] exceeding maxPendingUploadMetrics, skip metrics data for topology:__CLUSTER__

### ISSUE THREAD

**Issue by adian98** [alibaba/jstorm#145]
请问这个问题是如何产生的,怎么解决

[ERROR 2015-12-11 09:01:55 c.a.j.d.n.TopologyMetricsRunnable:686 TopologyMetricsRunnable] exceeding maxPendingUploadMetrics, skip metrics data for topology:__CLUSTER__
[INFO 2015-12-11 09:02:00 c.a.j.d.n.ServiceHandler:1256 pool-8-thread-51] Received topology metrics:__NIMBUS__
[ERROR 2015-12-11 09:02:00 c.a.j.d.n.TopologyMetricsRunnable:686 TopologyMetricsRunnable] exceeding maxPendingUploadMetrics, skip metrics data for topology:__NIMBUS__
[INFO 2015-12-11 09:02:05 c.a.j.d.n.TopologyMetricsRunnable:549 TopologyMetricsRunnable] refresh topologies, cost:0
[INFO 2015-12-11 09:02:55 c.a.j.d.n.TopologyMetricsRunnable:175 pool-6-thread-1] cluster metrics force upload.
[INFO 2015-12-11 09:02:55 c.a.j.d.n.TopologyMetricsRunnable:607 pool-6-thread-1] send update event for cluster metrics, size : 0
[ERROR 2015-12-11 09:02:55 c.a.j.d.n.TopologyMetricsRunnable:686 TopologyMetricsRunnable] exceeding maxPendingUploadMetrics, skip metrics data for topology:__CLUSTER__
[INFO 2015-12-11 09:03:00 c.a.j.d.n.ServiceHandler:1256 pool-8-thread-52] Received topology metrics:__NIMBUS__
[ERROR 2015-12-11 09:03:00 c.a.j.d.n.TopologyMetricsRunnable:686 TopologyMetricsRunnable] exceeding maxPendingUploadMetrics, skip metrics data for topology:__NIMBUS__

**Comment by wuchong** [comment]
最新的版本已经fix这个问题了，你用master分支编译一个应该就没问题了
