### ISSUE TITLE
worker.childopts  worker.memory.size 这两个参数有何区别？

### ISSUE THREAD

**Issue by yuhan0501** [alibaba/jstorm#146]
worker.childopts  worker.memory.size 这两个参数有何区别？

**Comment by longdafeng** [comment]
推荐使用worker.memory.size 参数去设置内存大小， worker的gc算法由jstorm 使用配置好的cms gc 参数

worker.childopts/worker.gc.childopts  2个参数是一样，等质的，这个也可以设置worker 内存大小，不过 主要如果觉得jstorm的cms gc参数不符合你自己的app， 可以调整gc 参数和gc 算法。
