### ISSUE TITLE
nohup: 无法运行命令"jstorm": 没有那个文件或目录  请问可能是什么原因啊

### ISSUE THREAD

**Issue by uptop** [alibaba/jstorm#148]
环境：Ubuntu14 jdk1.8 jstorm0.9.6.3 python2.7 zookeeper3.4.6

**Comment by unsleepy22** [comment]
jstorm/bin需要在path中。另外，目前jdk1.8还有问题，主要是defaults.yaml里有一个不兼容的JVM参数，2.1.1会兼容jdk1.8。

**Comment by yuanlai** [comment]
2.1.1有下载地址不

**Comment by unsleepy22** [comment]
2.1.1暂时还没有release，你如果现在要用的话，可以用2.1.0，但是需要自己修改一下项目中的defaults.yaml（你搜索一下文件），把里面的MaxTenuringThreshold这个JVM选项删掉，然后自己用build一下就可以。

**Comment by penuel-leo** [comment]
建议配置好jstorm环境后，直接运行jstorm nimbus/supervisor然后很直观的看错误

**Comment by longdafeng** [comment]
你jstorm 脚本没有放到PATH 环境变量里面，当然找不到jstorm
