### ISSUE TITLE
storm：spout fail 但是bolt正常

### ISSUE THREAD

**Issue by baobingzhe** [alibaba/jstorm#151]
在topology  build时，builder.setSpout("storm-input",new Jmspout(),4).setNumTasks(10)，这种情况会出现一部分消息处理时spout直接调fail()的情况，但是bolt正常，超时时间设置是30。
这样设置的目的是，目前使用的worker数为4，如果想扩展worker数的话，我只需要rebalance一下就可以了，bolt设置NumTasks的时候不会有问题，就是spout出现这样的情况。
storm的版本是0.9.2，针对扩展worker数时想同时扩展spout数，有没有更好的方法？

**Comment by longdafeng** [comment]
storm 不能动态调整task 并发， jstorm 有，你必须切到jstorm才能达到这种效果
