### ISSUE TITLE
mvn compile jstorm-all error

### ISSUE THREAD

**Issue by penuel-leo** [alibaba/jstorm#152]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project jstorm-all: Exit code: 2 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

need to use commands "gpg --gen-key"?

**Comment by Liuxboy** [comment]
你好，jstorm的pom中在此处配置了maven插件，
                     <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
一、gpg官方网站在这里https://www.gnupg.org/index.html。是在Git安装的bin里面的一个命令；
二、具体功能没有研究，等大神来解答，但看首页的“The GNU Privacy Guard”大概可以明白，是GNU、私钥保护方面的东西。
三、再看插件配置是verify阶段用到，所以可以在maven中进行verify操作。
我本地报错如下：
[INFO] --- maven-gpg-plugin:1.6:sign (sign-artifacts) @ jstorm-core ---
gpg: error loading `iconv.dll': �Ҳ���ָ����ģ�顣

gpg: please see http://www.gnupg.org/download/iconv.html for more information
gpg: NOTE: --use-agent is not available in this version
gpg: no default secret key: secret key not available
gpg: signing failed: secret key not available
这里可以看出，缺少一个iconv.dll，再查到官网去下载这个dll
https://www.gnupg.org/download/iconv.html
然后运行：
gpg --gen-key，按照提示，一步步生成key

然后再运行mvn clean，compile试试

Good Luck！

**Comment by penuel-leo** [comment]
Thx
