### ISSUE TITLE
Nimbus启动了Slave，但是主的挂了以后，前端也是同样打不开

### ISSUE THREAD

**Issue by breezyjin** [alibaba/jstorm#154]
Nimbus启动了Slave，但是主的挂了以后，前端也是同样打不开

**Comment by longdafeng** [comment]
可以打开的， 如果slave 没有完成同步， master 挂了， slave 备promte成master 需要等待2分钟

**Comment by breezyjin** [comment]
非常感谢，确实会，时间等久一点就会Slave自动切换Master。
