### ISSUE TITLE
jstorm-kafka 和 storm-kafka有什么区别或者优化？ 

### ISSUE THREAD

**Issue by Dollyn** [alibaba/jstorm#155]
还有，上次提到的疑似kafka-spout多线程的问题看了一下，用的是storm-kafka， 是否jstorm-kafka 对多线程做了什么优化？ storm-kafka是否不能用在jstorm环境下?

**Comment by longdafeng** [comment]
jstorm 对spout做了性能优化， nexttuple 使用一个线程， ack／fail 使用一个线程， 也就是spout内部有2个执行线程， 并且鼓励nexttuple做block操作，有数据就emit，没有数据时，block住， 这样可以节省cpu时间

storm里面只有一个执行现场， 先执行nexttuple，然后执行ack／fail， nexttuple／ack／fail 里面不允许阻塞或长时sleep操作，否则容易超时， 带来的问题时，当没有数据时，容易空跑，浪费cpu。 


（1）可以设置jstorm的spout 回退到单线程模式 设置  spout.single.thread: true
（2）社区storm 2.0， 很有可能切到jstorm 双线程模式

**Comment by easyreal** [comment]
楼上答非所问啊，我也想问一下storm-kafka是否不能用在jstorm环境下。
另外楼上说的“鼓励nexttuple做block操作”，如果用了jstorm-kafka ，那么nexttuple这个方法也不归我管啊

**Comment by Dollyn** [comment]
我的分析，storm-kafka最好不要用在jstorm环境下，参考 #133 应该就是因为jstorm里面ack和nextuple是两个不同的线程，而storm-kafka里应该是没考虑这种情况，具体在PartitionManager这个类里面，_pending这个map没有做线程安全保护的情况下，ack,fail,next都直接在使用这个map.

但是这个究竟会产生多大的影响还不知道，因为我们这个目前毕竟不是核心系统，有点小问题也不容易被发现...

**Comment by easyreal** [comment]
谢谢Dollyn

我想借这个地方问一下阿里内部使用了jstorm-kafka了吗，因为maven仓库里没有，而且我看源码里有些注释掉的代码，所以不请求jstorm-kafka是否可用，版本是2.1.0

另外我们用的kafka版本是0.9.0，提供了新的客户端api，而且offset可用记在kafka里了，我想问下是否有计划升级jstorm-kafka以支持kafka 0.9.0，谢谢

**Comment by zhaiyuyong** [comment]
storm-kafka可以用在jstorm上的，如果出现线程安全问题 正如龙大说的 可以设置spout.single.thread: true 或者对于日志类的应用不开ack也没问题。

**Comment by easyreal** [comment]
github有人基于storm-kafka改了一版jstorm的版本，支持多线程
https://github.com/chenatu/jstorm-kafka

**Comment by liuxuan207** [comment]
https://github.com/chenatu/jstorm-kafka
这个版本的有个bug，需要捕获lastCompletedOffset方法里_pending.firstKey()的NullPointerException.

**Comment by darouwan** [comment]
@zhaiyuyong 对于jstorm 2.1.1，应该使用哪个版本的kafka spout？我看到jstorm在github上也有一个kafka spout，但是没有什么文档说明。不知是否能够提供使用的例子？
