### ISSUE TITLE
The command 'jstorm update_topology -jar x.jar -conf x.yaml ' does't work

### ISSUE THREAD

**Issue by aspoman** [alibaba/jstorm#157]
I use a new jar or conf to update running topology, like this 'jstorm update_topology topologyName -jar new.jar', but it does't work, I'd like to known it's a wrong command or not?

**Comment by hustfxj** [comment]
Bolts which need update conf.yaml must be derived from IDynamicComponent.

**Comment by aspoman** [comment]
OK,thanks I'll try it
