### ISSUE TITLE
关于supervisor slot 生成算法

### ISSUE THREAD

**Issue by wgb1990** [alibaba/jstorm#158]
麻烦大家介绍一下supervisor slot 生成算法，谢谢！

**Comment by hustfxj** [comment]
根据机器和cpu和内存，以及worker设置的cpu和内存默认值，计算一台机器顶多可以配置多少个slot

**Comment by wuchong** [comment]
如果你没有设置 `supervisor.slots.ports` , jstorm 会去取 `supervisor.slots.port.cpu.weight`和`supervisor.slots.port.mem.weight`，这两个的默认值分别是 1.2 和 0.8。如果你是 32核,   16G 内存的机器， 那么 根据cpu算出来是slot数是 32/1.2=26， 根据mem算出来的是 16/0.8=20， 两者之间取小值， 也就是会分配 20个slot。然后根据`supervisor.slots.ports.base: 6800`累加出各个slot对应的port。最后分配出来的端口号是 6800~6819
