### ISSUE TITLE
TransactionalSpoutCoordinator Bug情况

### ISSUE THREAD

**Issue by AlbertCCC** [alibaba/jstorm#159]
在使用TransactionalSpoutCoordinator中的sync方法时，在生成新的TransactionAttempt的时候，如果正在运行的transaction小于_maxTransactionActive ，会出现异常。_maxTransactionActive 为10。
假如正在运行的transactionID为1,2  下一个transactionId应该为3  但是当for循环遍历时，如果在curr变成4的时候正好有任务需要执行，这个时候transactionId为4  无法匹配到上一个transactionId为3  抛出异常Expecting previous txid state to be the previous transaction。
请确认该异常情况。

**Comment by longdafeng** [comment]
这个不是bug， trident的为了保证commit的强顺序性， 强制要求一个接着一个。

而且很多时候 maxspoutpending 为1， 所以不会有什么问题
