### ISSUE TITLE
资源隔离机制

### ISSUE THREAD

**Issue by inter12** [alibaba/jstorm#162]
底层隔离采用的是cgroup ,若是不想采用cgroup , 默认采用的还是storm自身的隔离机制吗？
那么若是采用storm自身机制的话，那么在新增任务时候，还是会不会去竞争已经存在任务的slot吗？之前的任务隔离机制是否失效？

**Comment by longdafeng** [comment]
先拓展你的问题 －－ 如何做资源隔离

（1）对于一些超级重要或者流量非常大的应用，都是直接独立部署，这样资源隔离是最彻底的，然后通过统一ui来管理多个集群， 另外补充一句， jstorm实际上支持，在一台网关机上，讲任务提交到不同的集群中。
（2）在单集群内做资源隔离， 有2种手段。
（2.1） 使用自定义调度的isolation.scheduler.machines 配置，指定机器列表，强制你任务运行在这批机器上， 和storm的效果类似， 但有点区别，它不会杀死指定机器上老的其他topology worker。 这种方式其实是可以达到资源隔离的效果的
（2.2） 打开jstorm的supervisor.enable.cgroup， 可以限制worker的cpu。


最后回答你的问题：
如果你的集群没有开cgroup， 新增任务可能会抢占老任务的cpu和网络， 当系统资源不够的时候。 如果系统资源够的话，问题不大。

但真正线上使用时，尤其是机器数量有限时，是非常有必要开cgroup， 因为你会发现，很多程序cpu浪费很严重，或者内存使用很夸张（带来的问题是 不停的full gc，非常消耗cpu，）
