### ISSUE TITLE
对于线上不同类型节点机器的配置建议

### ISSUE THREAD

**Issue by inter12** [alibaba/jstorm#164]
nimbus 和 Supervisor 建议的机器配置是如何的？
阿里线上的机器配置是如何？

**Comment by longdafeng** [comment]
其实jstorm不挑机器， 在配置不同的机器上都能自适配
另外，我曾经在小型机上跑过jstorm， 性能很好，但不稳定。

建议，一般cpu越强劲越好

阿里都是大规模采购，统一配置， 32核，128g， ssd， 2块千兆网卡，机房万兆交换机（部分交换机10万兆）
