### ISSUE TITLE
JStorm支持动态topology增减吗

### ISSUE THREAD

**Issue by RalphSu** [alibaba/jstorm#165]
[CC from users group]
如题

目前在storm上跑一些任务，想根据源的特点动态做一些动态的topology改动。storm目前是静态topology，jstorm在这方便有增强吗

**Comment by bastiliu** [comment]
支持运行时动态的修改component并发，但是暂时不支持修改topology结果（增加或减少component）

**Comment by longdafeng** [comment]
有2种方式：restart或rebalance 命令

jstorm restart $topologyname $conf.yaml
jstorm rebalance $topologyname $conf.yaml

$topologyname 是topology的名字
$conf.yaml 是配置文件

在conf.yaml 配置类似如下
```
#topology.spout.parallelism:
#    {
#        "spoutName" : Num
#    }
#topology.bolt.parallelism: null
#    {
#        "BoltName_1" : Num,
#        "BoltName_2" : Num
#    }
```
