### ISSUE TITLE
examples can not run

### ISSUE THREAD

**Issue by lwclover** [alibaba/jstorm#166]
examples can not run!
examples can not run!
examples can not run!

**Comment by longdafeng** [comment]
example 可以跑的啊，这个example每天都会在我们自动化测试中运行

你是tar包安装的，还是rpm安装的。

还是你本地模式运行。


你多给一些信息。

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
有没有针对git源码的使用说明文档 比如如何使用git上克隆的源代码运行一套完整的jstorm方案
