### ISSUE TITLE
关于jstorm中的task

### ISSUE THREAD

**Issue by justcodeforfun** [alibaba/jstorm#167]
看源码jstorm中的task number会发生变化，但是，向fieldsgrouping是需要根据task id来确定往哪个task里发送tuple的。那么task number变化，jstorm是如何保证fieldsgrouping的正确的

**Comment by hustfxj** [comment]
你可以看下RefreshConnections，里头会定时去检查task所有连接，如果需要，它会去更新TaskSendTargets里头的streamComponentgrouper，这样tuple每次做fieldsGrouping的时候保证下游的tasks都是合理的。

**Comment by justcodeforfun** [comment]
更新之后，不就无法保证field相同的tuple被分配到相同的task了吗？

**Comment by hustfxj** [comment]
对 存在这个问题。所以动态伸缩当前仅对shuffer grouping有效(Shuffer, Localfirst, LocalOrShuffer)

**Comment by bastiliu** [comment]
做一个自定义custom grouping吧，用一致性hash看看能不能解决这个问题

**Comment by justcodeforfun** [comment]
如果我使用了fieldsgrouping，task出现变化，比如减少了一个task，是不是就会一直处理失败了。
