### ISSUE TITLE
有针对git源码的使用说明吗 比如如何直接使用克隆的代码部署一套完整的jstorm框架

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [alibaba/jstorm#169]

**Comment by unsleepy22** [comment]
见：https://github.com/alibaba/jstorm/wiki/%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85

**Comment by unsleepy22** [comment]
git的源码 ，编译打包之后，在target目录下会有一个类似aloha-tgz/jstorm-2.1.0的目录，其中jstorm-2.1.0就是完整的jstorm binary，再参照上面的安装文档即可。
