### ISSUE TITLE
KafkaSpout里的open方法里为什么要调用一下config.configure(conf);

### ISSUE THREAD

**Issue by Dollyn** [alibaba/jstorm#172]
![image](https://cloud.githubusercontent.com/assets/184413/11955067/439ebc9c-a8e9-11e5-84e7-73d6bbd0f3b4.png)

RT，这种写法如果是在拓扑里只有一个kafkaspout的情况下，并且配置文件中kafka的配置都在第一级的情况下没有问题，但是因为我们有两个，只能这样：
![image](https://cloud.githubusercontent.com/assets/184413/11955138/15d555d6-a8ea-11e5-931d-a78ed7b98a9b.png)

所以导致在这里重新调用configure()方法后，kafka的配置全都变成了默认值。

我们现在把这一行代码注释掉，暂时没发现其他问题，所以猜测这个调用**只是** 为了兼容kafkaspout的无参构造函数，希望确认一下，这个调用有没有其他的考虑，如果去掉这行代码有没有其他副作用。

**Comment by Dollyn** [comment]
想了一下，这个应该算个bug，因为这个调用使得另外一个带参数的构造方法 KafkaSpout(config) 传入的配置无效，最终会被storm_config覆盖或者变成默认值

**Comment by unsleepy22** [comment]
可以提个PR

**Comment by wuchong** [comment]
addressed in  #174
