### ISSUE TITLE
依赖JStorm-2.1的项目能在版本更低的集群（如JStorm0.9.6.2集群）中运行吗

### ISSUE THREAD

**Issue by zengxmy** [alibaba/jstorm#177]
如题，期待回复，谢谢

**Comment by unsleepy22** [comment]
不兼容的，thrift版本和结构都不一样了，zk结构也不一样。

**Comment by zengxmy** [comment]
谢谢，是不是依赖包和集群的版本一定要统一？

**Comment by unsleepy22** [comment]
基本上要统一吧，也不是严格的。目前jstorm有两个版本，一个是0.9系列，这个系列的几乎所有版本，都是兼容的，但是不同版本之间的升级，可能需要重启topology，因为zk结构可能不一样。另外一个是2.x版本，这个版本是merge apache的版本，这个变化比较大，最大的是thrift从原来的0.7升级到了0.9.2，然后thrift的结构也发生了比较大的变化，这会导致很多都是不向后兼容的了。当然还是建议使用2.1.0这个版本，因为它有非常强大的metric system（比0.9.x系列以及storm都要强大得多），可以很方便地在这个基础上做问题排查或者监控报警。2.1.1年前也会发布，性能比2.1.0有了大幅提升，我们内部测试性能对0.9.x也有10%左右的提升。

**Comment by zengxmy** [comment]
初学storm jstorm，谢谢你详细的解释(*^__^*) ……
