### ISSUE TITLE
请问JStorm2.1是用netty还是zeromq作为消息队列？

### ISSUE THREAD

**Issue by zengxmy** [alibaba/jstorm#178]
如题。

**Comment by bastiliu** [comment]
用的Netty. 
ZMQ后面会完全移除

**Comment by zengxmy** [comment]
哦~~~    那么安装JStorm2.1时，不需要装zeromq和jzmq，而是要装netty了?

**Comment by zengxmy** [comment]
还是zeromq  jzmq  netty都需要安装?

**Comment by bastiliu** [comment]
都不需要去安装。netty的jar包，jstorm的安装文件里都带了
