### ISSUE TITLE
UnknownHostException错误

### ISSUE THREAD

**Issue by liang2016** [alibaba/jstorm#179]

**Comment by liang2016** [comment]
![01](https://cloud.githubusercontent.com/assets/16539220/12089420/820922a2-b31f-11e5-86fb-76bc0b569ae5.png)

**Comment by longdafeng** [comment]
（1） 先说一下问题的根本原因是， 题主的nimbus机器 主机名设置不正确（/etc/hosts或网卡配置设置有问题， 运行hostname就会发现）， nimbus启动后，必须将自己的ip注册到zk中，但题主的nimbus获取ip失败，因此注册到ZK 的hostname是null （有很多case是localhost）， 当supervisor连接nimbus时，拿到的是"localhost", 因此不可能成功连接nimbus

解决办法：
重新配置机器的/etc/hosts， 请baidu 搜索如何设置机器 hostname， 这里不做详细介绍
执行命令 hostname -i 能获得正确的ip，那就是ok的
