### ISSUE TITLE
实时计算结果数据落地的问题

### ISSUE THREAD

**Issue by yamanko** [alibaba/jstorm#181]
各位大神，用jstorm做实时计算的时候，结算结果的数据各位是如何落地的？落在什么数据存储结构上，内存，mysql，hbase又或者其他？如果需要把数据结果实时在UI端展示，数据落在哪里最方便，性能最好

**Comment by xinchun-wang** [comment]
没有什么通用的存储框架。一般是：需要和Topology中间进行数据交互的用内存数据库，如Redis，减少延迟同时提供高并发支持；如果最终少量汇聚结果，并且方便二次聚合，可以考虑关系型数据库。根据你的业务特点、使用场景来权衡吧。

**Comment by zhaiyuyong** [comment]
可以考虑 redis+hbase

**Comment by longdafeng** [comment]
redis ＋ hbase 非常不错， 推荐使用
