### ISSUE TITLE
关于--include-jars的用法

### ISSUE THREAD

**Issue by runLiu** [alibaba/jstorm#187]
JStorm2.1.0使用--include-jars 在提交任务时，希望将依赖jar一起分发所有Worker，但实际运行中，却报ClassNotFoundException，也就是加载不到依赖jar，想问下--include-jars的使用与含义

**Comment by unsleepy22** [comment]
--include-jars只是客户端在提交的时候include的，并不会真正上传。举例来说，我在jstorm jar的时候，我的应用jar的main依赖本地一个native的jar包，这时可以用--include-jars来确保应用jar的main不会报ClassNotFound。如果想要达到你的目的，还是需要用maven-assembly-plugin或者maven-shade-plugin把依赖打包进去。

**Comment by longdafeng** [comment]
jstorm 提供--lib 功能， lib 里面的jar会被上传到每个worker， 怎么使用，麻烦看看example  https://github.com/alibaba/jstorm/blob/master/example/sequence-split-merge/src/main/java/com/alipay/dw/jstorm/example/sequence/SequenceTopologyTool.java

**Comment by runLiu** [comment]
StormSubmitter.submitTopology(String name, Map stormConf, StormTopology topology, SubmitOptions opts, List<File> jarFiles)
该方法会把最后一个参数所有依赖jar一起上传，分发所有Worker，调用该方法解决，谢谢
