### ISSUE TITLE
Why com.alibaba.jstorm.daemon.nimbus.TopologyMetricsRunnable.run CPU 100%

### ISSUE THREAD

**Issue by juaby** [alibaba/jstorm#188]
centos 7.2
jstorm 2.1

jstack info:

"TopologyMetricsRunnable" prio=10 tid=0x00007ff2fc69a800 nid=0xc54 runnable [0x00007ff2939e4000]
   java.lang.Thread.State: RUNNABLE
        at com.alibaba.jstorm.daemon.nimbus.TopologyMetricsRunnable.run(TopologyMetricsRunnable.java:254)

**Comment by juaby** [comment]
Event event = queue.poll(1,TimeUnit.MILLISECONDS);
if (event == null) {
    continue;
}

here?loop?very violenly!

**Comment by longdafeng** [comment]
This is a bug of 2.1.0, fixed in 2.1.1. You can build one binary with the latest github code.
