### ISSUE TITLE
why get Public IP == > masterHost:202.1XX.1XX.XX:7627

### ISSUE THREAD

**Issue by juaby** [alibaba/jstorm#191]
JSTROM 2.1
JAVA 1.7_80
CENTOS 7.2

202.1XX.1XX.XX

why get Public IP?
[INFO  2016-01-25 14:18:31 ThriftClient:108 http-bio-8080-exec-4] masterHost:202.1XX.1XX.XX:7627

**Comment by juaby** [comment]
InetAddress.getLocalHost().getHostAddress()

**Comment by juaby** [comment]
public FollowerRunnable(final NimbusData data, int sleepTime) {
        this.data = data;
        this.sleepTime = sleepTime;

        if (!ConfigExtension.isNimbusUseIp(data.getConf())) {
            this.hostPort = NetWorkUtils.hostname() + ":" + String.valueOf(Utils.getInt(data.getConf().get(Config.NIMBUS_THRIFT_PORT)));
        } else {
            this.hostPort = NetWorkUtils.ip() + ":" + String.valueOf(Utils.getInt(data.getConf().get(Config.NIMBUS_THRIFT_PORT)));
        }

**Comment by juaby** [comment]
ping `hostname`
must config /etc/hosts

**Comment by longdafeng** [comment]
There are two network adaptor in you machine, one is public ip, the other is private ip, you prefer to use private ip.

But the jstorm will call "InetAddress.getLocalHost().getHostAddress()" to get ip of node, the function will normally return public ip, you can google the details of the api. 

if you want to use the private ip, please set the /etc/hosts
