### ISSUE TITLE
ack机制的fail问题

### ISSUE THREAD

**Issue by gaga0808** [alibaba/jstorm#193]
今天在本地模式下，试验ack机制， 
    其中wiki里介绍 ： 在规定的时间内，没有收到Acker的ack响应tuple，就触发fail动作，
    即认为该tuple处理失败。这个规定的时间，是怎么设置的？ 
    本人尝试用conf.setMessageTimeoutSecs(10); 设置10秒。
    并且在bolt处理时，不调用collector.fail方法，。
   结果过了两三分钟才触发spout的fail方法。
   请问难道不是在这里设置这个时间的么？
   如果不是那应该在哪里设置？

**Comment by wuchong** [comment]
请问你是怎么保证让消息丢失掉的呢？   bolt中不ack吗 ?

**Comment by gaga0808** [comment]
正常调用collector.fail 和 collector.ack方法  的确会立即触发spout 的fail动作
在这里我是想试验下 在多久的时间内没有接受到Acker的ack响应,会触发fail动作，
所以在bolt里 故意不调用collector的ack方法，相当于永久不会接受到Acker的ack响应,
看多久会触发spout的fail方法，结果时间篇长 达到两三分钟才触发，而不是10秒

**Comment by wuchong** [comment]
由于task的启动需要一定的时间， 所以第一次的过期操作默认会延迟2分钟执行，否则可能造成消息刚发出去，就执行了过期操作。

如果你想调整第一次的过期操作的延时，可以设置`Config.SUPERVISOR_WORKER_START_TIMEOUT_SECS`。

**Comment by gaga0808** [comment]
根据你的提示，测试了下，果真如此。3Q拉.   
                                                                                                                                                 gaga~~~
