### ISSUE TITLE
如何确保拓扑被kill时数据不丢失？

### ISSUE THREAD

**Issue by jinyunx** [alibaba/jstorm#194]
如题，如何确保拓扑被kill时数据不丢失？此处的数据是指已经在拓扑中流动的数据，但是还没流到拓扑的末端，也即是还没被处理完。
我的假想是这样的，拓扑被kill时，spout不会再取数据，此时jstorm应该会等一个小时间，让拓扑内的数据尽可能被处理完，时间到，即timeout后，不管数据是否丢失，所有task都被kill。
那么不知这个timeout的大小是哪里设置？
尝试过增大supervisor.worker.shutdown.sleep.secs和task.cleanup.timeout.sec，均没达到预期效果。

另外，jstorm在等待数据被处理完过程中，也就是还没timeout之前，数据已经全部被处理完了，那么jstorm是继续等（等到timeout为止），还是说不再等直接结束？

感谢各位对jstorm的辛勤付出，致敬！

**Comment by unsleepy22** [comment]
jstorm kill <topology_name> [wait_time_sec]

这个命令就可以等待指定的时间。但是jstorm不会去检查这个时间内，消息有没有被处理完。因为这个检查很可能是没有意义的，比如说消息处理失败触发了上游的重发，那有可能永远也不会处理完，或者说如果没有开acker，那也不会知道消息有没有被处理完。

**Comment by bastiliu** [comment]
kill topology的时候主要分为两个阶段。
第一个是在jstorm kill topologyName [delayTime]里的delayTime，这个等待时间默认为消息的超时时间，当开始kill topology的时候，所有的spout会进入deactive状态，也就是spout不会再执行nextTuple，让下游的bolt处理已经发出的消息。
当这个deactive等待时间超时后，我们会进入第二个阶段。开始真正的kill topology，shut down所有的task。这时候会回调用户自定义的cleanup()，一般我们在这里做最后的一些清理操作。cleanup最长的等待时间为task.cleanup.timeout.sec这个配置。也就是说cleanup如果在task.cleanup.timeout.sec时间内结束，task在cleanup后就正常了。如果超过了这个时间还没有结束，我们也会强制kill -9对应的worker进程，保证worker都被杀死。
所以你可以根据你的任务情况，去设置这两个超时时间。

**Comment by jinyunx** [comment]
好的，弄明白了，非常感谢！
想问多一个问题，不知acker机制如何关闭？之前看文章《storm @ twitter》知道acker机制是storm性能的瓶颈之一，本人想测试一下在jstorm的影响。

**Comment by unsleepy22** [comment]
Config.setNumAckers(0);就可以关闭了

2016-01-27 15:11 GMT+08:00 jinyunx <notifications@github.com>:

**Comment by jinyunx** [comment]
好的，非常感谢！
