### ISSUE TITLE
jstorm需要打开的端口有哪些？

### ISSUE THREAD

**Issue by rayihong** [alibaba/jstorm#196]
现在环境搭的集群是把防火墙已经关闭了。但是现在需要开启防火墙。想知道jstorm总共监听了哪些端口谢谢。

**Comment by unsleepy22** [comment]
jstorm本身的端口并不多，http API端口（2.1.1默认8000）， thrift端口（默认8627），drpc（如果开的话）默认4772，4773，3774，http日志端口8621，8622，具体看一下项目中的defaults.yaml就可以了。但是jstorm底层是使用netty来通信的，netty开启的端口是未知的，所以除非你预留一个区间的端口给jstorm的java进程来使用，不然可能会有问题。

**Comment by luotianwen** [comment]
我的也是关闭了 我配置的是6800-6803 但是会出现6902 6901哪些端口 不知到防火墙要开那些端口
