### ISSUE TITLE
nimbus报错：exceeding maxPendingUploadMetrics, skip metrics data for topology:__NIMBUS__

### ISSUE THREAD

**Issue by lileichinasoft** [alibaba/jstorm#201]
部署版本：jstorm-2.1.0.tar.bz2

[INFO 2016-02-25 10:18:44 c.a.j.d.n.TopologyMetricsRunnable:549 TopologyMetricsRunnable] refresh topologies, cost:1
[INFO 2016-02-25 10:18:55 c.a.j.d.n.TopologyMetricsRunnable:175 pool-6-thread-1] cluster metrics force upload.
[INFO 2016-02-25 10:18:55 c.a.j.d.n.TopologyMetricsRunnable:607 pool-6-thread-1] send update event for cluster metrics, size : 0
[ERROR 2016-02-25 10:18:55 c.a.j.d.n.TopologyMetricsRunnable:686 TopologyMetricsRunnable] exceeding maxPendingUploadMetrics, skip metrics data for topology:__CLUSTER__
[INFO 2016-02-25 10:19:00 c.a.j.d.n.ServiceHandler:1256 pool-8-thread-46] Received topology metrics:__NIMBUS__
[ERROR 2016-02-25 10:19:00 c.a.j.d.n.TopologyMetricsRunnable:686 TopologyMetricsRunnable] exceeding maxPendingUploadMetrics, skip metrics data for topology:__NIMBUS__

**Comment by unsleepy22** [comment]
这个包是自己编译的么？如果是自己编译的应该不会有这个问题的。这个是之前的一个bug，已经fix了的。

**Comment by lileichinasoft** [comment]
@unsleepy22 
不是自己编译的包，是从这个地方下载的：http://42.121.19.155/jstorm/jstorm-2.1.0.tar.bz2

**Comment by unsleepy22** [comment]
你自己编译一下吧，bug fix只是源代码的更新，包没有更新的。

**Comment by lileichinasoft** [comment]
@unsleepy22 明白了，多谢！
