### ISSUE TITLE
nimbus频繁报error: exceeding maxPendingUploadMetrics

### ISSUE THREAD

**Issue by gaga0808** [alibaba/jstorm#206]
最近nimbus上的log里 频繁出现：
exceeding maxPendingUploadMetrics, skip metrics data for topology:__CLUSTER__
exceeding maxPendingUploadMetrics, skip metrics data for topology:__NIMBUS__
exceeding maxPendingUploadMetrics, skip metrics data for topology:ping-alarm-count-1-1456709112

有哪位朋友nimbus.log里也出现过这种错误的，知道是什么原因么？。虽然这个错误貌似不影响程序的运行，但心里看着总别扭，也担心这会对集群以后造成一些不为人知的错误。。。。

**Comment by unsleepy22** [comment]
请用最新的代码重新编译一下，这个问题在源码上很早就fix了，但是包没有更新。

**Comment by unsleepy22** [comment]
或者用刚刚release的2.1.1也可以

**Comment by gaga0808** [comment]
好的谢谢~
