### ISSUE TITLE
kafka-Spout并发问题

### ISSUE THREAD

**Issue by zhp510730568** [alibaba/jstorm#207]
kafka-spout报了并发引起的异常，nexttuple的并发执行，导致存储偏移号的集合需要考虑并发

**Comment by unsleepy22** [comment]
storm-kafka本身因为storm的nextTuple和ack是在同一个线程，所以不会有这个问题。jstorm中nextTuple和ack是两个线程，如果在nextTuple或ack中修改了共享的数据，可能会有这个问题，你可以把topology.max.spout.pending设置为1
