### ISSUE TITLE
Jstorm 如何对用户的权限进行设置？，应该在哪里设置

### ISSUE THREAD

**Issue by gaga0808** [alibaba/jstorm#210]
Jstorm 在 topology提交时，日志里有打印出相关的用户名，密码。JSTORM 集群该如何对用户名，密码之类的进行权限设置，有哪位懂的还请指点一下。

**Comment by unsleepy22** [comment]
JStorm目前并没有ACL相关的权限控制。。。

**Comment by gaga0808** [comment]
那提交topology时，日志中打印出来的user.name和user.password 这两个参数的作用是什么呢？

**Comment by longdafeng** [comment]
这2个参数现在不用了
这个是在早期，在 一个集群内，为不同的用户设置quota， 用来限制用户申请资源超过限制。
现在，阿里不用这个功能了。
