### ISSUE TITLE
com.alibaba.jstorm.daemon.nimbus.TopologyMetricsRunnable 修改获取队列的方式为 take

### ISSUE THREAD

**Issue by sniperxyp** [alibaba/jstorm#213]
public void run() {
        while (isShutdown != null && !isShutdown.get()) {
            if (localMode) {
                return;
            }

            try {
                // wait for metricUploader to be ready, for some external plugin like database, it'll take a few seconds
                if (this.metricUploader != null) {
                    Event event = queue.poll(1, TimeUnit.MILLISECONDS);
                    if (event == null) {
                        continue;
                    }

建议将上面的 
Event event = queue.poll(1, TimeUnit.MILLISECONDS); 修改成为 
Event event = queue.take();避免程序空转

**Comment by unsleepy22** [comment]
1ms的空转应该不会消耗多少cpu的

**Comment by longdafeng** [comment]
可以用take， 这样做问题也不大
差不多
