### ISSUE TITLE
bolt中Map线程安全的问题

### ISSUE THREAD

**Issue by yangdalong** [alibaba/jstorm#215]
阿里的朋友：
     您好！我想咨询一个问题，如果我的bolt中有一个HashMap，设定的并发个数大于1，这会不会产生HashMap争用或者导致HashMap线程不安全的问题？jstorm内部有这样一个保证bolt中变量访问隔离的机制吗？

**Comment by wuchong** [comment]
如果并发数大于1，导致一个worker中分配的bolt数大于1（视worker数决定），则会导致 hashmap 非线程安全。也就是说一个进程中有多个线程对这个hashmap进行了访问，是会有并发问题的。

 这个时候最好使用线程安全的容器， 比如 `ConcurrentHashMap`， jstorm内部没有你说的这种机制。

**Comment by yangdalong** [comment]
thank you, wuchong！感谢解答！
