### ISSUE TITLE
Jstorm项目日志

### ISSUE THREAD

**Issue by zengxmy** [alibaba/jstorm#217]
项目提交到集群上，在supervisor节点上可以看到运行的work日志，但是项目中打印的日志信息看不到，请问怎样才能输出项目的日志，需要配置什么东西吗？谢谢！

**Comment by wuchong** [comment]
使用 SLF4j 接口打日志，就可以把日志输出到 worker 日志中

**Comment by zengxmy** [comment]
log4j不可以吗

**Comment by wuchong** [comment]
使用 log4j 你需要使用自定义Log4j的配置文件

```
user.defined.log4j.conf: user.log4j.properties
```

参考： https://github.com/alibaba/jstorm/wiki/user_define_log_cn

**Comment by zengxmy** [comment]
这个配置项是在  storm.yaml文件里面配置吗

**Comment by wuchong** [comment]
storm.yaml 是对整个集群生效，你也可以只在拓扑中指定

```
ConfigExtension.setUserDefinedLog4jConf(conf, "user.log4j.properties");
```

**Comment by zengxmy** [comment]
谢谢你帅哥 O(∩_∩)O
