### ISSUE TITLE
jstorm-kafka的spout空跑问题

### ISSUE THREAD

**Issue by cocofree** [alibaba/jstorm#218]
当kafka数据生产速度小于消费时，log日志里面打了非常多的"fetch null message from offset"。
jstorm的spout已经将nextTuple和ack/fail分成两个线程，看了下jstorm-kafka的源码，是否可以给没有数据的partitionConsumer设置个缓冲时间，另外当所有partition都没有数据的时候增加个Thread.sleep(100)挂起线程，来减少空跑的次数？

**Comment by unsleepy22** [comment]
@cocofree 可以提PR来帮助我们改进～

**Comment by cocofree** [comment]
@unsleepy22 已提交，同时还改了另外两处碰到的问题
1、当partitionConsumer的offset超出范围时，原代码没做处理。调整为将emittingOffset更新为最新的offset，以可以继续消费新数据。
2、当kafka.fetch.from.beginning设置为true时，原代码每次重启拓扑都将重头读取，而不是从zk中获取已消费到的offset。调整为优先从zk中获取offset

**Comment by Dollyn** [comment]
关于#2 ， 一般来说设置kafka.fetch.from.beginning: true 就是想每次从头读取，个人认为这一点没有问题， Storm-kafka也是这么做的

**Comment by cocofree** [comment]
@Dollyn 我认为仅第一次从头读取，能解决重新发布拓扑又不想重复消费的场景。如果每次发布都想从头读取，可以设置不同的clientId~

**Comment by cocofree** [comment]
@Dollyn 仔细想了下，从字面理解和实际操作中，每次都从头读取更好一些。
@unsleepy22 帮忙也看一下，如果原来的逻辑没问题我这边恢复一下代码重新提交。

**Comment by unsleepy22** [comment]
我同意 @Dollyn 的看法，如果强制从上次的offset开始，那用户就没有选择了。如果优先从头开始，至少用户还是可以配置从上次offset继续的。

**Comment by cocofree** [comment]
嗯，已提交恢复代码。

**Comment by unsleepy22** [comment]
fixed
