### ISSUE TITLE
无法启动多个Supervisor

### ISSUE THREAD

**Issue by chenhuan14** [alibaba/jstorm#223]
supervisor不停的死掉，整个集群里每次都只有一个supervisor在运行

**Comment by xiaoyao2102** [comment]
你在部署的时候是不是都从一个做好的supervisor上复制出来的？
可以清一下data目录下的spervisor文件夹试试看

**Comment by unsleepy22** [comment]
supervisor.log中有没有异常日志

**Comment by longdafeng** [comment]
一套jstorm 的配置里面只能启动一个supervisor， 你可以把配置文件的本地目录和端口区间错开，就可以一台机器上启动多个supervisor
