### ISSUE TITLE
hivebolt异常导致worker重启和数据重复

### ISSUE THREAD

**Issue by gyisgood** [alibaba/jstorm#224]
使用github storm上的hivebolt，写数据进hive，在发生异常时（故意kill掉hive metastore进行测试），hivebolt调用了this.collector.reportError报告错误信息，然后发现运行到这一行代码就中止了（因为之后的日志木有打印出来），worker似乎被关掉重启了：Halting process，而且hive中写入的数据此时会有重复的

**Comment by unsleepy22** [comment]
spout/bolt的异常需要你自己来处理的，如果你不处理，jstorm捕捉到异常就会直接把worker杀掉

**Comment by gyisgood** [comment]
异常已捕获，使用collector.reportError上报异常，然后会导致worker重启

**Comment by unsleepy22** [comment]
那collector.reportError本身有没有抛出异常

**Comment by gyisgood** [comment]
对collector.reportError进行catch了，并没有捕获到异常

**Comment by gyisgood** [comment]
看到代码了：
下面这个构造函数，reportError 使用了TaskReportErrorAndDie这个类
	public BoltCollector(Task task, RotatingMap<Tuple, Long> tuple_start_times,
			int message_timeout_secs) {
		this.rotateTime = (1000L * message_timeout_secs / 2L);
		this.reportError = task.getReportErrorDie();

然后TaskReportErrorAndDie在report的时候，会停止进程：
	public void report(Throwable error) {
		this.reporterror.report(error);
		this.haltfn.run();
	}

**Comment by gyisgood** [comment]
但是，感觉还是不太对，为嘛reportError要把进程给halt掉

**Comment by longdafeng** [comment]
reportError api里面有专门 report错误的而不退出进程的
```
public void report(Throwable error) {
        this.reporterror.report(error);
        this.haltfn.run();
    }

    @Override
    public void report(String error) {
        this.reporterror.report(error);
    }

```

你应该用下面一个report(String error)

**Comment by gyisgood** [comment]
我也是这样想的，但是在bolt里面，该方法已经被OutputCollector给封装，只有一个report(Throwable error)
