### ISSUE TITLE
关于jstorm中JStorm basics in 5 min提到的每个worker中，又可以有多个task，分别代表一个执行线程。每个task就是上面提到的组件(component)的实现，要么是spout要么是bolt

### ISSUE THREAD

**Issue by low901028** [alibaba/jstorm#225]
如标题在jstorm里面是否bolt或者spout的代表物理线程？不是应该存在executor的概念么？ executor应该是代表对应的物理线程，一个executor是可以执行多个task，而task并不是如文档所说对应的物理线程。
按照个人理解应该：
   worker----->executor---->tasks(bolt/spout) 对应的是
    进程------->线程----->componet
不知是否是个人理解有问题，请解答下。 谢谢

**Comment by longdafeng** [comment]
jstorm里面没有executor

worker 代表进程
task代表线程
