### ISSUE TITLE
2.1.1有没有办法通过设置跳过Slot算法，强行指定可用port的数量？

### ISSUE THREAD

**Issue by Dollyn** [alibaba/jstorm#228]
rt，看过代码，2.1.1中slot算法有较大的改变，但是因为测试服务器上资源比较紧张，升级2.1.1后就根据计算可用的port数量变成只有一两个了... 被迫回退
希望能提供一种方式，能解决这种问题

**Comment by wuchong** [comment]
```
 supervisor.slots.ports:
    - 6800
    - 6801
    - 6802
    - 6803
```

这种方式可以强制指定端口，也强制指定了端口数

**Comment by Dollyn** [comment]
我们就是这样配置的，2.1.0 这种方式是可以的， 2.1.1中已经没用 了，简单看了下源码，2.1.1 会综合很多指标计算出一个值。

**Comment by unsleepy22** [comment]
可以在storm.yaml里调整这两个参数:
supervisor.slots.port.cpu.weight
supervisor.slots.port.mem.weight

可以将它们的值设为小于1，比如0.8，就会增加worker slot的数量

**Comment by unsleepy22** [comment]
我们考虑在2.1.2中添加一个配置来跳过自动调整

**Comment by longdafeng** [comment]
以前是可以的， 后面因为增加了tm和自定义调度， 当worker少的时候，这个地方会有些问题

**Comment by dulio** [comment]
测试过后发现强制指定端口在supervisor启动里有效
但是在topology操作（submit，kill）后还是会变成自动调整后的值

**Comment by unsleepy22** [comment]
2.1.1 supervisor是会自动调整的，按照我的方式，只要cpu或者memory使用率不是很高，应该能够把slot数加上去。

**Comment by maplejiong** [comment]
2.1.1发现在kill topology操作之后，之前占用的ports无法恢复，集群的ports usage越来越少

**Comment by unsleepy22** [comment]
我们明天发一个hot fix吧，加一个开关控制是否开启自动调整

**Comment by unsleepy22** [comment]
@maplejiong @dulio @Dollyn 刚刚发了一个hot fix，你们用master上最新的代码重新build一下吧，默认把supervisor的自动调整关闭了。

**Comment by unsleepy22** [comment]
见：https://github.com/alibaba/jstorm/commit/f26863bf14850e98ec413efb39bca5b85d4b59cc

**Comment by longdafeng** [comment]
这个应该不会的啊

不过，2.1.1 会根据cpu／memory动态调整， 在虚拟机环境下， 容易导致slot比较少。你用后面cody的那个patch吧

2016-03-29 20:35 GMT+08:00 maplejiong <notifications@github.com>:

**Comment by maplejiong** [comment]
@unsleepy22 @longdafeng ，看了下com.alibaba.jstorm.daemon.supervisor下的Heartbeat类
portList.removeAll(usedList)这句，由于是portList是引用传递，这样会导致可用port越来越少，即使kill topo也无法恢复，

**Comment by unsleepy22** [comment]
这个应该没问题的，只不过释放的时间比较长，需要1分钟后才能释放。你就用最新代码重新打包好了。
