### ISSUE TITLE
jstorm 0.9.6.2 定时器无法生效

### ISSUE THREAD

**Issue by splf32** [alibaba/jstorm#229]
public static boolean isTickTuple(Tuple tuple) {
		return tuple != null && Constants.SYSTEM_COMPONENT_ID.equals(tuple.getSourceComponent())
				&& Constants.SYSTEM_TICK_STREAM_ID.equals(tuple.getSourceStreamId());
}

这段代码的判断始终是false，定时器在本地调试时eclipse里可以正常运行，但是部署到jstorm集群上就无法生效，请问是什么原因？

**Comment by hustfxj** [comment]
Constants.SYSTEM_COMPONENT_ID.equals()  你把这个判断去掉去吧

**Comment by splf32** [comment]
去掉了也不会执行，这段代码的uple.getSourceComponent()和tuple.getSourceStreamId()并不会定时生成_system和_tick，我打印了集群的日志。

**Comment by longdafeng** [comment]
你的component configuration里面有没有设置  Config.TOPOLOGY_TICK_TUPLE_FREQ_SECS 呢


另外单位是秒， 不要弄错了

**Comment by longdafeng** [comment]
你jstorm什么版本？

0.9.6.3 或以上版本才支持

**Comment by longdafeng** [comment]
不用看了， 0.9.6.2 里面不支持， 建议升级到2.1.1

**Comment by splf32** [comment]
我试着升级到2.1.1，可以没起来，那我再试一下吧，多谢回复！

**Comment by longdafeng** [comment]
2.1.1 应该可以的， 楼主，问题解决了吗？

2016-03-25 17:41 GMT+08:00 splf32 <notifications@github.com>:

**Comment by splf32** [comment]
尝试安装2.1.1没成功，不过应该可以用吧，多谢回复！
