### ISSUE TITLE
topology在空闲状态下worker等java进程占用cpu问题

### ISSUE THREAD

**Issue by youngcle** [alibaba/jstorm#236]
jstorm 2.1.1

在jstorm中提交一个topology，在完全空闲状态下，每个worker的java进程cpu使用率在12-30%之间波动。在worker数量少的时候还无所谓，在worker数量设置较多时，这消耗有些不太合理了。
多个worker运行时，top里面一大片20%-30%的java进程，看着就吓人。

不知有无设置可以将静默状态的worker消耗cpu降到一个更加合理的程度。

**Comment by unsleepy22** [comment]
worker运行时本质上就是一个死循环，spout不停地调用nextTuple，bolt不停地调用execute。所以我觉得12～30%的CPU使用率是很正常的。每个worker理想的CPU使用是要至少跑满该worker所占的CPU slot权重（默认是1，也就是跑满1个CPU）。

**Comment by unsleepy22** [comment]
所以我理解，就算是空闲状态下，每个worker占用30%不到的CPU，系统还是有很大余量的。

**Comment by bastiliu** [comment]
如果worker里只分配了spout，你要看下是不是nextTuple空转引起的，如果没有emit任何数据，nextTuple空转就会有多余的cpu消耗。但是bolt的execute()是从执行队列拿到消息后才会被调用的，而disruptor queue的读取是阻塞方式(TimeoutBlocking)。这个是不会有太多cpu消耗的，我们测试结果应该是1%~5%。

对应spout的nextTuple空转，你可以让spout去实现SleepSpoutWaitStrategy接口，在没有消息要发送的时候用这个接口的emptyEmit方法。或者更简单的方式在没有消息要发送的时候，你sleep 1ms，就足够让spout所在worker的cpu使用率降到10%以内

**Comment by youngcle** [comment]
感谢回复，我再查查。
我的spout里面去redis读一个list，用的是jedis的阻塞方式api，brpop，因此按照我的理解，在list无数据时,spout，应该没啥损耗才对。

当然我对redis也不太熟悉，不知该阻塞模式有多大消耗。

测测再说

**Comment by qzhJie** [comment]
我在测试环境中，在完全空闲状态下。cpu消耗会达到200%-300% 。ui里面显示340+%，可能是什么原因呢？spout 是kafka
