### ISSUE TITLE
Bolt中创建新的线程是不是一个好的做法？

### ISSUE THREAD

**Issue by Dollyn** [alibaba/jstorm#242]
比如向Hbase中插入数据，一般需要批量插入以提高性能，一般会攒一批数据再调用hbase的批量插入方法，如果不在另外一个新线程中做这件事的话，性能还是上不去。 但是在Bolt中创建新线程又感觉有些奇怪

**Comment by hustfxj** [comment]
可以这么，其实我们做优化，也经常这么干
