### ISSUE TITLE
LocalCluster 本地模式不能执行

### ISSUE THREAD

**Issue by rongyousu** [alibaba/jstorm#243]
Config config = new Config();
config.setDebug(true);
 config.setMaxTaskParallelism(1);                
LocalCluster cluster = new LocalCluster();
 cluster.submitTopology("simple", config, topologyBuilder.createTopology());

在eclipse 里面执行本地模式的时候 ，控制台没有输出就结束了，请问是什么问题

**Comment by hustfxj** [comment]
你sleep下

**Comment by longdafeng** [comment]
你可以参考我们的example代码再看一下呢

**Comment by darionyaphet** [comment]
因为local模式运行在一个JVM钟 ，没有 sleep 线程直接就结束了  。
