### ISSUE TITLE
JStormHistogram对象升级后的问题

### ISSUE THREAD

**Issue by caiyifeng** [alibaba/jstorm#248]
您好：
     原来的应用中使用JStormHistogram对象来做一些操作统计，升级到2.1.1后该对象不支持了，请问用哪个对象替代了，如何使用？
多谢

**Comment by unsleepy22** [comment]
有AsmHistogram的。参考代码见example中sequence-split-merge工程TotalCount类

**Comment by longdafeng** [comment]
api确实改变了，需要参考@unsleepy22给的示例代码

**Comment by caiyifeng** [comment]
多谢多谢！解决了
