### ISSUE TITLE
调用restart命令，数据会丢失吗？

### ISSUE THREAD

**Issue by lazy0411** [alibaba/jstorm#254]
如题：
我调用restart命令，看Topology Summary页面上显示的是，Topology的Status先从Active变成Inactive，然后再变成Active，然后看各Task的状态，最终各task也是active。而Topology Id也是新产生了一个。

restart之前到restart之后，数据会丢失吗？

**Comment by unsleepy22** [comment]
会有可能。如果队列里堆积了较多数据，并且你的bolt处理速度较慢，那就有可能丢失。

**Comment by lazy0411** [comment]
可以通过指定一个时间参数，尽量减少堆积数据造成的影响吗？

**Comment by unsleepy22** [comment]
暂时还不行，kill是可以带时间参数的，但是restart没有带，现在是sleep 5s之后就会做kill操作
