### ISSUE TITLE
Task 任务总是dead

### ISSUE THREAD

**Issue by 1647917675** [alibaba/jstorm#257]
整个topology的提交时运行正常，但是总有一个task导致spout阻塞（我从Mq抓取数据设置了一个pending值）不再消费数据，然后spout   dead 之后任务也dead

**Comment by hustfxj** [comment]
是不是full gc

**Comment by 1647917675** [comment]
不是，我的topolog一直跑的很好，昨天挂了之后，再次重启集群就这样了，

**Comment by 1647917675** [comment]
我用的是0.963 版本的

**Comment by 1647917675** [comment]
看了一下日志是fullGc的问题

**Comment by 1647917675** [comment]
我之前跑的时候都是正常的，都已经上线3.4个月了，之间也是正常的reboot的集群，就是昨天之后就是这样子了

**Comment by 1647917675** [comment]
已经解决了。work的jvm的配置问题
