### ISSUE TITLE
建议能把carbonite 包依赖去掉，相关代码建议打包到项目内部，因为这个包在开放公共maven库已经找不到了

### ISSUE THREAD

**Issue by zhangyl** [alibaba/jstorm#258]
<dependency>
            <groupId>com.twitter</groupId>
            <artifactId>carbonite</artifactId>
            <version>1.4.0</version>
        </dependency>
另外:希望中文常见问题和英文常见问题内容保持同步

**Comment by longdafeng** [comment]
这个包是twitter， 我们没有权限自己上传这个包到maven库中
