### ISSUE TITLE
数据流分流和合并文档页面最后的示例代码缺失

### ISSUE THREAD

**Issue by noprom** [alibaba/jstorm#267]
- [数据流分流和合并](https://github.com/alibaba/jstorm/wiki/%E6%95%B0%E6%8D%AE%E6%B5%81%E5%88%86%E6%B5%81%E5%92%8C%E5%90%88%E5%B9%B6)这个页面最后的[示例代码](https://github.com/longdafeng/storm-examples)缺失。

- [事务](https://github.com/alibaba/jstorm/wiki/%E4%BA%8B%E5%8A%A1)这个页面最后的[事务原理](http://blog.linezing.com/2013/01/storm%E5%85%A5%E9%97%A8%E6%95%99%E7%A8%8B-%E7%AC%AC%E4%BA%94%E7%AB%A0-%E4%B8%80%E8%87%B4%E6%80%A7%E4%BA%8B%E5%8A%A1?spm=0.0.0.0.66YWQS)缺失。

**Comment by longdafeng** [comment]
@noprom 

谢谢， 第一个已经修复了， 第二个链接已经失效了，因此删除掉

**Comment by noprom** [comment]
谢谢修改。
