### ISSUE TITLE
提交Topology提示找不到java.library.path

### ISSUE THREAD

**Issue by noprom** [alibaba/jstorm#276]
使用
`
jstorm jar ./preliminary.demo-1.0-SNAPSHOT.jar com.alibaba.middleware.race.jstorm.RaceTopology
`
提交Topology,提示

`
Could not determine current working directory.
`
以下是完整的错误信息：
`
jstorm jar ./preliminary.demo-1.0-SNAPSHOT.jar com.alibaba.middleware.race.jstorm.RaceTopology
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java
Failed to get config java.library.path
None
Error occurred during initialization of VM
java.lang.Error: Properties init: Could not determine current working directory.
        at java.lang.System.initProperties(Native Method)
        at java.lang.System.initializeSystemClass(System.java:1119)
`
cannot concatenate 'str' and 'NoneType' objects
`
Syntax: [jstorm jar topology-jar-path class ...]

    Runs the main method of class with the specified arguments. 
    The jstorm jars and configs in $JSTORM_CONF_DIR/storm.yaml are put on the classpath. 
    The process is configured so that StormSubmitter 
    (https://github.com/alibaba/jstorm/wiki/JStorm-Chinese-Documentation)
    will upload the jar at topology-jar-path when the topology is submitted.

但是我在jstorm配置文件storm.yaml里面已经配置了:
`
java.library.path: "/usr/local/lib:/opt/local/lib:/usr/lib"
`

**Comment by noprom** [comment]
以解决。

**Comment by mrgiser** [comment]
@noprom 我也碰到了这个问题，请问你是怎么解决的？谢谢

**Comment by stoneluo** [comment]
@noprom  同问，怎么解决的

**Comment by noprom** [comment]
我记得当时是重新在家目录创建.jstorm文件夹

**Comment by stoneluo** [comment]
@noprom   是什么原因导致呢？

**Comment by mrgiser** [comment]
@stoneluo 不知道是不是同样的问题，我当时是这么解决的
http://he-zhao.cn/2017/11/29/JStorm%E8%BF%90%E8%A1%8C%E4%BE%9D%E8%B5%96storm-core%E7%9A%84%E4%BB%BB%E5%8A%A1%EF%BC%9A%E4%BE%9D%E8%B5%96%E5%86%B2%E7%AA%81%E4%B8%8E%E8%A7%A3%E5%86%B3/

https://www.jianshu.com/p/91cc84259be1

**Comment by mrgiser** [comment]
@stoneluo  集群模式，解决方法1那部分

**Comment by stoneluo** [comment]
@mrgiser   按照你的方式弄了，还是不行，
`                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>1.7.1</version>
                    <executions>
                        <execution>
                            <phase>package</phase>
                            <goals>
                                <goal>shade</goal>
                            </goals>
                            <configuration>
                                <transformers>
                                    <transformer
                                            implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                        <resource>META-INF/spring.handlers</resource>
                                    </transformer>
                                    <transformer
                                            implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                        <resource>META-INF/spring.schemas</resource>
                                    </transformer>
                                    <transformer
                                            implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                        <mainClass>com.sm.charge.jstorm.TransactionChargeTopology
                                        </mainClass>
                                    </transformer>
                                </transformers>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>`
插件应该没问题，也将jstorm包的<scope>provided</scope>打开了

**Comment by stoneluo** [comment]
@mrgiser   搞定了，是因为代码的Jstorm版本比环境的版本要高导致的

**Comment by mrgiser** [comment]
@stoneluo   哈哈，居然是这个原因，学习了
