### ISSUE TITLE
关于tuple的值的问题

### ISSUE THREAD

**Issue by 1647917675** [alibaba/jstorm#277]
我看了整个ack机制的实现，觉得ack机制追踪的是rootid 和tasklist所生成的uuid，进行的异或，和tuple的值没有太多的关系，感觉tuple的值是可以修改的，但是源码注释很多都是不可变的，想知道这是为什么

**Comment by unsleepy22** [comment]
ack本来就是跟tuple的值本身不相关的，不可变的原因是防止多线程同时修改一个tuple，或者说当一个tuple被处理完准备被序列化的时候又被改变，可能出现并发或者与预期结果不一致的问题。

**Comment by 1647917675** [comment]
谢了，了解 了
