### ISSUE TITLE
关于jstorm事务的一些想法

### ISSUE THREAD

**Issue by 1647917675** [alibaba/jstorm#280]
我这里有一点关于jstorm事务的一些想法，spout在发送给ack数据的时候是不是可以带上tasklist的id，之后bolt ack的时候将bolt的id发送给acker bolt 去维护整个 tasklist tree 维护tasklist 列表 ，当ack成功的时候remove  thetaskid，当失败的时候将tasklist 传送给spout 这样 得到了 失败的task的id，就可以直接 emit构建新的tuple树，（tuple的值不可变）。并且给每一个tuple 加上生命周期，超时的时候就不要去处理，这样不知道可不可行

**Comment by longdafeng** [comment]
jstorm 2.2.0 （已经release，但没有开源）， 已经做了exactly－once框架， 参考chandy－lamport算法
