### ISSUE TITLE
jstrom 中消息的速度匹配

### ISSUE THREAD

**Issue by iPoorGuy** [alibaba/jstorm#283]
找到一遍关于jstorm与storm比较的博客，有下面一句话：
“JStorm
底层RPC 采用netty + disruptor
保证发送速度和接受速度是匹配的”

就想问：jstorm"保证发送速度与接收速度匹配"是什么意思？
真的能做到速度匹配吗？

disruptor的处理机制是当ringbuf的空间不够时（也就是生产消息速度大于消费消息速度时），写入会出现先阻塞，待有空间在写。这是处理速度不匹配的机制。

那么，jstorm是做到了完全的生产消息与消费消息速度匹配？还是只是利用了这种机制来处理了速度不匹配的问题？

3Q！

**Comment by longdafeng** [comment]
这个是0.9.0 时候，做的反压1.0 
在2.1.1 的时候， 做的是反压 2.0

2.2.0 （已经release，但还没有开源）， 做的反压 3.0

你可以看看反压2.0 的文档 https://github.com/alibaba/jstorm/wiki/Backpressure
