### ISSUE TITLE
关于IFailValueSpout和IAckValueSpout

### ISSUE THREAD

**Issue by zzzvvvxxxd** [alibaba/jstorm#287]
对这两个，我的理解：
实现了这两种interface的Spout不会再使用原有的ack()和fail()
而是使用：

```
void fail(Object msgId, List<Object> values);
void ack(Object msgId, List<Object> values);
```

同时还会在本地Cache住之前发送过的tuple，除了替代原来自己管理tuple缓存的做法，这样理解对吗

ack后删除缓存的tuple吗？

**Comment by zzzvvvxxxd** [comment]
另外这种Spout会有oom的风险吗？

**Comment by longdafeng** [comment]
（1）不会有oom 风险， 因为storm底层也做了缓存， 只不过没有暴露这个接口给你
（2） 实现了这2个接口后， 老的接口ack／fail 就不会被调用
