### ISSUE TITLE
zookeeper集群不同端口问题

### ISSUE THREAD

**Issue by vv0885** [alibaba/jstorm#288]
配置如下：
 storm.zookeeper.servers:
    - "192.168.1.225"
    - "192.168.1.225"
    - "192.168.1.225"
 storm.zookeeper.ports:
    - 2181
    - 2182
    - 2183

但是发现UI界面cluster页上显示都是2181

在conf页面显示没问题

会影响使用吗？

**Comment by wuchong** [comment]
你这个配置集群能正常起来？ 

我记得 `storm.zookeeper.ports` 配置必须是 int，不能是List呀。

**Comment by longdafeng** [comment]
不可以不同端口， 必须相同端口
