### ISSUE TITLE
双网络环境下supervisor网络设置问题-jstorm-2.1.1

### ISSUE THREAD

**Issue by youngcle** [alibaba/jstorm#291]
我的机群中配置有两个网络，1个千兆，一个万兆，分别规划用来走数据和管理信息。
部署jstorm时，前期做开发和测试没有太注意。今天发现从jstorm list 和ui中看到的各个节点supervisor都显示的是千兆网的ip。配置文件中似乎没有地方专门写网络信息。
我将nimbus.host改为万兆网ip，zookeeper地址写为千兆网的地址,
jstorm 启动后依然list出来的supervisor全部都是千兆网地址。

后来我尝试将各个节点的Hostname改为/etc/hosts中万兆网的主机名(如：从workernode01改为workernode01-10g)。再list就ok了。

我不确定这算不算一个问题，提醒开发团队留意一下，至少可以在配置文件中做的更加清晰一些。

**Comment by longdafeng** [comment]
恩， 

这个问题， 在阿里云上出现过， 2张网卡， 一张对外，一张对内。

@youngcle  能不能帮我写一个wiki 来帮忙提示一下呢

**Comment by youngcle** [comment]
好的。我整理一下。

**Comment by youngcle** [comment]
@longdafeng 
我写了一个wiki，关于双网络（多网络）环境下jstorm的配置

地址如下：https://github.com/alibaba/jstorm/wiki/%E5%85%B3%E4%BA%8E%E5%8F%8C%E7%BD%91%E7%BB%9C%EF%BC%88%E5%A4%9A%E7%BD%91%E7%BB%9C%EF%BC%89%E7%8E%AF%E5%A2%83%E4%B8%8Bjstorm%E7%9A%84%E9%85%8D%E7%BD%AE

**Comment by unsleepy22** [comment]
thx
