### ISSUE TITLE
topology.enable.classloader问题

### ISSUE THREAD

**Issue by charlieyxl** [alibaba/jstorm#292]
topology.enable.classloader不打开，是不是不能加载我应用里引用的第三方jar包？
比如，默认不开启topology.enable.classloader，启动topology时会报错如下：
java.lang.NoClassDefFoundError: Could not initialize class org.I0Itec.zkclient.ZkClient
        at com.alibaba.dubbo.remoting.zookeeper.zkclient.ZkclientZookeeperClient.<init>(ZkclientZookeeperClient.java:25) ~[stormjar.jar:na]

打开topology.enable.classloader，发现这个问题就没有了，但是日志打印上又出现新的问题。能否再详细说明一下，如果想统一用logback打印自己写的topology里的日志，在jstorm2.1下要如何配置？

谢谢！

**Comment by longdafeng** [comment]
现在问题是：
你的zk client和jstorm client的版本发生冲突

解决办法：
（1）统一zk 的版本， 活着你应用的zk 版本使用jstorm的版本， 如果不可以，就把jstorm的安装目录里面 zk的版本换成你应用zk的版本即可， 最后关掉classloader
（2） 或者等到jstorm 2.2.0 对外开源， 2.2.0 已经解决所有类冲突问题

**Comment by charlieyxl** [comment]
那请问2.2.0计划什么时候开源？

**Comment by unsleepy22** [comment]
2.2.1已经release了
