### ISSUE TITLE
Jstorm 启动后，集群只显示一台机器，为何ip一直是127.0.1.1

### ISSUE THREAD

**Issue by ZongWenlong** [alibaba/jstorm#293]
Jstorm启动后：
![2](https://cloud.githubusercontent.com/assets/8022060/16361385/a4ab8b62-3bc1-11e6-8cb7-ca1ae8140f43.PNG)
三个机器，为啥一直只有一个，而且是127.0.1.1
用jstorm list结果如下：
![3](https://cloud.githubusercontent.com/assets/8022060/16361393/dde06916-3bc1-11e6-9b9f-f476598a8028.PNG)

 我的jstorm，配置如下
![1](https://cloud.githubusercontent.com/assets/8022060/16361394/e2ff5bbe-3bc1-11e6-93e4-942f22f6e390.PNG)

**Comment by longdafeng** [comment]
你的jstorm获取不到本地ip 导致的， 你执行


hostname -i
能够获取到非 127.0.0.1 就可以了


你可以修改/etc/hosts或者设置网卡hostname达到这个效果

**Comment by ZongWenlong** [comment]
@longdafeng 修改了host就好了，多谢~
