### ISSUE TITLE
Topology的日志在哪里呢

### ISSUE THREAD

**Issue by dongeforever** [alibaba/jstorm#297]
我提交了一个topology，在web界面看运行正常，可我在程序中打印的日志全部没有显示出来。

topology名字是：WordCountTest2
在jstorm安装目录下:
有logs/WordCountTest2这个文件夹，但是里面的日志文件并没有打印我的程序日志

**Comment by wuchong** [comment]
你是用什么方式打印日志的呢？ 代码贴一下

建议用 slf4j 的接口打印

**Comment by dongeforever** [comment]
@wuchong 是用slf4j 的接口打印的，日志应该没有问题；
后来发现是worker没启动成功, 这个问题纠结了我两个小时了,supervise的日志一直在重启worker，但是worker本身却没有错误日志。我把启动worker的命令单独拿出来运行，
java  -Xms256m -Xmx256m   -Djstorm.log.dir=/export/server/jstorm/jstorm-2.1.1/logs -Dlogfile.name=WordCountTest2-worker-6800.log -Dtopology.name=WordCountTest2 -Dlogback.configurationFile=/export/server/jstorm/jstorm-2.1.1/conf/jstorm.logback.xml -cp /export/server/jstorm/jstorm-2.1.1/lib/logback-classic-1.0.13.jar:/export/server/jstorm/jstorm-2.1.1/lib/json-simple-1.1.jar:/export/server/jstorm/jstorm-2.1.1/lib/asm-4.0.jar:/export/server/jstorm/jstorm-2.1.1/lib/metrics-healthchecks-3.1.2.jar:/export/server/jstorm/jstorm-2.1.1/lib/rocksdbjni-3.10.1.jar:/export/server/jstorm/jstorm-2.1.1/lib/commons-logging-1.1.3.jar:/export/server/jstorm/jstorm-2.1.1/lib/commons-io-2.4.jar:/export/server/jstorm/jstorm-2.1.1/lib/commons-lang-2.5.jar:/export/server/jstorm/jstorm-2.1.1/lib/slf4j-api-1.7.5.jar:/export/server/jstorm/jstorm-2.1.1/lib/kryo-2.21.jar:/export/server/jstorm/jstorm-2.1.1/lib/httpclient-4.3.3.jar:/export/server/jstorm/jstorm-2.1.1/lib/zookeeper-3.4.6.jar:/export/server/jstorm/jstorm-2.1.1/lib/objenesis-1.2.jar:/export/server/jstorm/jstorm-2.1.1/lib/chill-java-0.3.5.jar:/export/server/jstorm/jstorm-2.1.1/lib/jgrapht-core-0.9.0.jar:/export/server/jstorm/jstorm-2.1.1/lib/reflectasm-1.07-shaded.jar:/export/server/jstorm/jstorm-2.1.1/lib/metrics-core-3.1.2.jar:/export/server/jstorm/jstorm-2.1.1/lib/httpcore-4.3.2.jar:/export/server/jstorm/jstorm-2.1.1/lib/disruptor-3.3.2.jar:/export/server/jstorm/jstorm-2.1.1/lib/netty-3.9.0.Final.jar:/export/server/jstorm/jstorm-2.1.1/lib/snakeyaml-1.11.jar:/export/server/jstorm/jstorm-2.1.1/lib/log4j-over-slf4j-1.6.6.jar:/export/server/jstorm/jstorm-2.1.1/lib/clojure-1.6.0.jar:/export/server/jstorm/jstorm-2.1.1/lib/commons-cli-1.2.jar:/export/server/jstorm/jstorm-2.1.1/lib/curator-client-2.5.0.jar:/export/server/jstorm/jstorm-2.1.1/lib/commons-codec-1.6.jar:/export/server/jstorm/jstorm-2.1.1/lib/jline-0.9.94.jar:/export/server/jstorm/jstorm-2.1.1/conf:/export/server/jstorm/jstorm-2.1.1/lib/carbonite-1.4.0.jar:/export/server/jstorm/jstorm-2.1.1/lib/servlet-api-2.5.jar:/export/server/jstorm/jstorm-2.1.1/jstorm-core-2.1.1.jar:/export/server/jstorm/jstorm-2.1.1/lib/libthrift-0.9.2.jar:/export/server/jstorm/jstorm-2.1.1/lib/logback-core-1.0.13.jar:/export/server/jstorm/jstorm-2.1.1/lib/metrics-jvm-3.1.2.jar:/export/server/jstorm/jstorm-2.1.1/lib/guava-16.0.1.jar:/export/server/jstorm/jstorm-2.1.1/lib/curator-framework-2.5.0.jar:/export/server/jstorm/jstorm-2.1.1/lib/gson-2.3.1.jar:/export/server/jstorm/jstorm-2.1.1/lib/commons-exec-1.1.jar::/export/server/jstorm/jstorm-2.1.1/data/supervisor/stormdist/WordCountTest2-1-1467206947/stormjar.jar com.alibaba.jstorm.utils.ProcessLauncher  java -server  -Xms300483648 -Xmx300483648  -Xmn150241824  -XX:PermSize=18780228 -XX:MaxPermSize=18780228 -XX:ParallelGCThreads=4   -XX:SurvivorRatio=4 -XX:+UseConcMarkSweepGC  -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:CMSFullGCsBeforeCompaction=5 -XX:+HeapDumpOnOutOfMemoryError -XX:+UseCMSCompactAtFullCollection -XX:CMSMaxAbortablePrecleanTime=5000  -Xloggc:/export/server/jstorm/jstorm-2.1.1/logs/WordCountTest2/WordCountTest2-worker-6800-gc.log -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:HeapDumpPath=/export/server/jstorm/jstorm-2.1.1/logs/WordCountTest2/java-WordCountTest2-1-1467206947-20160629215208.hprof  -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Djstorm.home=/export/server/jstorm/jstorm-2.1.1 -Djstorm.log.dir=/export/server/jstorm/jstorm-2.1.1/logs -Dlogfile.name=WordCountTest2-worker-6800.log -Dtopology.name=WordCountTest2 -Dlogback.configurationFile=/export/server/jstorm/jstorm-2.1.1/conf/jstorm.logback.xml -cp /export/server/jstorm/jstorm-2.1.1/lib/logback-classic-1.0.13.jar:/export/server/jstorm/jstorm-2.1.1/lib/json-simple-1.1.jar:/export/server/jstorm/jstorm-2.1.1/lib/asm-4.0.jar:/export/server/jstorm/jstorm-2.1.1/lib/metrics-healthchecks-3.1.2.jar:/export/server/jstorm/jstorm-2.1.1/lib/rocksdbjni-3.10.1.jar:/export/server/jstorm/jstorm-2.1.1/lib/commons-logging-1.1.3.jar:/export/server/jstorm/jstorm-2.1.1/lib/commons-io-2.4.jar:/export/server/jstorm/jstorm-2.1.1/lib/commons-lang-2.5.jar:/export/server/jstorm/jstorm-2.1.1/lib/slf4j-api-1.7.5.jar:/export/server/jstorm/jstorm-2.1.1/lib/kryo-2.21.jar:/export/server/jstorm/jstorm-2.1.1/lib/httpclient-4.3.3.jar:/export/server/jstorm/jstorm-2.1.1/lib/zookeeper-3.4.6.jar:/export/server/jstorm/jstorm-2.1.1/lib/objenesis-1.2.jar:/export/server/jstorm/jstorm-2.1.1/lib/chill-java-0.3.5.jar:/export/server/jstorm/jstorm-2.1.1/lib/jgrapht-core-0.9.0.jar:/export/server/jstorm/jstorm-2.1.1/lib/reflectasm-1.07-shaded.jar:/export/server/jstorm/jstorm-2.1.1/lib/metrics-core-3.1.2.jar:/export/server/jstorm/jstorm-2.1.1/lib/httpcore-4.3.2.jar:/export/server/jstorm/jstorm-2.1.1/lib/disruptor-3.3.2.jar:/export/server/jstorm/jstorm-2.1.1/lib/netty-3.9.0.Final.jar:/export/server/jstorm/jstorm-2.1.1/lib/snakeyaml-1.11.jar:/export/server/jstorm/jstorm-2.1.1/lib/log4j-over-slf4j-1.6.6.jar:/export/server/jstorm/jstorm-2.1.1/lib/clojure-1.6.0.jar:/export/server/jstorm/jstorm-2.1.1/lib/commons-cli-1.2.jar:/export/server/jstorm/jstorm-2.1.1/lib/curator-client-2.5.0.jar:/export/server/jstorm/jstorm-2.1.1/lib/commons-codec-1.6.jar:/export/server/jstorm/jstorm-2.1.1/lib/jline-0.9.94.jar:/export/server/jstorm/jstorm-2.1.1/conf:/export/server/jstorm/jstorm-2.1.1/lib/carbonite-1.4.0.jar:/export/server/jstorm/jstorm-2.1.1/lib/servlet-api-2.5.jar:/export/server/jstorm/jstorm-2.1.1/jstorm-core-2.1.1.jar:/export/server/jstorm/jstorm-2.1.1/lib/libthrift-0.9.2.jar:/export/server/jstorm/jstorm-2.1.1/lib/logback-core-1.0.13.jar:/export/server/jstorm/jstorm-2.1.1/lib/metrics-jvm-3.1.2.jar:/export/server/jstorm/jstorm-2.1.1/lib/guava-16.0.1.jar:/export/server/jstorm/jstorm-2.1.1/lib/curator-framework-2.5.0.jar:/export/server/jstorm/jstorm-2.1.1/lib/gson-2.3.1.jar:/export/server/jstorm/jstorm-2.1.1/lib/commons-exec-1.1.jar::/export/server/jstorm/jstorm-2.1.1/data/supervisor/stormdist/WordCountTest2-1-1467206947/stormjar.jar com.alibaba.jstorm.daemon.worker.Worker WordCountTest2-1-1467206947 2cd581d1-dea7-4f67-b381-1bb1304d6f79 6800 393ae922-4e45-4bd7-91d5-8bcb1edcf7fb /export/server/jstorm/jstorm-2.1.1/data/supervisor/stormdist/WordCountTest2-1-1467206947/stormjar.jar

Begin to exit:255

这个错误来自于src/main/java/com/alibaba/jstorm/utils/ProcessLauncher.java

但是要怎么解呢

我的机器是ubuntu 64位   jdk7 64位

**Comment by dongeforever** [comment]
jdk改成 java version "1.8.0_91"之后，可以正常启动。
原先的jdk版本是java version "1.7.0_55"
