### ISSUE TITLE
MetricsConsumer在jstorm最新版里可以用吗？

### ISSUE THREAD

**Issue by lcy362** [alibaba/jstorm#301]
我按着storm给的文档，注册了一个MetricConsumer
`conf.registerMetricsConsumer(MetricConsumerTest.class, 1);`
功能只是打日志，
`    @Override
    public void handleDataPoints(TaskInfo taskInfo, Collection<DataPoint> dataPoints) {
        for (DataPoint p : dataPoints) {
            logger.info("testoutmetrics: " + p.name + " " + p.value);
        }
    }`
但是发现没有效果。可能是什么原因呢？

**Comment by unsleepy22** [comment]
不行，你可以实现MetricUploader接口，来达到发送metrics数据的目的。

**Comment by lcy362** [comment]
@unsleepy22  请问MetricUploader有使用说明吗?
我写了这么一个类：
public class MetricUploaderTest extends DefaultMetricUploader {
    private final Logger logger = Logger.getLogger(getClass());
    @Override
    public boolean upload(String clusterName, String topologyId, Object key, Map<String, Object> metricContext) {
        logger.info("topometrics: " + metricContext);
        return true;
    }
}

然后再storm.yaml里配上nimbus.metric.uploader.class: ......MetricUploaderTest

现在只在nimbus.log里找到了topometrics这行日志，supervisor和worker的日志里都没有，是不是需要别的配置？
而且打出的日志信息也很少：
[INFO 2016-07-13 17:54:00 c.s.MetricUploaderTest:17 main-upload-control-thread] topometrics: {metric.timestamp=1468403640121, metric.type=TASK}
[INFO 2016-07-13 17:54:00 c.s.MetricUploaderTest:17 main-upload-control-thread] topometrics: {metric.timestamp=1468403640224, metric.type=TASK}
[INFO 2016-07-13 17:54:00 c.s.MetricUploaderTest:17 main-upload-control-thread] topometrics: {metric.timestamp=1468403640252, metric.type=TP}
[INFO 2016-07-13 17:54:02 c.s.MetricUploaderTest:17 main-upload-control-thread] topometrics: {metric.timestamp=1468403642825, metric.type=ALL}
[INFO 2016-07-13 17:54:36 c.s.MetricUploaderTest:17 main-upload-control-thread] topometrics: {metric.timestamp=1468403676510, metric.type=ALL}
怎么得到详细的metric数据呢？

**Comment by unsleepy22** [comment]
它是通过你自定义的metric uploader来实现向外部发送metrics数据。看一下TopologyMetricsRunnable类的run方法，它会发送各种不同的数据。但是具体如何发送到外部存储，存储的schema，都是需要你自己来定义的。

**Comment by lcy362** [comment]
@unsleepy22 
不知道我理解的对不对，是说通过metricUploader.sendEvent() 这个方法来实现输出metics数据吗？
但是还有问题，在这一块代码里,
                    if (event instanceof Remove) {
                        handleRemoveEvent((Remove) event);
                    } else if (event instanceof Update) {
                        handleUpdateEvent((Update) event);
                    } else if (event instanceof Refresh) {
                        handleRefreshEvent((Refresh) event);
                    } else if (event instanceof KillTopologyEvent) {
                        handleKillTopologyEvent((KillTopologyEvent) event);
                    } else if (event instanceof StartTopologyEvent) {
                        handleStartTopologyEvent((StartTopologyEvent) event);
                    } else if (event instanceof TaskDeadEvent) {
                        handleTaskDeadEvent((TaskDeadEvent) event);
                    } else if (event instanceof TaskStartEvent) {
                        handleTaskStartEvent((TaskStartEvent) event);
                    } 
只有Start/kill Topology/task 这几个event的处理中调了metricUploader.sendEvent()。
topology的监控信息，就是tps,延时这些，是在Update这个event里吗？但是handleUpdateEvent((Update) event) 里没有调过sendEvent()方法，或者metricUploader的其他方法，应该怎么把各个topology的信息输出出来呢？

**Comment by unsleepy22** [comment]
代码里，对于非metrics的event，比如StartTopologyEvent, KillTopologyEvent，都会发送给metricUploader，具体就看metricUploader如何使用。

metric data是先放在metric cache里，其实就是本地的rocksdb中，具体怎么用还是看你metric uploader的。可以从rocksdb中把数据读出来，写到其他地方，最后从rocksdb中删除数据。

大致就是这样的思路。获取metric data、删除metric data的具体代码你可以仔细看一下这个类。

**Comment by lcy362** [comment]
懂了。我再看看。谢谢
