### ISSUE TITLE
自定义统计指标无效

### ISSUE THREAD

**Issue by gavincook** [alibaba/jstorm#308]
现在使用了storm-kafka组件，其中有很多统计指标，但是无法将其显示到jstorm-ui上，也不能在日志中输出。
当使用如下代码进行注册时：

```
conf.registerMetricsConsumer(LoggingMetricsConsumer.class);
```

LoggingMetricsConsumer类的构造方法一直都没有被调用过。

**Comment by unsleepy22** [comment]
2.1.0里重构了metrics，storm-kafka里的metrics，用的是老的metrics系统，所以无法跟jstorm的metrics数据对接在一起。。。

**Comment by Ruguo** [comment]
使用storm-kafka时，在KafkaSpout中使用MetricClient注册了一个Count metric，用来采集kafka积压量，最后在JStorm UI也显示上这个metric，但类型却是Histogram，不知是怎么回事？(自定义metric参考的：http://www.jstorm.io/Maintenance_cn/JStormMetrics.html)
