### ISSUE TITLE
很抱歉又是 jstorm 的 log 问题

### ISSUE THREAD

**Issue by Allianzcortex** [alibaba/jstorm#312]
很抱歉但又是 jstorm 打 log 的问题：
1. 已经把网上能找到的资料和相关的 issue 都看了，却仍然是没有办法。
2. 我不知道我的理解是否正确：
   ① 尽量用 slf4j，相比较于 log4j,它避免了 additional setup to do on each node in the cluster
   参考　[链接](http://stackoverflow.com/questions/25679963/how-to-write-logs-to-a-file-using-log4j-and-storm-framework)
   ② 相关的 log 会自动在 ｀%{jstorm_log_dic}｀ 目录下创建以 topology-name 命名的文件夹。
   ③ 使用时只要定义好 ｀private static final Logger LOGGER=LoggerFactory.getLogger(some.class)｀ 后就可以用
   ｀LOGGER.info(),LOGGER.debug()｀ 等方法来更新。参考：[getting-started-with-storm-logging](http://kitmenke.com/blog/2015/06/22/getting-started-with-storm-logging/)
3. 我的 jstorm 版本是 2.1.0,在 local-mode 和 cluster 上都可以运行成功，但就是无法找到 log 文件。
   具体的代码我上传在：https://github.com/Allianzcortex/jstorm-word-count-demo   ，就是一个简单的 word-count 的 demo。
   我需要在 maven 配置里再添加什么吗？
   或者至少像 worker-id 这样的文件夹也应该生成啊。。。?怎么样配置比较合适呢？

**Comment by unsleepy22** [comment]
理论上你的代码只需要依赖slf4j-api即可，因为slf4j-api和logback在jstorm的lib里都是有的。
但是需要注意，一定要排除掉slf4j-log4j12，因为jstorm2.1.0开始是带了log4j-over-slf4j，这两个是冲突的。

这些如果都没问题，你可以看下cluster中，你的worker进程，通常来说，会有一个-Dlogback.configurationFile参数，你看一下参数对应的logback配置，这是集群的logback配置，通常会指向${jstorm_home}/conf/jstorm.logback.xml。

**Comment by Longda-Feng** [comment]
https://github.com/alibaba/jstorm/wiki/user_define_log_cn

这篇文章， 你看过吗？？

另外， 你的依赖里面排除掉slf4j-log4j12

**Comment by CQbaron** [comment]
我想问下，如何配置每个应用的自定义日志输出？

**Comment by hatface** [comment]
没说明白啊，到底是依赖slf4j还是log4j呢
