### ISSUE TITLE
jStorm Topo资源使用问题

### ISSUE THREAD

**Issue by Fengdada** [alibaba/jstorm#314]
场景：JStorm上的业务，在运行期会进行扩容，扩容时涉及到资源的弹性和TOPO的修改（主要是Worker/Task或spout/bolt个数的修改）。
   我们的Jstorm集群部署在容器内，所以硬件资源的伸缩，可以通过k8s自动弹性来解决，但是TOPO必须停下来才能进行修改，业务需要下线。
   问题：扩容时不期望影响现有业务，如何修改TOPO？
   可能的方案：提交TOPO时，按照最大规模的Worker/Task数量来提交，但是按实际规模来分配硬件资源，随着supervisor的自动弹出，JStorm在不修改TOPO的情况下会进行负荷均衡，把Worker/Task逐渐分配到新的supervisor上，这种方式是否可以？有什么缺点？
一个相关的问题：supervisor注册到集群后，为什么JStorm不会自动的进行负荷均衡？而需要手动运行负荷均衡的命令。

**Comment by unsleepy22** [comment]
jstorm是支持动态修改并发度的, rebalance可以做到这点。所以只要nimbus能够感知到新注册的supervisor，理论上就可以用rebalance来做，而不是像你现在这样，将supervisor杀死，由调度来做。

不自动进行负载均衡，是基于稳定的目的。线上的任务，稳定是第一位的。

**Comment by Longda-Feng** [comment]
你们jstorm是跑在docker 上的？ 当你们docker 缩容时， 你的意思是，你应用必须先停下来，然后docker缩容， 再启动 你应用吗？


实际上，不需要这样做：
docker的伸缩容都可以和jstorm独立开来。

当docker扩容时， 你调用restart／rebalance 命令对你应用进行增加并发，就使用上你的新增的docker

当docker缩容时， supervisor 死去，上面的任务会自动迁移到到活着的docker上，前提条件是docker的资源够
