### ISSUE TITLE
Nimbus JVM out of memory

### ISSUE THREAD

**Issue by jyxlcd** [alibaba/jstorm#319]
因为要在一个资源有限的环境下跑JStorm，我把Nimbus的虚拟机的内存调整到1GB。启动Nimbus时，Java报错JVM内存不够，需要分配1.5GB内存。

我于是再把Nimbus的虚拟机的内存调整到2.5GB。初次启动Nimbus成功。关掉cluster重启后，Java再次报错JVM内存不够，这次它需要分配2.5GB内存了。

查阅JStorm文档发现，0.9.7版本时，Nimbus的JVM默认大小已被设为4GB。我在conf/storm.yaml里也没有看到可以设定Nimbus占用JVM内存大小的选项。因此，我对Nimbus的JVM的内存大小如何设定，上述的1.5GB和2.5GB请求是怎么来的不太明白。请指教！

**Comment by 1647917675** [comment]
nimbus.childopts nimbus进程的jvm参数

**Comment by jyxlcd** [comment]
谢谢！！
