### ISSUE TITLE
请教如何怎么分配Topology到特定的worker 上

### ISSUE THREAD

**Issue by caiyifeng** [alibaba/jstorm#324]
嗨 @Longda-Feng 请教问题，如何怎么分配worker 到特定的机器，甚至把Topology分配到指定的worker 上！！！多谢

**Comment by hustfxj** [comment]
你参考下自定义调度，jstorm支持自定义调度

**Comment by hustfxj** [comment]
https://github.com/alibaba/jstorm/blob/master/example/sequence-split-merge/src/main/java/com/alipay/dw/jstorm/example/sequence/SequenceTopologyUserDefine.java

**Comment by caiyifeng** [comment]
多谢 @hustfxj
