### ISSUE TITLE
jstorm-2.1.0 触发反压限流一段时间后，下游task已经完全空闲但没有自动解除限流

### ISSUE THREAD

**Issue by meta-life** [alibaba/jstorm#325]
拓扑触发反压限流后，下游task已经完全空闲但没有自动解除限流，请问是什么原因？该怎么解决？
软件版本：jstorm-2.1.0
@Longda-Feng

**Comment by 1647917675** [comment]
jstorm的反压无论是限流还是解除限流都会取样的，取样的次数好像没有提供配置的参数，建议你去触发限流的参数

**Comment by Longda-Feng** [comment]
在配置文件中配置
```
topology.backpressure.enable: false
```
就可以彻底关掉反压了， 重启jstorm集群


如果想要动态关闭反压， 就是对一个正在运行的程序进行操作
jstorm update_topology topologyName -conf configFile

其中configfile 是包含“topology.backpressure.enable: false” 的yaml 配置文件

**Comment by meta-life** [comment]
在spout中使用了有界的BlockingQueue，nextTuple中take()取数据，从日志发现当BlockingQueue满了以后，就无法正常解除反压。设置topology.max.spout.pending后再没发现此问题。

**Comment by unsleepy22** [comment]
2.2.1已经优化了backpressure，应该不会再出现这个问题了
