### ISSUE TITLE
JSTORM安装--烦请在JStorm安装步骤中增加NimbusHA部署步骤说明

### ISSUE THREAD

**Issue by kwengelie** [alibaba/jstorm#326]
根据网络上JSTORM和STORM1.0之前的版本比较，JSTORM增加了NimbusHA，如下：
Nimbus HA
JStorm: stable, running more than 2 years
Storm: hasn't been released, no online test.
Suggestion: using JStorm's HA solution

但是在查阅了很多JSTORM安装资料之后，从未见到过NimbusHA部署的步骤说明。请问官方是否可以提供下JSTORM的Nimbus HA部署说明。谢谢！

**Comment by Longda-Feng** [comment]
随便找一台机器启动nimbus， 就可以了， 就自动HA 了

**Comment by kwengelie** [comment]
@Longda-Feng 非常感谢。

请问配置文件中的nimbus host配置项，是否需要配置两台HA机器的IP信息？

**Comment by Longda-Feng** [comment]
nimbus host 配置项， 只是方便脚本 $jstorm_home/bin/start.sh 使用的， 你如果不用这个脚本，就无所谓了

你如果用这个脚本，就配置起来， 

不过，一般建议配置，这样，可以提醒自己 集群里面哪些机器启动了nimbus
