### ISSUE TITLE
trident使用TransactionalTridentKafkaSpout遇到的问题！求帮助

### ISSUE THREAD

**Issue by caiyifeng** [alibaba/jstorm#329]
嗨，求救：
我按照实例，写了个trident应用，但就是无法从kafka拿到信息，求指教
我用的是jstorm2.1.1 ,storm-kafka0.9.6

**Comment by Longda-Feng** [comment]
你这样没有详细信息和报错信息，我无法回答啊

**Comment by caiyifeng** [comment]
不好意思，确实信息量少了点，@longda-Feng 我找到问题了！多谢了啊
