### ISSUE TITLE
Dcoker中部署Jstorm，supervisor可用端口数量变为0

### ISSUE THREAD

**Issue by AlphaGoCome** [alibaba/jstorm#330]
nimbus和supervisor分别在不同的容器中部署，启动nimbus后，再启动supervisor成功，“jstorm list”命令查看supervisor容器，显示可用端口为5个：
![image](https://cloud.githubusercontent.com/assets/20814576/17883532/af4db804-6945-11e6-934d-c05531a7b3a9.png)
此时不提交topo任务，经过60秒左右之后，再用“jstorm list”命令查看supervisor容器，显示可用端口为0，导致此后无法提交topo任务。请大师给看看，谢谢！
![image](https://cloud.githubusercontent.com/assets/20814576/17883555/d240769e-6945-11e6-92aa-01b764b85509.png)

**Comment by Longda-Feng** [comment]
jstorm 有自动探测机器资源的配置， 探测cpu load 和内存和磁盘空间， 估计你这里面有一项是不行的， 你关掉自动探测吧

```
supervisor.enable.check: false
supervisor.slots.ports:
    - 6800
    - 6801
    - 6802
    - 6803
```

**Comment by AlphaGoCome** [comment]
还是不行，在storm.yaml文件中添加了上述配置项，仍旧在60s后端口被清0，supervisor检查的配置项本来默认就是关闭的。
![image](https://cloud.githubusercontent.com/assets/20814576/17916674/097ea0b6-69e8-11e6-9293-47b174e0c6f0.png)

**Comment by Longda-Feng** [comment]
改配置后，你重启了supervisor吗？

**Comment by hustfxj** [comment]
@AlphaGoCome  应该是设置这个配置项 supervisor.enable.auto.adjust.slots：false，你试一下

**Comment by AlphaGoCome** [comment]
@Longda-Feng 我们都是修改后重新启动的
@hustfxj  这个配置项也不对，我们在storm.yaml中加了，启动后还是一样，60s后端口被回收。

**Comment by hustfxj** [comment]
你代码是2.1.1最新的代码吗？ 这个地方我们在今年3月份fix的，应该没问题的。你可以我们代码里头这个函数  calculatorAvailablePorts

**Comment by AlphaGoCome** [comment]
@hustfxj  是的，我们下的就是最新的2.1.1版本。在docker中部署，现在的情况是，启动时可以查看到4个端口，但60s后，有时会保留一个端口，有时端口都会被回收。感觉还是会根据资源来计算。

**Comment by AlphaGoCome** [comment]
@Longda-Feng @hustfxj  我们切换了镜像，从ubuntu + jdk 切换为alpine + openjdk镜像，同样的jstorm2.1.1， 启动后，端口再也不会被回收了。
