### ISSUE TITLE
“0.9.0 性能测试“一页中，测试样例无法下载

### ISSUE THREAD

**Issue by jyxlcd** [alibaba/jstorm#333]
页面：https://github.com/alibaba/jstorm/wiki/0.9.0-%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95

测试样例下载链接：https://github.com/longdafeng/storm-examples

无法下载，而且页面上有图片无法显示

**Comment by hustfxj** [comment]
这个很老了，你直接下载jstorm代码，里头有example
