### ISSUE TITLE
log4j配置问题

### ISSUE THREAD

**Issue by penuel-leo** [alibaba/jstorm#337]
使用`ConfigExtension.setUserDefinedLog4jConf(config,"log4j_custom.xml");`添加自定义log4j文件；
提交topo ok，但是找不到log在哪？
其中log4j_custom.xml内容:

    <appender name="log_file" class="org.apache.log4j.DailyRollingFileAppender">
		<param name="File" value="${jstorm.log.dir}/${topology.name}/${topology.name}.log"/>
		<layout class="org.apache.log4j.PatternLayout">
			<param name="ConversionPattern" value="%d %-5p (%F:%L) - %m%n"/>
		</layout>
    </appender>
    <root>
		<priority value="WARN"/>
		<appender-ref ref="console"/>
		<appender-ref ref="log_file"/>
    </root>

其中Worker启动后的参数:
    `Worker -Xms1073741824 -Xmx1073741824 -Dlog.home=/dianyi/app/logs ... -Dtopology.name=XXX_TOPO -Dlogback.configurationFile=/home/jstorm-  2.1.1/conf/jstorm.logback.xml -Dlog4j.configuration=log4j_eagle.xml`

另外：在jstorm-ui上面，能从Topology->Task Stats->Error上面看到错误日志，但是点击view log后提示./XXX_TOPO/XXX_TOPO-worker-6804.log(不是我log4j配置的文件名)不存在.

**Comment by penuel-leo** [comment]
调整了mvn的log4j依赖，可以看到了；
仅使用了"slf4j-api","slf4j-log4j12","log4j"可以了；

单独问下，jstorm-ui viewlog的位置在哪配置，让jstorm ui能找到正确的log文件；
还有${jstorm.log.dir},${topology.name},${topology.name}这三者环境变量在何处设置的？

**Comment by Longda-Feng** [comment]
${jstorm.log.dir}  这个变量可以在配置文件中进行配置， 如果没有配置，则是${jstorm.home}/logs
${topology.name}  就是 topology的名字
${logfile.name} 就是日志的名字， 比如topology-id-worker-6800.log

jstorm-ui 的日志是在tomcat里面

如果想要ui上能看到任务的日志， 你只需要 保证 supervisor启动的时候和worker启动的时候 2个 ${jstorm.log.dir} 是一样的， 也就是说，他们的日志都放在 ${jstorm.log.dir}

如果你在ui上看不到日志， 说明，他们的日志不是在一块， 一种常见的原因是， 启动supervisor后， 修改了配置文件，导致 2者不在一起， 
解决办法： 重启一下supervisor 即可， supervisor会重新读取logback 配置文件，从而2者日志都在相同目录下
