### ISSUE TITLE
怎么平滑下架Supervisor

### ISSUE THREAD

**Issue by ky1987** [alibaba/jstorm#338]
请教个问题，现在要下架集群中的一个Supervisor，怎么操作才能平滑迁走Topology？谢谢

**Comment by Longda-Feng** [comment]
其实，我们这边从来不会平滑下架supervisor， 都是暴力下降， 直接"pkill -9 java"或者直接重启机器

当supervisor 杀死后， 他上面的worker会自动迁移到其他机器上

topology会抖动大概2分钟，2分钟后，稍微观察一下， 如果应用恢复了，就ok， 没有恢复，就重启一下应用

jstorm restart xxxx
