### ISSUE TITLE
jstorm  能否把系统日志和业务日志分开

### ISSUE THREAD

**Issue by hubuyt** [alibaba/jstorm#339]
现在看了storm作业的日志 发现和storm的日志混在一起了大量的系统日志遮盖了业务日志，请问能否把业务日志单独拿出来，以便好分析业务

**Comment by penuel-leo** [comment]
使用`ConfigExtension.setUserDefinedLog4jConf(config, "log4j_custom.xml");`
或者配置`user.defined.log4j.conf`参数；
就可以使用自定义log4j进行区分日志了
