### ISSUE TITLE
连nimbus.log都没有生成,什么原因？

### ISSUE THREAD

**Issue by woderia** [alibaba/jstorm#340]
运行storm list提示nimbus is not alive，到日志目录查看没有nimbus.log,只有nimbus-gc-14******.log.o.current
版本2.1.1 检测zk正常 supervisor.log正常生成,求大神指导,能到哪里查看错误？

**Comment by woderia** [comment]
nimbus.childopts: "-Xmx256m"  
 supervisor.childopts: "-Xmx256m"  
 worker.childopts: "-Xmx128m" 
加了这几个参数后就可以了,十分困惑原因,希望有人能帮忙解答

**Comment by Longda-Feng** [comment]
你应该是在自己的笔记本上运行， 明显，你把进程的所有内存调小了，这说明默认的参数是需要4g/1g/2g 内存（默认参数是在服务器上运行的），在你的机器上无法创建这么大的jvm

你虽然把内存调小，可以把nimbus／supervisor／worker 跑起来，但基本干不了什么事情， 你唯一的办法是加大内存， 三个内存调到1g/512m/1g，  你才能运行正常

**Comment by longdafeng** [comment]
ni
