### ISSUE TITLE
jstorm的反压只能在supervisor中配置吗？

### ISSUE THREAD

**Issue by darouwan** [alibaba/jstorm#345]
在拓扑配置中没有搜索到back pressure的配置，反而在supervisor中搜索到了，默认是开启的~如果我想关闭，那就无法在拓扑中关闭，只能在配置文件中设置然后重启supervisor吗？

**Comment by darouwan** [comment]
我现在在配置文件中把反压设置为false，可以在各个supervisor中看到topology.backpressure.enable 的值是false，但好像反压还是在起作用。在storm ui里看到sendtps还是一阵一阵的。不知如何完全关闭？

**Comment by hustfxj** [comment]
你去看worker日志，搜一下反压的配置信息，确认下 配置是 开 是 关

**Comment by hustfxj** [comment]
你去看worker日志，搜一下反压的配置信息，确认下 配置是 开 是 关

**Comment by hustfxj** [comment]
你去看worker日志，搜一下反压的配置信息，确认下 配置是 开 是 关；如果反压实开的话，tm日志英国也是有提示的

**Comment by darouwan** [comment]
@hustfxj 可以看到topology.backpressure.enable=false，不过其他的反压配置也存在，比如backpressure.water.mark.low=0.05，topology.backpressure.water.mark.high=0.8这样的。不知这样算开启还是关闭？

**Comment by darouwan** [comment]
我现在的统计图是这样的，一阵一阵的，之前在storm0.9.5测试没有这样的情况，不知道是反压导致的吗？

**Comment by Longda-Feng** [comment]
从程序上讲， 应该是反压关闭了， 怀疑是不是，你中间有worker 挂掉了

你执行一下命令是一下
jstorm restart xxxxx restart.yaml

xxxx 是你topology的名字
restart.yaml 是配置文件， 里面配置
```
topology.backpressure.enable: false
```

试一下

**Comment by darouwan** [comment]
restart.yaml 是和jstorm/conf/storm.yaml相同吗？
刚才还发现一个问题，就是Topology Summary的Topology Graph中，点击spout，可以发现：如果sendtps非常低，所有时间段的emitted和sendtps都为空，不是0，而是格子是空的。

**Comment by darouwan** [comment]
刚才又仔细看了下，是spout所在的2个进程cpu使用率过高，将近400%，其他java进程cpu使用率也就10%不到~如果允许spout丢数据的话，如何才能让spout emit的速度比较平稳？

**Comment by Longda-Feng** [comment]
spout 400%， 而其他的只有10%， 你得用工具看一下，是什么原因让cpu利用率这么高

**Comment by yunfan123** [comment]
可以针对job级别设置反压吗？

**Comment by unsleepy22** [comment]
topology.backpressure.enable这个参数本来就是job级别的
