### ISSUE TITLE
获取监控metrics时怎么拿到topology列表？

### ISSUE THREAD

**Issue by lcy362** [alibaba/jstorm#350]
看了TopologyMetricsRunnable的代码，发现操作都是针对topology的？
怎样能拿到topology列表呢？
现在能想到直接去查zookeeper. 有办法通过jstorm本身拿到吗？

**Comment by hustfxj** [comment]
ClusterSummary clusterSummary = nimbusClient.getClient().getClusterInfo();
clusterSummary.get_topologies()
