### ISSUE TITLE
一个storm 作业开启2个worker  在同一台服务器上success，两台服务器失败

### ISSUE THREAD

**Issue by hubuyt** [alibaba/jstorm#351]
现在我的storm作业 为了能够处理更多的数据 开启了2个worker， 如果2个worker在同一台服务器上成功，如果分配到不同的服务器一台服务器启动成功，另外一台总是启动失败
![image](https://cloud.githubusercontent.com/assets/11042146/18661135/eb3f1f8a-7f46-11e6-9057-5a85f23cddae.png)
这是启动失败那台服务器supervisor日志
[supervisor.txt](https://github.com/alibaba/jstorm/files/481853/supervisor.txt)

**Comment by hubuyt** [comment]
两台不同的服务器之间可以ssh 可以ping通

**Comment by hustfxj** [comment]
你可以把supervisor上面启动worker的jvm复制一下，然后手动粘贴启动，看看有什么错误提示吗

**Comment by hubuyt** [comment]
移除storm.yaml 中的user.defined.log4j.conf参数一切正常不知道为什么
