### ISSUE TITLE
下游已经空闲,反压没有解除

### ISSUE THREAD

**Issue by lcy362** [alibaba/jstorm#353]
"pool-6-thread-1" prio=10 tid=0x00007f0bc4005000 nid=0x7de9 waiting on condition [0x00007f0c3125e000] java.lang.Thread.State: TIMED_WAITING (sleeping) at java.lang.Thread.sleep(Native Method) at com.alibaba.jstorm.task.backpressure.BackpressureController.flowControl(BackpressureController.java:104) at com.alibaba.jstorm.task.TaskBatchTransfer.transfer(TaskBatchTransfer.java:113) at com.alibaba.jstorm.task.execute.spout.SpoutBatchCollector.sendBatch(SpoutBatchCollector.java:123) at com.alibaba.jstorm.task.execute.spout.SpoutBatchCollector$1.flush(SpoutBatchCollector.java:63) - locked <0x00000007b8515e70> (a java.util.HashMap) at com.alibaba.jstorm.daemon.worker.timer.TaskBatchFlushTrigger.run(TaskBatchFlushTrigger.java:43) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745)

一直在sleep,然后隔一会发出一条数。
除了关闭反压，还有办法解决吗？

**Comment by lcy362** [comment]
SourceBackpressureInfo[tasks=[106, 107, 108, 109, 110, 111, 112, 113, 114, 115],targetTasks={xxx=TargetBackpressureInfo[tasks=[31, 40, 51],backpressureStatus=stopBackpressure,flowCtrlTime=13910,timeStamp=1474361766938

zookeeper中已经变成stopBackpressure了。但是spout现在还是一分钟左右发出一条数

**Comment by hustfxj** [comment]
这个版本的反压，解除动作是比较缓慢的。我们内部版本已经有很大的反压机制了，不过暂时不能开源。我个人建议你还是把反压关闭，不要用反压啦
