### ISSUE TITLE
资源隔离问题

### ISSUE THREAD

**Issue by Fengdada** [alibaba/jstorm#358]
负荷均衡机制中有自定义的资源隔离机制，主要是强制某些任务运行在指定的机器上，那么：
1.在不设置cgroup的情况下，是否可以指定多个TOPO运行在特定的机器上，如：
TOPO1设置：
isolation.scheduler.machines: 
    - 10.62.56.101
    - 10.62.56.102
TOPO2同样设置：
isolation.scheduler.machines: 
    - 10.62.56.101
    - 10.62.56.102
这样设置是否有问题？

2.在进行资源弹缩时（jstorm运行在容器上，容器会进行动态的弹缩），弹出新的容器后，是否需要修改自定义的配置项？还是Jstorm的负荷均衡机制会自动分配？如，弹出一个新的容器（IP地址为10.62.56.103）：
isolation.scheduler.machines: 
    - 10.62.56.101
    - 10.62.56.102
    - 10.62.56.103（是否需要增加）
TOPO2同样设置：
isolation.scheduler.machines: 
    - 10.62.56.101
    - 10.62.56.102
    - 10.62.56.103（是否需要增加）

3.jstorm部署在容器上，容器资源申请多大比较合理？一个容器分配几个端口比较合理（默认是4个）？还是完全由任务的业务逻辑来决定？有没有讲究？

**Comment by hustfxj** [comment]
1.  可以，isolation.scheduler.machines是拓扑级别的配置；
2. 要的；
3. jstorm 你没必要设置端口数量，我们默认会自动根据机器配置决定端口数量。默认一个worker 2g；

调度上面指定多个TOPO运行在特定的机器上，我建议你没必要用isolation.scheduler.machines 这个。jstorm支持自定义调度，如果可以指定某个worker在某台机器某个端口启动，如果没有设置的那些worker，就会自定利用负荷均衡机制自动分配端口号

**Comment by Fengdada** [comment]
@hustfxj 谢谢
我把多个topo放在同一台机器，是为了进行资源共享。多个TOPO的运行周期不同，前15分钟TOPO1比较忙，后15分钟TOPO2比较忙，放在一台机器正好可以充分利用资源。
jstorm的自定义调度，通过Worker指定机器号和端口号没办法达到这种效果吧？

另外，生产环境中，随着业务规模的扩充，会增加新的机器，同时修改TOPO的并行度来进行负荷均衡。负荷均衡策略：1.Worker数不变，JStorm把Worker从旧机器迁移到新机器；2.也可能修改并行度，动态增加Worker的个数，新增的Worker分配到新的资源。
按道理来说，修改并行度比较合理，但是只有当TOPO采取随机分发策略时，才能修改并行度，其他分发策略都不能修改并行度。所以只要有非随机分发策略，都只能采取方式1来进行负荷均衡。
我的理解对吗？
这种情况下，是不是按照TOPO配置负荷均衡策略更优？

**Comment by Fengdada** [comment]
@hustfxj 
关于这个问题：
jstorm 你没必要设置端口数量，我们默认会自动根据机器配置决定端口数量。默认一个worker 2g

storm.yaml文件中，默认打开4个端口：6800~6803，默认worker 2G，但是实际情况是，不管supervisor有多大内存（尝试分配2g和4g内存），一分钟后端口总是会被回收，只留下一个端口，为啥？

**Comment by hustfxj** [comment]
我们内部是根据你机器的内存 cpu 自动调整worker数量，如果你不需要的话，你配置supervisor.enable.auto.adjust.slots＝false,同时自己在storm.yaml文件里头把 端口上设置死，就可以啦

**Comment by hustfxj** [comment]
@Fengdada

**Comment by Fengdada** [comment]
@hustfxj 
谢谢，再帮忙回答一下第二个问题，期待！

**Comment by AlphaGoCome** [comment]
@hustfxj 我们切换了镜像，从ubuntu + jdk 切换为alpine + openjdk镜像，同样的jstorm2.1.1， 启动后，端口再也不会被回收了。
这个问题纠结了这么久，也没搞清楚到底是啥原因。

**Comment by hustfxj** [comment]
@AlphaGoCome  检查下supervisor.enable.auto.adjust.slots 这个开关被关上啦，@Fengdada 估计你机器是低配的话，计算出来的端口数量只能是一个吧

**Comment by hustfxj** [comment]
@AlphaGoCome  检查下supervisor.enable.auto.adjust.slots 这个开关被关上啦，@Fengdada 估计你机器是低配的话，计算出来的端口数量只能是一个吧

**Comment by AlphaGoCome** [comment]
@hustfxj 2.1.1默认的配置文件中没有这个开关吧，我们自己也没有添加这个开关。

**Comment by AlphaGoCome** [comment]
@hustfxj 昨天看了你们@Fengdada 的一个视频演讲介绍了jstorm的情况，里面下一步计划中提到了jstorm-on-docker的优化，想了解一下：
1.  jstorm中的各个角色在docker中是如何部署的，nimbus、superivisor各自独占一个docker？自动弹伸时，只弹supervisor的docker？
2.  topo如何提交？
3.  nimbus的HA如何做？

**Comment by michael8335** [comment]
搭建2.1.1版本时，启动报错导致无法启动
[INFO 2016-11-14 19:40:02 c.a.j.d.n.TopologyMetricsRunnable:134 main] create topology metrics runnable.
[INFO 2016-11-14 19:40:02 c.a.j.d.n.TopologyMetricsRunnable:155 main] pending upload metrics: 0
[INFO 2016-11-14 19:40:02 c.a.j.d.n.TopologyMetricsRunnable:382 main] adding __NIMBUS__ to metric context.
[INFO 2016-11-14 19:40:02 c.a.j.d.n.TopologyMetricsRunnable:382 main] adding __CLUSTER__ to metric context.
[INFO 2016-11-14 19:40:02 c.a.j.d.n.TopologyMetricsRunnable:382 main] adding __SUPERVISOR__ to metric context.
[INFO 2016-11-14 19:40:02 c.a.j.d.n.TopologyMetricsRunnable:202 main] metric uploader class:com.alibaba.jstorm.daemon.nimbus.metric.uploader.DefaultMetricUploader
[INFO 2016-11-14 19:40:02 c.a.j.d.n.TopologyMetricsRunnable:213 main] Successfully init com.alibaba.jstorm.daemon.nimbus.metric.uploader.DefaultMetricUploader
[WARN 2016-11-14 19:40:02 c.a.j.d.n.TopologyMetricsRunnable:221 main] use default metric query client class.
[INFO 2016-11-14 19:40:02 c.a.j.d.n.TopologyMetricsRunnable:233 main] init topology metric runnable done.
[ERROR 2016-11-14 19:40:02 c.a.j.s.FollowerRunnable:85 main] get nimbus host error!
java.lang.Exception: the hostname which Nimbus get is localhost
        at com.alibaba.jstorm.schedule.FollowerRunnable.<init>(FollowerRunnable.java:82) ~[jstorm-core-2.1.1.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.NimbusServer.initFollowerThread(NimbusServer.java:275) [jstorm-core-2.1.1.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.NimbusServer.launchServer(NimbusServer.java:121) [jstorm-core-2.1.1.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.NimbusServer.main(NimbusServer.java:95) [jstorm-core-2.1.1.jar:na]
[ERROR 2016-11-14 19:40:02 c.a.j.d.n.NimbusServer:137 main] Fail to run nimbus
java.lang.RuntimeException: java.lang.Exception: the hostname which Nimbus get is localhost
        at com.alibaba.jstorm.schedule.FollowerRunnable.<init>(FollowerRunnable.java:86) ~[jstorm-core-2.1.1.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.NimbusServer.initFollowerThread(NimbusServer.java:275) [jstorm-core-2.1.1.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.NimbusServer.launchServer(NimbusServer.java:121) [jstorm-core-2.1.1.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.NimbusServer.main(NimbusServer.java:95) [jstorm-core-2.1.1.jar:na]

现在是否不支持单机版了？？？
