### ISSUE TITLE
jstorm 2.1.1 这个分支用java8 无法编译

### ISSUE THREAD

**Issue by yunfan123** [alibaba/jstorm#363]
报错：
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.1:jar (attach-javadocs) on project jstorm-core: MavenReportException: Error while creating archive:
[ERROR] Exit code: 1 - /data09/home/zhangyunfan/repos/jstorm/jstorm-core/src/main/java/com/alibaba/jstorm/callback/impl/KillTransitionCallback.java:26: error: self-closing element not allowed

原因应该是：java8 doc 不再允许 <p/> 这种格式的注释了。

JDK 版本是： jdk1.8.0_77.jdk
可以看下这个页面：
http://stackoverflow.com/questions/26049329/javadoc-in-jdk-8-invalid-self-closing-element-not-allowed

**Comment by Longda-Feng** [comment]
@yunfan123  确实java doc 失败， 你要么提交一个pull requestion 帮我们fix 一下

**Comment by zeromem** [comment]
http://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete
javadoc的plugin加上<failOnError>false</failOnError>可以通过install，更详细的解决办法可以看上面的链接
