### ISSUE TITLE
jstorm 自定义metric有哪些，有什么文档或者例子吗？

### ISSUE THREAD

**Issue by yunfan123** [alibaba/jstorm#364]
rt.

**Comment by Longda-Feng** [comment]
https://github.com/alibaba/jstorm/tree/master/example/sequence-split-merge/src/main/java/com/alipay/dw/jstorm/example/sequence/bolt




http://jstorm.io/ProgrammingGuide_cn/AdvancedUsage/UserDefined/Metrics.html

**Comment by yunfan123** [comment]
想问下，这个metric可以支持存储到opentsdb之类的db里面吗？

**Comment by yunfan123** [comment]
我如何能够消费这个metric呢？应该有接口可以拿到worker cpu信息这种数据吧？

**Comment by unsleepy22** [comment]
可以的，你只要实现MetricUploader接口就可以

**Comment by unsleepy22** [comment]
http://jstorm.io/Maintenance_cn/JStormMetrics.html
