### ISSUE TITLE
2.1.1版本supervisor和nimbus不能在同一台机器么？

### ISSUE THREAD

**Issue by yunfan123** [alibaba/jstorm#366]
如果在同一台机器需要什么特别的配置吗？
同样的配置，如果nimbus和supervisor在同一台机器，worker数（可用端口）就是0。此时job也无法启动。

**Comment by hustfxj** [comment]
你应该是低配机器吧，你看下其他issue

**Comment by hustfxj** [comment]
你应该是低配机器吧，你看下  https://github.com/alibaba/jstorm/issues/358#issuecomment-257093680

**Comment by hustfxj** [comment]
你应该是低配机器吧，你看下  https://github.com/alibaba/jstorm/issues/358#issuecomment-257093680

**Comment by hustfxj** [comment]
你应该是低配机器吧，你看下  https://github.com/alibaba/jstorm/issues/358#issuecomment-257093680

**Comment by hustfxj** [comment]
你应该是低配机器吧，你看下  https://github.com/alibaba/jstorm/issues/358#issuecomment-257093680

**Comment by hustfxj** [comment]
你应该是低配机器吧，你看下  https://github.com/alibaba/jstorm/issues/358#issuecomment-257093680

**Comment by yunfan123** [comment]
@hustfxj , 额，我已经查到了，这个其实是jstorm本身的bug导致的。
就是在计算内存资源的时候，只计算了系统了free 的内存，没有考虑到系统cache的内存，而cache的内存很多都是可以回收的。我部署jstorm nimbus的机器和存储型业务混步，而存储型业务有大量的page cache。这个我在QQ群里面反馈过，你们在内部版本已经修复了。
