### ISSUE TITLE
jstorm on yarn 现在只支持0.9.3版本吗？

### ISSUE THREAD

**Issue by yunfan123** [alibaba/jstorm#367]
如果重新用最新版本编出来的jstorm on yarn ，我可以理解为用的是最新版的jstorm吗？

**Comment by unsleepy22** [comment]
这个是比较老版本的jstorm on yarn，还没有在最新版上测试过。最新版的还没有release。

**Comment by wuyw** [comment]
@yunfan123 我最近也在研究jstorm on yarn，能否交流一下，我的qq：839427538，方便的话加一下

**Comment by unsleepy22** [comment]
release 2.2.1，可以看下更新后的文档。
