### ISSUE TITLE
Jstorm 可以通过cgroup为每个topology限制内存吗？

### ISSUE THREAD

**Issue by yunfan123** [alibaba/jstorm#369]
jstorm现在的资源隔离好像是以worker为单位？
这个对于cpu来说OK，但是对于内存来说，有些job就会用很多内存，有些就不会.
希望能够在topology的配置里面，能够配置worker 的cgroup的内存。

**Comment by yunfan123** [comment]
因为我们不是JAVA的项目，而worker.memory.size 只能限制JVM的内存。

**Comment by unsleepy22** [comment]
可以用cgroup限制内存

**Comment by yunfan123** [comment]
怎么设置限制呢？ 似乎在2.1.1里面没看到相关代码。

**Comment by unsleepy22** [comment]
https://github.com/alibaba/jstorm/wiki/%E8%B5%84%E6%BA%90%E7%A1%AC%E9%9A%94%E7%A6%BB

**Comment by yunfan123** [comment]
能给个限制内存的例子吗？我从代码看似乎看不到有限制内存的功能。

**Comment by unsleepy22** [comment]
代码中不需要设置，跟正常启进程一样。主要是设置操作系统的cgroup中对特定组的资源限制。然后在supervisor配置中开启cgroup就可以。
