### ISSUE TITLE
我的项目用log4j2

### ISSUE THREAD

**Issue by xiaoqunhu** [alibaba/jstorm#371]
在本地跑没问题，但是一旦搬到正式环境各种日志冲突，头都疼啊，能不能jstorm用log4j或者logback,不影响我的项目用log4j2啊

**Comment by hustfxj** [comment]
你排出所有logback的jars，同时user.defined.log4j.conf=jstorm.log4j.properties

**Comment by xiaoqunhu** [comment]
排除所有的logback解决了问题，感谢
