### ISSUE TITLE
nimbusHA问题

### ISSUE THREAD

**Issue by Fengdada** [alibaba/jstorm#378]
HA的资料很少，在坛子里找到一点点HA信息：nimbusHA，就是部署多个nimbus，会自动做HA。

so，我们部署了两个nimbus的容器，的确可以达到HA的效果。但是奇怪：nimbus上的storm.yaml和TOPO jar包并没有在多个nimbus上做自动同步，nimbus host宕机重启后，就没有TOPO jar包的任何持久化信息（容器重启后没有持久化信息），为啥TOPO会正常呢？

**Comment by Longda-Feng** [comment]
如果不使用hdfs时（大家使用时，一般没有配置hdfs ）， 会做自动同步的， 自动download binary， 源码你搜索FollowerRunnable 这个类，就可以做同步操作。 


如果使用hdfs， slave nimbus 是不需要同步的，这个需要配置blobstore
