### ISSUE TITLE
请教一下jstorm作业能否远程调试

### ISSUE THREAD

**Issue by hubuyt** [alibaba/jstorm#379]
http://stackoverflow.com/questions/975271/remote-debugging-a-java-application结合这个文章
想请问一下 jstorm 作业能否像 tomcat一下   支持远程调试

**Comment by unsleepy22** [comment]
你在topology.worker.childopts里加远程调试的参数就可以。

**Comment by hubuyt** [comment]
非常感谢, 一切ok
