### ISSUE TITLE
jstorm大量watcher_executor日志

### ISSUE THREAD

**Issue by bigfool1988** [alibaba/jstorm#381]
日志中大量的没用的日志，求指导怎么解决？日志如下：
![image](https://cloud.githubusercontent.com/assets/17540653/20048220/dbca266a-a4f5-11e6-92a1-72cf9f368e54.png)

**Comment by unsleepy22** [comment]
改一下conf/jstorm.logback.xml，把zk的级别设为WARN或者ERROR就好了
