### ISSUE TITLE
咨询请教JStorm的CPU/MEM资源消耗情况

### ISSUE THREAD

**Issue by Fengdada** [alibaba/jstorm#382]
根据测试的情况：
1. nimbus启动时内存会占用到2G，CPU峰值达到180%；supervisor类似。
2. UI访问或者刷新页面时候，tomcat进程cpu会达到60%多；
3. jstorm list ，nimbus的CPU也会达到65%左右；
4. 提交topo，nimbus进程的cpu会达到60%。

想问一下：
1.上述数据，是提交一个TOPO的情况，多个TOPO正常运行时，nimbus的CPU和内存数据是否会翻多倍？我理解应该在一个稳定范围内。
2.按容器部署，把tomcat+nimbus部署在一个容器上，这个容器分配多少资源比较合适？多少cpu？多少内存？
3.目前，部署tomcat+nimbus的容器，没有申请固定的cpu资源，虚机资源也比较紧张（CPU比较紧张），这种情况下，nimbus总是会退出重启，正常不？日志中没看到异常信息。
4.在没有业务的情况下，nimbus和supervisor会占用多少资源？
请指点。

**Comment by unsleepy22** [comment]
1.release中2.1.1的nimbus有个小问题，所以CPU占用会比较高，如果自己打包，就能解决这个问题。多拓扑的情况下nimbus的CPU占用一般也还好，不会翻番，内存的话主要看自定义的metrics uploader，正常情况下也还好
2. supervisor是不大可能占用这么多CPU的，我们测试的时候极少出现这种情况
3. 不太建议用虚拟机来部署，如果只能这么做的话，建议调大内存，不然很有可能出现内存问题而导致进程退出
4. 同1

**Comment by Fengdada** [comment]
@unsleepy22 谢谢，在哪里配置nimbus和supervisor的内存？貌似nimbus默认内存是4G，supervisor默认内存是2G。自定义的metrics只能对worker进行自定义吧？
这两个配置项：
nimbus.childopts	通过storm-deploy项目部署时指定给nimbus进程的jvm选项
supervisor.childopts	在storm-deploy项目中使用,用来配置supervisor守护进程的jvm选项
仅仅是AWS云平台部署参数？

**Comment by unsleepy22** [comment]
nimbus.childopts和supervisor.childopts可以直接指定JVM参数，比如-Xmx 4g这样，跟AWS没有关系

**Comment by Fengdada** [comment]
@unsleepy22 再请教：nimbus默认内存是4G，supervisor默认内存是2G，是根据什么定义的？不考虑自定义的metrics uploader，cpu和内存的上下限分配多少比较合适？
我们要部署在容器中，资源分配有瓶颈。
谢谢！

**Comment by unsleepy22** [comment]
supervisor默认是1G吧，nimbus不管怎样metrics都会传输过来，会消耗一些内存

**Comment by Fengdada** [comment]
@unsleepy22 还是想问清楚，容器部署，他们的内存、CPU分配多少比较合适？最小最大分别是多少？给个指导意见，谢谢：）

**Comment by unsleepy22** [comment]
你说的容器部署是指docker还是什么？
Nimbus内存看集群规模，小规模的话2～4G，规模比较大的话可以适当调大。CPU一般可以给1~2个核。

**Comment by Fengdada** [comment]
@unsleepy22 对，指docker。谢谢！
