### ISSUE TITLE
如何优雅重启或停机

### ISSUE THREAD

**Issue by shang7053** [alibaba/jstorm#384]
数据源是kafka，数据量很大，每天大概将近一个T的日志，通过jstorm处理后存入hbase。要求处理数据不能丢失，那么在升级或者意外因素需要重启（暂时关闭）jstorm时，如何优雅停机，保证正在处理的数据不丢并且不接收新数据进来？以下步骤是否行？
假设要做升级
1、kill Nimbus-》升级-》重启
2、kill Supervisor （当运行在此节点上的work全部转移到别的节点上时） -》升级-》重启
3、重复2，直到全部重启完毕

**Comment by unsleepy22** [comment]
默认情况下，你杀死nimbus或者supervisor，对worker没有任何影响的，所以如果只是jstorm本身的停机，不会影响你的任务处理。

**Comment by shang7053** [comment]
好的，谢谢
