### ISSUE TITLE
JStorm UI响应较慢的问题

### ISSUE THREAD

**Issue by panguoqing** [alibaba/jstorm#386]
我们这边使用JStorm UI管理7个集群，其中进入tomcat所在的那个集群页面基本是秒进，但进入其余集群的cluster页面基本需要5 6秒甚至更长的时间，不知道有谁遇到此类问题

**Comment by unsleepy22** [comment]
这个要看集群规模了，如果集群规模很大，进入集群首页会获取很多的metrics来渲染，还会获取集群所有的拓扑信息，是会比较慢的。

**Comment by yunfan123** [comment]
+1, UI 极慢，集群规模才30台机器，一共不到2000个task，感觉UI就撑不住了。

**Comment by yunfan123** [comment]
@panguoqing ，我在我这边查了下，很可能是Nimbus慢的问题，不知道你那边是不是。
我感觉上nimbus有内存泄漏，你看你nimbus是不是有OutOfmemory的Exception。话说能问下阿里最大的jstorm集群使用的是哪个版本的jstorm么？

**Comment by yunfan123** [comment]
@panguoqing ，你用的是什么版本，我的是2.1.1，我怀疑是因为Nimbus慢导致的。
感觉上Nimbus似乎有内存泄漏，我设置了40g内存，nimbus还能用满，而且无法gc回收。

**Comment by unsleepy22** [comment]
@yunfan123 那肯定是不正常的，我们线上也不会用这么大的内存来配置nimbus。

**Comment by unsleepy22** [comment]
@yunfan123 你是自己打的包还是直接用的release里面的二进制包？

**Comment by unsleepy22** [comment]
正常来说，你不到2K个task，nimbus的堆内存可以配置成8G。

**Comment by yunfan123** [comment]
我自己打的包，不过基于2.1.1打包和你们打的包有区别吗？
@unsleepy22 ，我观察到 backtype.storm.generated.MetricSnapshot 这个类会占用大量的内存。
是不是这个版本中的metric过多，内存占用过大？

**Comment by unsleepy22** [comment]
@yunfan123 加 https://gitter.im/alibaba/jstorm 聊

**Comment by unsleepy22** [comment]
@panguoqing 在你集群的storm.yaml里加两个配置：
```
topology.enable.stream.metrics: false
topology.max.worker.num.for.netty.metrics: 0
```
然后重启一下集群(nimbus和supervisor)以及拓扑，再看看
