### ISSUE TITLE
Nimbus 使用内存非常大，经常异常退出

### ISSUE THREAD

**Issue by yunfan123** [alibaba/jstorm#387]
在使用jstorm 2.1.1的时候，JVM设置内存到40g，但是Nimbus还是经常OutOfMemory.
集群一个job，不过单job有1300个task。
还有Nimbus经常报一个错误zk上就没有nimbus的master node了。错误如下：

[WARN 2016-11-28 15:55:26 c.a.j.c.DistributedClusterState:84 CuratorFramework-0-EventThread] Received event Disconnected:None:null with disconnected Zookeeper.

另外，弱弱问句在阿里内部jstorm最大的集群用的是什么版本。。。我感觉2.1.1其实问题还挺多的。。。

**Comment by yunfan123** [comment]
zk那个问题应该也是内存问题，看gc log一直在做full gc，但是确回收不了多少内存。
怀疑是nimbus哪里有内存泄漏，nimbus应该不需要太多的内存吧？

**Comment by yunfan123** [comment]
看了下heap，大多数内存耗在backtype.storm.generated.MetricSnapshot。
 num     #instances         #bytes  class name
----------------------------------------------
   1:      71863012    12647890112  backtype.storm.generated.MetricSnapshot
   2:       4907178    10634146552  [B
   3:      90164776     4327909248  java.util.HashMap$Node
   4:      19690436     4322308072  [C
   5:      18263492     2060020896  [Ljava.util.HashMap$Node;
   6:      35428413     1983991128  java.nio.HeapByteBuffer
   7:      53610579     1286653896  java.lang.Integer
   8:      18272470     1169438080  java.util.HashMap
   9:      19689816      630074112  java.lang.String

应该是这块存在内存泄漏，按道理来说就4个窗口，这块内存很小才对。

**Comment by unsleepy22** [comment]
这个问题现在OK了吧？

**Comment by yunfan123** [comment]
OK了。主要问题是我们误用，导致component 过多，metric过多。
另外，关掉了stream metric和netty metric也有帮助。
还是就是不知道之后job很多导致component过多会不会导致nimbus内存过大。

**Comment by unsleepy22** [comment]
OK，那close了
