### ISSUE TITLE
新人，请教一个worker内task通信问题

### ISSUE THREAD

**Issue by moroseking** [alibaba/jstorm#388]
jstorm，task数一定的情况下，worker数少一点，能减少worker内的task通信消耗这点，能否讲解一下，我目前的理解就是，能让同一个stream的各个task在一个worker进程内，从而使数据不出进程即可处理完成，减少了数据对象的序列化和反序列化。
目前的疑惑就是：jstorm在分配拓扑的时候，是如何做到，让同一个流的各个task 到同一个worker内的？是否有比如说即使spout，bolt在同一个worker内，但是spout依然向其他worker内的bolt发送的问题出现？如果做到的worker内的节点优先通信本进程内的？因为具体的task分配是在启动拓扑的时候进行的，所以这块有点疑惑，想请教一下！

**Comment by yunfan123** [comment]
这个肯定不可能在分配的时候考虑啊，框架不可能知道你的数据是什么。
只是在job跑起来之后，尽量保证如果在同一个worker内用进程内通信。你可以看下TaskTransfer里面innerTaskTransfer的实现。

**Comment by moroseking** [comment]
我看了下新的localOrShuffleGrouping 这种分发，已经明白了，目前是先判断是否在一个worker内，如果是，直接发到本worker内，如果在一个节点上，不在一个worker中，优先发到本节点内的其他线程中，如果都不在一个节点，才是最后的选择策略，这样就实现了传输的最优化！设计果然很棒
