### ISSUE TITLE
backpressure是nimbus还是supervisor的配置？

### ISSUE THREAD

**Issue by lcy362** [alibaba/jstorm#391]
改集群配置的话是只改nimbus就行还是每个节点都要改？

**Comment by unsleepy22** [comment]
是nimbus的配置 + topology的配置。其中topology的配置会覆盖nimbus配置。但是如果你topology没有设置，那实际上会读取supervisor的配置。
如果你需要全局地启用或者禁用，那就需要改每个节点的配置。

**Comment by lcy362** [comment]
明白了
