### ISSUE TITLE
2.1.1 Launch worker的时候可能会hang住

### ISSUE THREAD

**Issue by yunfan123** [alibaba/jstorm#392]
ProcessBuilder默认会创建一个PIPE给子进程的stdout，stdin和stderr。
而在jstorm ProcessLauncher main中，刚开始就会System.out.print 当前环境，如果这个到stdout中数据过大，到了PIPE缓存的最大值，可能会造成worker起不来。

**Comment by unsleepy22** [comment]
2.2.1里默认把redirect关掉了，马上会release
