### ISSUE TITLE
jstorm 重启后 会不会重复消费一部分数据

### ISSUE THREAD

**Issue by hubuyt** [alibaba/jstorm#393]
请问现在jstorm 消费kafka的数据，如果因为业务需要 需要重新启动jstorm，而之前jstorm消费的offset没有写进zk，重启的时候 是不是存在重复消费部分数据的可能

**Comment by someorz** [comment]
会，简单的kafka消费者无法避免这种情况。可以自己管理offset，kafka比较适合不在乎丢失，重复消费一些数据的场景。
英文原文：https://dzone.com/articles/kafka-clients-at-most-once-at-least-once-exactly-o
完整源代码GitHub: https://github.com/ajmalbabu/kafka-clients//
