### ISSUE TITLE
Python依赖的问题

### ISSUE THREAD

**Issue by AlphaGoCome** [alibaba/jstorm#395]
在docker中部署jstorm，我们希望基础镜像中不包含python，只有jdk，
那么，启动nimbus、supervisor，提交topo等可以通过调用java API接口来替换，但不清楚jstorm在运行过程中是否还使用了python命令？在没有python的docker中，jstorm是否可以正常运行？

**Comment by unsleepy22** [comment]
这个改动比较大，暂时没有这个计划。但是python对版本要求不高啊，只要2.6以上就可以。

**Comment by AlphaGoCome** [comment]
@unsleepy22 跟python版本无关，跟我们是否需要单独维护 一个java + python的基础镜像有关。
目前我能看到的jstorm中使用python的地方：启动nimbus、supervisor，提交topo，rebalance等命令，但这些命令实际上都是封装的java API接口，我在使用时可以直接调用API，从而避开使用python命令。
所以，我的问题是：
1. 除了上述命令，目前，jstorm**运行期间**是否还有哪个地方依赖了python？
2. 如果没有python，目前的jstorm是不是无法正常运行？

**Comment by unsleepy22** [comment]
运行时一般的任务是不会依赖python的，除非是multi-lang的。不过你们改了还得测试一遍。。。
