### ISSUE TITLE
Jstorm任务的动态伸缩

### ISSUE THREAD

**Issue by Fengdada** [alibaba/jstorm#400]
应用场景：nimbus和supervisor部署在PaaS上，我们会配置supervisor的弹缩策略（nimbus不弹缩）。但是当supervisor弹缩后，需要动态修改TOPO的并行度，才能充分利用新增增的资源。
这样，我们只能获取topo的metrics，根据metrics的信息调整进程/线程并行度，这样理解对吗？

1.如果理解正确，如何来获取topo的metrics？翻了下论坛，有提到ServiceHandler.getTopologyMetrics()方法来获取，也有提到实现一个MetricUploader来获取。应该用哪种？

2.getTopologyMetrics()方法返回TopologyMetric，这个类的定义中没具体的metrics信息，反序列队列负荷、执行队列负荷等都在哪？

3.如何判断需要增加还是减小并行度？

**Comment by Fengdada** [comment]
JStorm框架是否会完善动态伸缩方案？

**Comment by unsleepy22** [comment]
1. 我觉得动态伸缩最终还是需要根据业务来决定的，不是说你资源多了，你的并行度就应该加大。。。
2. metrics的获取，在没有使用自定义MetricUploader的时候，通过ServiceHandler.getTopologyMetrics获取，如果你自己定义了外部的metrics存储，那就无所谓了，可以实现MetricQueryClient来自己决定如何获取。
3. 队列信息的metrics在task metrics中。

**Comment by Fengdada** [comment]
@unsleepy22 有没有metrics的相关文档？比如Topo、Worker、task的metrics列表及含义，或者源码位置，没找到具体的metrics定义。

**Comment by unsleepy22** [comment]
这个文档我后面完善一下

**Comment by unsleepy22** [comment]
metrics文档已经在jstorm.io更新了
