### ISSUE TITLE
Topology提交时的worker数怎么计算

### ISSUE THREAD

**Issue by someorz** [alibaba/jstorm#401]
Topology提交时的worker数，有计算的方法吗？比如说一个woker最多运行多少个task？按总的task数来设定worker数？集群可用的worker数是根据什么来算的？是按照端口数量吗？
supervisor.slots.ports:
    - 6800
    - 6801
    - 6802
    - 6803

**Comment by Fengdada** [comment]
worker数是根据端口数量来判断的，默认情况下，端口数量是根据系统资源来计算的，系统资源多，可用端口数就多。

**Comment by someorz** [comment]
就是说我添加supervisor.slots.ports这个端口，就可以增加worker数，这样理解对吧。

**Comment by someorz** [comment]
我有三个结点的jstorm集群，每个结点配置了5个端口，应该一共有15个worker。但我测试时发现并没有。
![image](https://cloud.githubusercontent.com/assets/5456361/21497359/62742612-cc5f-11e6-82af-78f9c4be60fc.png)

![image](https://cloud.githubusercontent.com/assets/5456361/21497337/49cdc1e0-cc5f-11e6-972c-11c6511021a5.png)

**Comment by someorz** [comment]
@Fengdada 我在三个结点的jstrom集群上，每个结点设置5个端口，但可用的worker数并不是15个。
![image](https://cloud.githubusercontent.com/assets/5456361/21497453/f21ff246-cc5f-11e6-9e0a-6cf38b30b085.png)

**Comment by unsleepy22** [comment]
你看下web ui中supervisor页每个supervisor的worker数

**Comment by Longda-Feng** [comment]
你看看这篇文档  http://jstorm.io/Maintenance_cn/SupervisorWorker.html
