### ISSUE TITLE
JStorm 与 Kafka 合用可否有办法保证Kafka（多分区）数据的顺序行呢？

### ISSUE THREAD

**Issue by iamjohnnyzhuang** [alibaba/jstorm#402]
Kafka只能保证一个分区数据的顺序性。但是我在Kafka里存储的数据量较大，如果只有一个分区是显然不够存储的。
而且我存储在Kafka的数据要求有时序性，对于每条数据需要计算两条相差的值并且做相应的操作。

想了很久实在没想出有什么好方案，尝试过在bolt做延迟计算（延迟两分钟存储来修正顺序）但是有些数据延迟的实在久，两分钟貌似有时候也不够。
请问下这种业务场景下是否有什么好的办法解决呢？

**Comment by someorz** [comment]
你每条数据业务上有没有一个唯一标识，比较说你要计算前后两条数据相差，但这两条数据应该是相同的id的。如果数据上有这样的id，可以增加kafka分区，生产者在写kafka时，指定key为id，value为消息。这样能保证相同的id会发送到相同的分区。分区可以保证顺序的。如果没有这么一个id，是不是考虑下，kafka不太适合你的使用场景。

**Comment by iamjohnnyzhuang** [comment]
你的建议对我有很大的帮助，感谢！
