### ISSUE TITLE
一个worker上运行多少个task比较合适

### ISSUE THREAD

**Issue by someorz** [alibaba/jstorm#403]
我想知道一个默认的worker(2G内存)，推荐运行多个任务？我在做性能测试时，发现11个worker运行2266个task集群就出现大量的No response from Task报错，然后kafka消费者都就挂掉了。有没有计算方法，能估算出一个worker运行多个task。

**Comment by unsleepy22** [comment]
worker跟task的比例，一般不建议超过1:10。
