### ISSUE TITLE
Stop BackPressure 消息丢失

### ISSUE THREAD

**Issue by vivilife** [alibaba/jstorm#404]
最近一个 Topology 出现问题， 8个spout 中只有 2个正常发送消息，另外6个每分钟发送消息为个位数。 

dump出worker 的heap 发现，这些有问题的spout 处于 backpressure 状态， sleep 时间高达86秒。因为有2个spout 工作正常，怀疑这6个spout的 stop backpressure 消息丢失。

请问 JStorm 能否确保backpressure 之类的控制消息不会丢失？如果可能丢失，能否通过重发消息解决

**Comment by Longda-Feng** [comment]
这个问题在2.2.0 版本中fix了

**Comment by Longda-Feng** [comment]
2.2.1 会在春节前 对外release 掉

**Comment by unsleepy22** [comment]
released
