### ISSUE TITLE
好像一个新bug：关于TOPO提交API

### ISSUE THREAD

**Issue by Fengdada** [alibaba/jstorm#405]
backtype.storm.StormSubmitter

    public static void submitTopology(String name, Map stormConf, StormTopology topology) throws AlreadyAliveException, InvalidTopologyException {
        submitTopology(name, stormConf, topology, null);
    }
......
    private static String submittedJar = null;
    private static String path = null;

    private static void submitJar(NimbusClient client, Map conf) {
        if (submittedJar == null) {
            ......提交jar
        } else {
            LOG.info("Jar already uploaded to master. Not submitting jar.");
        }
    }

问题在于submittedJar 是个静态变量
第一次调用submitTopology()方法提交TOPO时，可以正确提交jar包和TOPO，但是提交完成后，submittedJar并没有置为null，导致：
第二次调用submitTopology()方法提交其他TOPO时，仅打印但不提交TOPO。

应该是bug还是就仅仅允许提交一次TOPO？

**Comment by Longda-Feng** [comment]
对，确实是有这个问题， 以前也发现了， 但目前没有人进行重复提交，所以这个问题也就没有fix

@Fengdada  你有重复提交的需求吗， 你可以尝试fix 一下，然后提交一个pull request 给我们，我们review 一下

**Comment by Fengdada** [comment]
@Longda-Feng 已提交。
