### ISSUE TITLE
如果在bolt里边创建数据连接，可以多个bolt用一个连接池吗？

### ISSUE THREAD

**Issue by someorz** [alibaba/jstorm#407]
我在bolt里边需要查询数据库，我想知道bolt之间能不能共用一个连接池。还是必须在各自的prepare里边初始化连接。

**Comment by moroseking** [comment]
这个我觉得应该是具体问题具体分析吧，毕竟涉及到序列化和传输的问题，这里的并发，我的理解是序列化后传输的实现，而不是单纯的创建多线程来做

**Comment by liyong1028826685** [comment]
可以使用单例，目前我们公司就这样处理

**Comment by someorz** [comment]
@liyong1028826685 我也用过单例，但看log发现，跟之前设想的不一样，之前想过用单例后，每个worker会共享一个连接池对象，但实际上是每个task会创建一个连接池对象，单例没启作用。
