### ISSUE TITLE
源码编译失败

### ISSUE THREAD

**Issue by songzhongkai** [alibaba/jstorm#412]
源码编译，依赖metaq-client 3.1.8 这个应该是没有放出来的，外面都找不到

**Comment by moroseking** [comment]
同问，编译的时候也遇到了这个问题

**Comment by songzhongkai** [comment]
2.1.1可以编译的

**Comment by unsleepy22** [comment]
我咨询一下metaq的同学，你们可以先把这个模块注掉。

**Comment by Longda-Feng** [comment]
@songzhongkai  你提交一个pull request， 把metaq版本降一下
