### ISSUE TITLE
自定义MetricUploader只能是针对整个集群？

### ISSUE THREAD

**Issue by superwood** [alibaba/jstorm#413]
实现自定义MetricUploader 只能配置在一个集群上而不是针对单个Topology？ 
 原生strom每个Topology可以自定义注册IMetricsConsumer方式 是否在jstorm能实现？

**Comment by unsleepy22** [comment]
目前最小单位是集群，原生的storm metric consumer有一些缺点，所以在jstorm 2.x中不支持了。

**Comment by superwood** [comment]
@unsleepy22 

我在spout里面自定义了一个counter类型的metric

		metricClient = new MetricClient(context);
		myCounter = metricClient.registerCounter("MyCounter");

在自定义的MetricUploader里面打印出来如下内容。 感觉很难理解这个内容。

首先 key CC@kafkaboltTest-5-1484289385@kafkaSpout@0@@udf@MyCounter  规则没有详细说明

其次 里面有4项  每项的里面的数字key 60 600 7200 86400不知道代表什么含义？

三者  为什么有4项  每项里面的内容有是什么？ 


CC@kafkaboltTest-5-1484289385@kafkaSpout@0@@udf@MyCounter={

600=MetricSnapshot(metricId:-6524749770146267167, ts:1484290500000, metricType:1, longValue:59780), 

7200=MetricSnapshot(metricId:-6524749770146267167, ts:1484291040000, metricType:1, longValue:158430), 

60=MetricSnapshot(metricId:-6524749770146267167, ts:1484291040000, metricType:1, longVal    ue:5960), 

86400=MetricSnapshot(metricId:-6524749770146267167, ts:1484291040000, metricType:1, longValue:158430)

}

**Comment by superwood** [comment]
@unsleepy22   目前就没有一个好的接口，能够通过Topology名字，component类型 , metric名字就能获取到metric

**Comment by Longda-Feng** [comment]
你去看 https://github.com/alibaba/jstorm/blob/master/example/sequence-split-merge/src/main/java/com/alibaba/starter/utils/JStormHelper.java 这个类里面CheckAckedFail 是怎么用的

**Comment by unsleepy22** [comment]
@superwood 你先看下这个文档，http://jstorm.io/Maintenance_cn/JStormMetrics.html

**Comment by unsleepy22** [comment]
key 60 600 7200 86400是指窗口值，1分钟，10分钟，2小时和1天
