### ISSUE TITLE
咨询关于Jstorm的一些Api接口

### ISSUE THREAD

**Issue by caiyifeng** [alibaba/jstorm#414]
您好：
      我想做关于Jstorm的控制功能，比如 Topology的启动，停止等；请问是否有相关Api接口可以调用，或者给个Demo，我自己看看，多谢了

**Comment by zhaiyuyong** [comment]
为什么要api？直接jstorm的命令不行么？

**Comment by caiyifeng** [comment]
直接jstorm命令对于熟悉的人来说当然好了，对于不熟悉的维护人员来说，我要做的是一个调度和配置平台，直接页面操作就行，不需要了解jstorm。这个可以通过调用shell脚本，但如果有相关的api调用则更好，因为还需要做各种的日志记录等操作！！

**Comment by unsleepy22** [comment]
通过NimbusClient调用。

**Comment by caiyifeng** [comment]
@unsleepy22 请问有demo实例吗，请指教下哈。。。。多谢

**Comment by unsleepy22** [comment]
看下`backtype.storm.command`这个package下面的类
