### ISSUE TITLE
Jstorm - 2.1.1 类Backpressure发现个小bug

### ISSUE THREAD

**Issue by gaozhengjiu** [alibaba/jstorm#415]
` if (stormConf.containsKey(BACKPRESSURE_DELAY_TIME)) {
            long time = JStormUtils.parseLong(stormConf, 0l); 
            if (time != 0l) {
                this.sleepTime = time;
            }
 }`

// long time = JStormUtils.parseLong(stormConf, 0l); 
 long time = JStormUtils.parseLong(stormConf.get(BACKPRESSURE_DELAY_TIME), 0l);

**Comment by Longda-Feng** [comment]
谢谢， 不过， 2.2.1 后，重写了backpressure， 已经没有这个问题
