### ISSUE TITLE
jstorm kill Topology会有消息丢失吗？

### ISSUE THREAD

**Issue by someorz** [alibaba/jstorm#416]
在对Topology进行升级时，如果kill掉正在运行的Topology，Topology中正在计算的数据是否会丢失？还是Jstorm在收到到kill命令会停止调用Spout，等到bolt中的数据都处理完成后，才真正kill掉Topology？

**Comment by unsleepy22** [comment]
会有可能的，jstorm不会等待数据处理完成。不过可以在kill的时候指定一个等待时间，这样jstorm会在等待时间之后再执行kill。

**Comment by someorz** [comment]
@unsleepy22 那如果我要对线上运行的程序进行升级，有什么方法可以避免消息丢失的情况吗？kill 命令加上指定等待时间，会先停掉spout，然后等待指定时间再kill掉Topology吗？

**Comment by unsleepy22** [comment]
是的，会先deactivate spout。

**Comment by someorz** [comment]
@unsleepy22 jstorm  update_topology -jar 用这个的命令更新jar包，可以做到不kill Topology，实现程序更新吗，避免消息丢失的情况？

**Comment by unsleepy22** [comment]
这个是用来做快速重启的，是可以不用kill topology，而且会尽量处理内存中的消息，但是也不能完全避免消息丢失。内部实现是shutdown tasks然后重新create，shutdown这个过程不能保证消息一定被处理完。
