### ISSUE TITLE
TaskHeartbeatTrigger里面executeThreadHbTime应该声明为volatile。

### ISSUE THREAD

**Issue by yunfan123** [alibaba/jstorm#422]
修改该变量和访问该变量不在一个线程里面。否则可能因为访问不到最新的修改，而reporter error。

**Comment by longdafeng** [comment]
@yunfan123  你提交一个pull request 提交吧

**Comment by yunfan123** [comment]
https://github.com/alibaba/jstorm/pull/430 @longdafeng

**Comment by yunfan123** [comment]
之前的CLA有问题，看 https://github.com/alibaba/jstorm/pull/431 。
