### ISSUE TITLE
动态计算mem port num问题  版本 2.1.1

### ISSUE THREAD

**Issue by superwood** [alibaba/jstorm#424]
看来下代码发现如下
JStormUtils.java 类  函数
getSupervisorPortNum
            if (memPortNum < 1) {
                LOG.info("Invalid worker.memory.size setting:" + workerMemSize);
                memPortNum = reserved ? 1 : 4;
            } else if (memPortNum < 4) {
                LOG.info("System memory is too small for Jstorm");
                memPortNum = reserved ? 1 : 4;
            }

感觉这块代码毫无意义。 memPortNum只要是小于4  都会归结成 1    不明白为何是这样的

**Comment by unsleepy22** [comment]
这个应该是当时针对我们内部VM的代码，2.2.1已经改掉了，不是这样了
