### ISSUE TITLE
MetaSpout 里边有一些属性为什么加上transient ？

### ISSUE THREAD

**Issue by someorz** [alibaba/jstorm#426]
`public class MetaSpout implements IRichSpout, IAckValueSpout, IFailValueSpout, MessageListenerConcurrently {

    private static final long serialVersionUID = 8476906628618859716L;
    private static final Logger LOG = LoggerFactory.getLogger(MetaSpout.class);

    protected MetaClientConfig metaClientConfig;
    protected SpoutOutputCollector collector;
    protected transient MetaPushConsumer consumer;

    protected Map conf;
    protected String id;
    protected boolean flowControl;
    protected boolean autoAck;

    protected transient LinkedBlockingDeque<MetaTuple> sendingQueue;

    protected transient MetricClient metricClient;
    protected transient AsmHistogram waithHistogram;
    protected transient AsmHistogram processHistogram;
`

**Comment by longdafeng** [comment]
nimbus 接受一个任务时， 会把对象序列化成一个文件，广播到集群中， 因此所有的对象都必须实现Serializable,  对于一些无法实现Serializable的成员变量 都必须加上transient， 提交任务时，不需要对该对象进行序列化， 因此还有一个问题，就是在任务真正在worker上开始运行时， 也就是spout开始调用open或bolt调用prepare时， 必须把这个对象创建出来。
