### ISSUE TITLE
自定义MetricUploader的用法，确认一下

### ISSUE THREAD

**Issue by lcy362** [alibaba/jstorm#442]
是说拿到MetricCache以后，自己起个线程，该怎么处理怎么吗？

MetricUploader接口里提供的几个方法，测了一下，要不就是TopologyMetricsRunnable里不会调，要不就是输入信息不全，很多数据拿不到。

**Comment by unsleepy22** [comment]
请参考一下：http://jstorm.io/Maintenance_cn/JStormMetrics.html
