### ISSUE TITLE
jstorm flux-core问题

### ISSUE THREAD

**Issue by sjq597** [alibaba/jstorm#447]
官方提供了插件式声明任务，文档在这:
http://jstorm.io/ProgrammingGuide_cn/AdvancedUsage/Plugins/Flux.html

但是这个教程里面的包:
```
<dependency>
    <groupId>com.alibaba.jstorm</groupId>
    <artifactId>flux-core</artifactId>
    <version>${jstorm.version}</version>
</dependency>
```
这个并没有找到，是还没有发布的新版特性吗？

**Comment by fengjian428** [comment]
master分支上有的

**Comment by sjq597** [comment]
@fengjian428 确实哈，我之前看引用的路径是`com.alibaba.jstorm`以为在核心包或者扩展包里面，没找到，谢谢了

**Comment by mrgiser** [comment]
@sjq597  你好，我在项目中添加依赖如下，maven无法下载com.alibaba.jstorm:flux-core:jar:2.2.1
<dependency>
    <groupId>com.alibaba.jstorm</groupId>
    <artifactId>flux-core</artifactId>
    <version>2.2.1</version>
</dependency>

请问可知道这个依赖问题怎么解决？
