### ISSUE TITLE
写了一篇从 JStorm 向 redis 中处理的博文(牵涉到多线程......)，还望指正哈～～

### ISSUE THREAD

**Issue by Allianzcortex** [alibaba/jstorm#448]
最近把之前做的一个东西进行了总结，写了这样一篇博文 [一个 Java 多线程程序实例——JStorm 处理逻辑](http://allianzcortex.me/2017/03/06/write-a-java-multithreading-application/)。不是很确定这是不是正确的处理方法，希望能交流一下⊙﹏⊙b

还有一个小问题～，最近在尝试阅读 JStorm 的源码，想知道编译调试的最好途径是.....？在导入 Intellij IDEA CE 后它会自动引入所有的依赖包，没有报错。

![jstorm-u](https://cloud.githubusercontent.com/assets/7290780/23698749/b0416328-0427-11e7-99ab-e323cec55eff.png)

**Comment by Allianzcortex** [comment]
嗯，调试这个我觉得从源码调试不是一个好的选择。因为之前写过一个 [Jstorm-split-word-count-ack-demo](https://github.com/Allianzcortex/Jstorm-split-word-count-ack-demo)，所以从应用入手感觉能更好地理解逻辑和相互之间的调用关系(特别是理清 backtype.storm 和 com.alibaba.jstorm 之间的依赖)。写了一篇半成品的博客 [jstorm-submit-topology-mechanism/](http://allianzcortex.me/2016/12/10/jstorm-submit-topology-mechanism/)，哈^_^

**Comment by unsleepy22** [comment]
看源码的话，可以从两方面来看，一方面是它的部署模式和运行模式，nimbus server, supervisor, worker, task。另一方面从应用的维度，从前到后。

在jstorm中使用线程池的话，建议谨慎使用cached thread pool，可以使用有界的线程池~ cached thread pool在极端的情况下容易造成线程池泄漏，即，一个worker中可能有上千个线程，一方面cpu时间都花在上下文切换上了，另一方面，大量的线程也会浪费系统资源

**Comment by Allianzcortex** [comment]
@unsleepy22 所以就是建议使用 fixedPool 喽～嗯，所以也就是选择一个比较合适的线程池数目来处理了。

**Comment by unsleepy22** [comment]
也不一定是fixedPool，ThreadPoolExecutor可以设置corePoolSize和maximumPoolSize

**Comment by Allianzcortex** [comment]
@unsleepy22 嗯，自定义一个 ThreadFactory 嘛：- D  不过这就要求一直监控业务来判断取值是否合适了
