### ISSUE TITLE
和kafka 整合连一点例子都没有？

### ISSUE THREAD

**Issue by zgqq** [alibaba/jstorm#455]
折腾好久了，资料真的太少了

**Comment by sjq597** [comment]
这个不就是spout那初始化的时候从kafka读消息然后处理吗

**Comment by zgqq** [comment]
@sjq597 道理我都懂，真实整合听起来各种报错

**Comment by sjq597** [comment]
@zgqq https://github.com/alibaba/jstorm/blob/master/jstorm-utility/jstorm-kafka/src/main/java/com/alibaba/jstorm/kafka/KafkaSpout.java

这个代码应该满足你的要求

**Comment by zgqq** [comment]
@sjq597 本地调试报这个错
Caused by: java.lang.IllegalStateException: Attempting to call unbound fn: #'carbonite.api/register-serializers
	at clojure.lang.Var$Unbound.throwArity(Var.java:43) ~[clojure-1.6.0.jar:na]
	at clojure.lang.AFn.invoke(AFn.java:36) ~[clojure-1.6.0.jar:na]
	at clojure.lang.Var.invoke(Var.java:383) ~[clojure-1.6.0.jar:na]
	at carbonite.JavaBridge.registerPrimitives(JavaBridge.java:43) ~[carbonite-1.4.0.jar:na]
	at backtype.storm.serialization.SerializationFactory.getKryo(SerializationFactory.java:72) ~[jstorm-core-2.1.1.jar:na]
	... 13 common frames omitted

**Comment by cathar** [comment]
我们项目有用啊，这很常用啊

2017-03-17 10:24 GMT+08:00, zgqq <notifications@github.com>:
> 折腾好久了，资料真的太少了
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alibaba/jstorm/issues/455


-- 
Huan He  何 欢
Dept. of Computer Science & Technology
Tsinghua University, Beijing, China, 100084
Office: FIT Building 4-104, Tel: 8610-62603063

**Comment by zgqq** [comment]
@cathar storm和kafka 起码还有一个例子看看，能不能扒点东西下来看看

**Comment by sjq597** [comment]
@zgqq 我从项目里面拔了点儿关键的代码,这是个spout,因为是连接kafka,所以作为了一个公共的spout,在open方法里面先初始化就行
```
    @Override
    public void open(Map conf, TopologyContext context, SpoutOutputCollector collector) {

        // 初始化collector
        this._collector = collector;
        // 初始化consumer
        this.map = Maps.newConcurrentMap();

        //初始化consumer
        this.consumer = new KafkaConsumer(zookeeperConnect, topics, group, 10000);
        //
    }
```
然后所有的bolt和spout都可以用这个公共的来连kafka,记得zk,topic,这些都可以从构造函数传入就行了

**Comment by elloray** [comment]
`KafkaSpoutConfig spoutConf = new KafkaSpoutConfig(
                ConfigUtil.getProperties());
        // 定义一个Topology
        TopologyBuilder builder = new TopologyBuilder();
        builder.setSpout(spoutId, new KafkaSpout(spoutConf));`
依赖jstorm-kafka

**Comment by zgqq** [comment]
@sjq597 @elloray 
又有奇怪的错误，google了好久还是没有找到解决方案
本地集群报错，获取不了消息
17:42:14.284 [kafka2-spout:4-SingleThreadSpoutExecutors] ERROR c.a.jstorm.kafka2.PartitionConsumer - fetch null message from offset 0
17:42:14.284 [kafka2-spout:4-SingleThreadSpoutExecutors] DEBUG com.alibaba.jstorm.kafka2.KafkaSpout - ====== partition 0 emit message state is EMIT_END
kafka报错
kafka.common.OffsetOutOfRangeException: Request for offset 1 but we only have log segments in the range 0 to 0.

**Comment by zgqq** [comment]
@elloray jstorm-kafka 我构建不起来，应该是镜像原因，我都换好几个了，没有什么卵用

**Comment by elloray** [comment]
@zgqq 看错误信息是这个分区上没有消息

**Comment by elloray** [comment]
@zgqq 使用命令行构建下，这个jstorm-kafka是可用的，我现在在生产环境使用

**Comment by zgqq** [comment]
@elloray 我用命令行发送消息了bin/kafka-console-producer.sh --broker-list localhost:9092 --topic hello
还有jstorm-kafka 我也是用命令行构建的，几个镜像地址老是卡着不动，还有某些库是某个地址特有的，这才是最蛋疼的地方

**Comment by elloray** [comment]
@zgqq 
1. 直接用消费代码看是能消费的嘛
2. 本地依赖jstorm-core，其余的都是很常见的库，不会吧

**Comment by zgqq** [comment]
@elloray 
1.直接是可以消费的
2.真的，淘宝和开源中国的镜像非常慢

**Comment by elloray** [comment]
@zgqq
1. 这个topic分区个数是几个？有没有设置到kafkaConf里面？
2. 我本地使用maven中央仓库非常快，可以试试用其他的源

**Comment by zgqq** [comment]
@elloray 
1.我设置1和2都不行，kafkaConf 有设置 （因为我构建不了jstorm-kafka，我直接把它的源码copy到我的项目）
2.现在把淘宝，twitter和开源中国的repo，移除掉好像暂时没问题，我记得有几个库是twitter特有的

**Comment by elloray** [comment]
@zgqq 
1. kafkaConf里面的`kafka.broker.partitions`一定要和你相应topic的分区数一致
2. jstorm应该不依赖twitter的东西

**Comment by zgqq** [comment]
@elloray         
这是我的基本配置
       ```
 Map conf = new HashMap();
        conf.put("kafka.topic", "hello");
        conf.put("kafka.broker.partitions", 1);
       //  kafka2.socket.receive.buffer.bytes
        KafkaSpoutConfig kafkaSpoutConfig = new KafkaSpoutConfig();
        kafkaSpoutConfig.configure(conf);

        TopologyBuilder builder = new TopologyBuilder();
        builder.setSpout("kafka-spout", new KafkaSpout(kafkaSpoutConfig));
```
奇怪的是消费者在命令行和用kafka的接口都没问题，偏偏整合起来就不行了

**Comment by zgqq** [comment]
@elloray 非常感谢，已经找到原因了，现在像你这么热心的大佬已经不多了，已经follow

**Comment by zgqq** [comment]
一行配置引发的惨案

**Comment by kevin19931015** [comment]
什么原因呢 是因为kafka.broker.partitions吗
