### ISSUE TITLE
用jstorm-kafka里的KafkaSpout读数据每次都是从头开始？

### ISSUE THREAD

**Issue by MarcusQian** [alibaba/jstorm#458]
是用本地模式跑的，配置如下：
kafka.zookeeper.hosts=192.168.153.xxx:2181,192.168.153.xxx:2181
kafka.broker.hosts=192.168.153.xxx,192.168.153.xxx
kafka.client.id=client0
kafka.topic=testTopic
kafka.broker.partitions=5
kafka.fetch.from.beginning=false

需要什么额外的改动吗？

还有就是这个topic是可以读到数据，换了另一个topic就不行,一直是fetch null message from offset xxx。

用storm-kafka就没这么多问题。。。 但是[issue-133](https://github.com/alibaba/jstorm/issues/133)又说storm-kafka线程上不安全。。。

**Comment by MarcusQian** [comment]
把zookeeper里存offset的目录全删掉后，无论哪个topic都是fetch null message。。。
这个不应该是自动生成的吗。。。

**Comment by elloray** [comment]
1. fetch null message是`emittingOffset+1`的偏移上没有消息，查看下是否zk上记录的offset已经是过期的offset了
2. 删除的是jstorm下面的offset目录吗？如果是的话就不太清楚

**Comment by MarcusQian** [comment]
1、KafkaSpout读数据每次都是从头开始：如果Bolt不进行ack, 则offsetNumber永远相等, Bolt中显式调用collector.ack(tuple)即可解决；
2、fetch null message：zookeeper里存该topic的offset目录不存在
3、删除zookeeper里存offset目录不再生成/offset目录未生成：jstorm-kafka生成存offset目录必须是kafka有实时的消息在生产，即使有老消息存在也不会生成，而且生成之后的offsetNumber是实时记录的位置（无法获取老记录），想读取老记录，必须kafka.fetch.from.beginning=ture，但这样如果jstorm重启，那又会从头开始读数据，简直不知道说什么好了。。。

**Comment by elloray** [comment]
@MarcusQian 
1. 在`KafkaSpout.nextTuple()`中调用了更新offset的代码，不用ack也是可以的
3. 可以通过startOffsetTime来设置消费开始的时间，不过这块代码目前jstorm-kafka是缺失的，可以参考下面代码实现在`PartitionConsumer`的构造方法中


>    if (config.fromBeginning) {
                     lastCommittedOffset = consumer.getOffset(config.topic, partition, kafka.api.OffsetRequest.EarliestTime());
            } else if (config.startOffsetTime > 0){
                     lastCommittedOffset = consumer.getOffset(config.topic, partition, config.startOffsetTime);
            } else  if (jsonOffset != null) {
                     lastCommittedOffset = jsonOffset;
            } else {
                     lastCommittedOffset = consumer.getOffset(config.topic, partition, kafka.api.OffsetRequest.LatestTime());
            }
            emittingOffset = lastCommittedOffset;

**Comment by MarcusQian** [comment]
@elloray 

1. 试了一下，没有`collector.ack(tuple)`，offset真没有更新。。。不知道为什么
2. 是让我参考`PartitionConsumer`构造方法里的代码自己写吗？在`kafka.fetch.from.beginning=ture`的情况下设置startOffsetTime的确是没什么效果

**Comment by elloray** [comment]
@MarcusQian 
1. 如果是同步的ack模式，确实只有ack会触发`pendingOffsets.remove(offset)`的操作，这样offset才会更新
2. 对

**Comment by MarcusQian** [comment]
@elloray 
非常感谢你的解答
