### ISSUE TITLE
多个节点，fieldsGrouping会把同一field的数据发往同一个节点的同一个线程处理吗？

### ISSUE THREAD

**Issue by MarcusQian** [alibaba/jstorm#462]
网上都是说会发往同一个线程，那多个节点，fieldsGrouping会把同一field的数据发往同一个节点的同一个线程处理吗？

**Comment by zgqq** [comment]
应该是会的，不然自已要处理的情况就相当难了

**Comment by 1647917675** [comment]
会的

**Comment by zgqq** [comment]
@1647917675 问一个问题，就是fieldsGrouping不会内存泄露吗，比如一个值出现一段时间后，以后再也不会出现的话

**Comment by 1647917675** [comment]
你的意思你的计算结果一直存在内存里，然后fields的值比较多是吧，一般这个计算的结果，都会持久化到外部，内存的风险太大，太不可控了

**Comment by 1647917675** [comment]
@zgqq  按照你的逻辑 我建议你可以将最近不活跃的filed 持久化到外部

**Comment by zgqq** [comment]
@1647917675 比如我现在在做一个日志分析系统，我用fieldsGrouping("parser",new Fields("access_time"))，这样的话，过去的时间不可能被统计了

**Comment by 1647917675** [comment]
过去的时间，你可以持久化到外部去啊

**Comment by 1647917675** [comment]
@zgqq 你可以持久化到外部去啊

**Comment by zgqq** [comment]
@1647917675 jstorm有这样的api吗？

**Comment by 1647917675** [comment]
@zgqq  这个你可以自己实现啊，一个定时器或是检测线程或是自己维护一个活跃的queue都ok啊

**Comment by zgqq** [comment]
@1647917675 关键是要怎么去掉内存的fields

**Comment by 1647917675** [comment]
@zgqq 那我问你 假如你的bolt是处理2017-02-12 09:12:23  2017-02-12 09:13:25 2017-02-12 09:15:23  这几个filed 值      那你的bolt是如何处理《K,V》的关系的 。

**Comment by zgqq** [comment]
@1647917675 我的topology大致如下

     ```
   TopologyBuilder builder = new TopologyBuilder();
        builder.setSpout("test-log-spout", new TestWordSpout());
        builder.setBolt("log-parser",new TestLogParserBolt(),2)
                .localOrShuffleGrouping("test-log-spout");
        builder.setBolt("log-access-time", new AccessTimeBolt(),2)
                .fieldsGrouping("log-parser",new Fields("access_time"));
        builder.setBolt("log-dao-access-time", new AccessTimeDaoBolt()).globalGrouping("log-access-time");

```

**Comment by 1647917675** [comment]
@zgqq 你电我吧 13522704814

**Comment by 1647917675** [comment]
@zgqq 你加我qq吧，细聊一下

**Comment by zgqq** [comment]
@1647917675 好的

**Comment by zgqq** [comment]
@1647917675 加了

**Comment by 1647917675** [comment]
@zgqq  没有

**Comment by zgqq** [comment]
@1647917675 我通过在qq搜索你的手机号了，然后找到就加了

**Comment by 1647917675** [comment]
OK ，问题解决了

**Comment by zgqq** [comment]
@1647917675 谢谢了，已经follow
