### ISSUE TITLE
窗口化操作

### ISSUE THREAD

**Issue by chasel-hu** [alibaba/jstorm#472]
请问下，窗口化操作，按照官方文档设定，只有每次窗口滑动的时候才执行execute(TupleWindow inputWindow)这个方法，这样，如果窗口时间相对比较大，比如一个小时，那么导致某个节点计算负载一下子增大，如果是在单机或者集群比较小的情况下，会造成计算时间变长吧？
可以更改为每次新产生一个消息就进行计算，等到某个特定的时间点就把结果传送出去？

**Comment by fengjian428** [comment]
这个过段时间会放出来

**Comment by unsleepy22** [comment]
2.4.0已经release，请参考文档：http://jstorm.io/ProgrammingGuide_cn/NewWindow.html
