### ISSUE TITLE
[jstorm 2.1.1]java.lang.NoSuchMethodError: backtype.storm.tuple.Values.([Ljava/lang/String;)V

### ISSUE THREAD

**Issue by sjq597** [alibaba/jstorm#483]
提个问题，最近想尝试使用flux这种配置化的方式来通用化创建jstorm任务,然后集群上的jstorm是2.1.1版本的,但是jstorm-flux这个插件是在最新的jstorm 2.2.1中才引入的，这就带来了一个问题
我在本地搭建了jstorm 2.2.1版本跑了一个jstorm-utility/jstorm-flux/flux-examples的例子是没有问题的，但是我提交到集群上用jstorm 2.1.1跑就会报错:
> 
[ERROR 2017-04-10 10:31:34 c.a.j.t.e.s.SpoutExecutors:178 word-spout:5-MultipleThreadSpoutExecutors] spout execute error 
java.lang.NoSuchMethodError: backtype.storm.tuple.Values.([Ljava/lang/String;)V
at com.alibaba.jstorm.flux.examples.WordSpout.nextTuple(WordSpout.java:47) ~[stormjar.jar:na]
at com.alibaba.jstorm.task.execute.spout.SpoutExecutors.nextTuple(SpoutExecutors.java:175) ~[jstorm-core-2.1.1.jar:na]
at com.alibaba.jstorm.task.execute.spout.MultipleThreadSpoutExecutors.run(MultipleThreadSpoutExecutors.java:79) [jstorm-core-2.1.1.jar:na]
at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) [jstorm-core-2.1.1.jar:na]
at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
[ERROR 2017-04-10 10:31:34 c.a.j.t.e.TaskReportError:46 word-spout:5-MultipleThreadSpoutExecutors] Report error to /ZK/taskerrors/yaml-topology-test-16-1491566733/5

然后我对比了一下2.1.1和2.2.1的`backtype.storm.tuple.Values`这个类,两者的差异如下
* jstorm 2.1.1
```
public class Values extends ArrayList<Object> {
    public Values() {

    }

    public Values(Object... vals) {
        super(vals.length);
        for (Object o : vals) {
            add(o);
        }
    }
}
```

* jstorm 2.2.1
```
public class Values extends ArrayList<Object> {
    public static final int OBJECT = 0;
    public static final int STRING = 1;
    public static final int INTEGER = 2;

    public int type;

    public Values() {

    }

    public Values(Object... vals) {
        super(vals.length);
        for (Object o : vals) {
            add(o);
        }
        type = OBJECT;
    }

    public Values(String... strs) {
    	super(strs.length);
        for (String s : strs) {
            add(s);
        }
        type = STRING;
    }

    public Values(Integer... ints) {
    	super(ints.length);
        for (Integer i : ints) {
            add(i);
        }
        type = INTEGER;
    }

    @Override
    public boolean add(Object obj) {
        Object val = obj;
        if (type == STRING && !(obj instanceof String)) {
            type = OBJECT;
        } else if (type == INTEGER && !(obj instanceof Integer)) {
            type = OBJECT;
        }
        return super.add(val);
    }
}
```
简单来看就是多了几个重载的方法，还是没懂问题出在哪,照理说string也是object的子类，不重载那几个方法也可以找到这个方法的吧，之前在集群上的任务在用的时候都是`new Values()`里面随便扔内容也没出错的啊，有人知道这个问题是什么导致的吗？还是说flux这个特性只能在2.2.1版本上用？

**Comment by fengjian428** [comment]
flux是2.2.1才有的，你升级一下好了

**Comment by sjq597** [comment]
@fengjian428 最后我确实是升级之后才可以用的，但是我有一点不明白,就算是2.2.1才有,我手动编译了flux-core包,拷贝到jstorm 2.1.1的lib目录,但是报错却是因为上面这个jstorm-core里面的错误，而且还是重载的问题，有点儿说不通啊

**Comment by sjq597** [comment]
算了，升级到2.2.1用了，具体啥问题官方也没个解释
