### ISSUE TITLE
替换掉Clojure包

### ISSUE THREAD

**Issue by darionyaphet** [alibaba/jstorm#485]
能否使用Java原生API 替换掉Clojure API？  感觉这样会好些吧

**Comment by fengjian428** [comment]
我们没有ClojureAPI的

**Comment by darionyaphet** [comment]
@fengjian428  `backtype.storm.tuple.TupleImpl`  这个类里面还有些Clojure 的接口 能用Java API替换么？

**Comment by unsleepy22** [comment]
这个主要是保持对storm的兼容。。。
