### ISSUE TITLE
JStorm-Kafka里的kafkaSpout读数据总是报fetch data from kafka topic[test-topic] host[xx.xx.xx.xx:9092] partition[0] error:1

### ISSUE THREAD

**Issue by caiyifeng** [alibaba/jstorm#499]
我的KafkaSpoutConfig的配置如下：
                stormConf.put("kafka.zookeeper.hosts", "10.139.32.187:2181");
                stormConf.put("kafka.broker.hosts", "10.139.102.26,10.139.36.29");
                stormConf.put("kafka.client.id", "client0");
                stormConf.put("kafka.topic", "test-topic");
                stormConf.put("kafka.fetch.from.beginning", "false");

为什么起来后总是报如下错误：
[ERROR 2017-04-27 00:25:21 c.a.j.k.KafkaConsumer:94 testspout:4-MultipleThreadSpoutExecutors] fetch data from kafka topic[test-topic] host[iZ23acwraoqZ:9092] partition[0] error:1
[WARN 2017-04-27 00:25:21 c.a.j.k.PartitionConsumer:137 testspout:4-MultipleThreadSpoutExecutors] reset kafka offset 384
[WARN 2017-04-27 00:25:21 c.a.j.k.PartitionConsumer:145 testspout:4-MultipleThreadSpoutExecutors] fetch null message from offset 384

原来一直用storm-kafka，没这么多问题，崩溃了，求帮助！！

**Comment by xuziw** [comment]
你试试一直向kafka的主题发送消息。
或者把kafka.fetch.from.beginning改为true
