### ISSUE TITLE
 Could not initialize class com.alibaba.jstorm.ui.utils.UIUtils

### ISSUE THREAD

**Issue by gohitbear** [alibaba/jstorm#509]
java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.jstorm.ui.utils.UIUtils
	com.alibaba.jstorm.ui.controller.ClustersController.show(ClustersController.java:41)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:781)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:721)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

**Comment by gohitbear** [comment]
########## These MUST be filled in for a storm configuration
 storm.zookeeper.servers:
     - "10.10.20.**"

 storm.zookeeper.root: "/jstorm"

# cluster.name: "default"

 #nimbus.host/nimbus.host.start.supervisor is being used by $JSTORM_HOME/bin/start.sh
 #it only support IP, please don't set hostname
 # For example
 # nimbus.host: "10.132.168.10, 10.132.168.45"
 nimbus.host: "10.10.20.***"
 #nimbus.host.start.supervisor: false

# %JSTORM_HOME% is the jstorm home directory
 storm.local.dir: "%JSTORM_HOME%/data"
 # please set absolute path, default path is JSTORM_HOME/logs
# jstorm.log.dir: "absolute path"

# java.library.path: "/usr/local/lib:/opt/local/lib:/usr/lib"



# if supervisor.slots.ports is null,
# the port list will be generated by cpu cores and system memory size
# for example,
# there are cpu_num = system_physical_cpu_num/supervisor.slots.port.cpu.weight
# there are mem_num = system_physical_memory_size/(worker.memory.size * supervisor.slots.port.mem.weight)
# The final port number is min(cpu_num, mem_num)
# supervisor.slots.ports.base: 6800
# supervisor.slots.port.cpu.weight: 1.2
# supervisor.slots.port.mem.weight: 0.7
# supervisor.slots.ports: null
supervisor.slots.ports:
    - 6800
    - 6801
    - 6802
    - 6803

# Default disable user-define classloader
# If there are jar conflict between jstorm and application,
# please enable it
# topology.enable.classloader: false

# enable supervisor use cgroup to make resource isolation
# Before enable it, you should make sure:
#       1. Linux version (>= 2.6.18)
#       2. Have installed cgroup (check the file's existence:/proc/cgroups)
#       3. You should start your supervisor on root
# You can get more about cgroup:
#   http://t.cn/8s7nexU
# supervisor.enable.cgroup: false


### Netty will send multiple messages in one batch
### Setting true will improve throughput, but more latency
# storm.messaging.netty.transfer.async.batch: true

### if this setting  is true, it will use disruptor as internal queue, which size is limited
### otherwise, it will use LinkedBlockingDeque as internal queue , which size is unlimited
### generally when this setting is true, the topology will be more stable,
### but when there is a data loop flow, for example A -> B -> C -> A
### and the data flow occur blocking, please set this as false
# topology.buffer.size.limited: true

### default worker memory size, unit is byte
# worker.memory.size: 2147483648

# Metrics Monitor
# topology.performance.metrics: it is the switch flag for performance
# purpose. When it is disabled, the data of timer and histogram metrics
# will not be collected.
# topology.alimonitor.metrics.post: If it is disable, metrics data
# will only be printed to log. If it is enabled, the metrics data will be
# posted to alimonitor besides printing to log.
# topology.performance.metrics: true
# topology.alimonitor.metrics.post: false

# UI MultiCluster
# Following is an example of multicluster UI configuration
# ui.clusters:
#     - {
#         name: "jstorm",
#         zkRoot: "/jstorm",
#         zkServers:
#             [ "localhost"],
#         zkPort: 2181,
#       }

**Comment by unsleepy22** [comment]
你是用的最新的代码打包的么？最新代码应该不会有这个问题的

**Comment by gohitbear** [comment]
升级到2.2.1以后，问题解决。

但在UI上Topology Graph没有绘制出
2017-05-10 11:43:17,725 [http-nio-8080-exec-6] INFO  c.a.j.u.c.TopologyController - topology page show cost:9ms
2017-05-10 11:43:18,038 [http-nio-8080-exec-8] WARN  o.s.w.s.PageNotFound - No mapping found for HTTP request with URI [/jstorm-ui-2.2.1/api/v2/cluster/jstorm/1/topology/TopologyMain-5-1494319552/metrics] in DispatcherServlet with name 'mvc-dispatcher'
2017-05-10 11:43:18,069 [http-nio-8080-exec-9] WARN  o.s.w.s.PageNotFound - No mapping found for HTTP request with URI [/jstorm-ui-2.2.1/api/v2/cluster/jstorm/1/topology/TopologyMain-5-1494319552/graph] in DispatcherServlet with name 'mvc-dispatcher'

是需要特别在哪里配置么？Topology没有报错，成功运行了10小时+

**Comment by gohitbear** [comment]
在浏览器出现404
http://ip:port/api/v2/cluster/jstorm/1/topology/TopologyMain-5-1494319552/graph
jquery
$.getJSON("api/v2/cluster/jstorm/1/topology/TopologyMain-5-1494319552/graph", function (data) {
