### ISSUE TITLE
jstorm有没有队列堆积报警和动态调整线程数的功能？

### ISSUE THREAD

**Issue by SmartCC** [alibaba/jstorm#511]
我的程序里有一部分bolt处理时间耗时比较长，在数据处理的高峰期会出现堆积的情况，现在暂时只能采取增加bolt并行数的方法来处理。但是bolt消耗的内存等资源比较大，在平常的时候回造成资源的浪费，请问有没有方法能动态的调整bolt的线程数？

**Comment by unsleepy22** [comment]
队列的数据，在metrics里面是有的，可以通过获取metrics的这个值，来做自定义的监控。
