### ISSUE TITLE
jstorm-core 2.4.0 shade bug

### ISSUE THREAD

**Issue by panguoqing** [alibaba/jstorm#514]
jstorm-core 2.4.0中包含了下面这个依赖<include>com.google.code.gson:gson</include>。
在shade中重定义路径的时候使用了下面的这个relocation：
<relocation>
    <pattern>com.google.code.gson</pattern>
    <shadedPattern>shade.storm.com.google.code.gson</shadedPattern>
</relocation>
但是com.google.code.gson:gson的package路径是com.google.gson，导致打包的时候，gson的代码并没有被relocate到shade.storm目录下。

**Comment by panguoqing** [comment]
你好，已经提了一个pr，地址是 https://github.com/alibaba/jstorm/pull/516

**Comment by kevin19931015** [comment]
请问2.4.0在哪里下载

**Comment by unsleepy22** [comment]
@kevin19931015 https://github.com/alibaba/jstorm/releases
如果想要最新的package，建议下载源码后自己打包。
