### ISSUE TITLE
jstorm是怎么处理失败的bolt的？

### ISSUE THREAD

**Issue by SmartCC** [alibaba/jstorm#517]
我topology中的**一台机器中的一个bolt失败**了（因为一个本地文件读取失败），**其余的机器上相同的bolt都正常启动了**，然后整个topoplog无法正常运行，日志显示一直在等这个这个bolt。请问jstorm是怎么处理节点上bolt失败的问题的，怎么设置才能使其中一个节点的失败不影响整体topology?

**Comment by unsleepy22** [comment]
worker在一台机器上重试几次之后，如果仍然不能成功启动，就会尝试调度到其他机器上的。
