### ISSUE TITLE
ui error 显示 No response ，这个错误造成了集群反压

### ISSUE THREAD

**Issue by mr2qin** [alibaba/jstorm#544]
ui 显示 No response from Task-49, last report time(sec) is 1499166697, at 2017-07-04 19:16 
这是什么意思？什么原因呢？
这个错误造成了集群反压

**Comment by Ruguo** [comment]
kafkaspout消费kafka时出现了同样的问题，这个是怎么回事呢？

**Comment by qianshanding** [comment]
我用kafkaSpout消费也出现这样的问题，如果是Task挂了，为啥没有重新启动一个Task？

**Comment by unsleepy22** [comment]
no response是说某个spout/bolt处理速度过慢，这个跟反压没有必然关系，只是一个警告告诉用户处理慢了，反压本身是默认打开的，可以通过配置项关闭。
