### ISSUE TITLE
菱形拓扑的吞吐量问题

### ISSUE THREAD

**Issue by zengxmy** [alibaba/jstorm#550]
您好，有个问题想请教一下。
   我创建了一条菱形的拓扑:        
                                                       B1
                                                ↗            ↘        
                                           S                       B3
                                                ↘            ↗
                                                       B2
    它是由一个spout S  和 3 个bolt:B1、B2、B3组成，数据有两条处理路径S——>B1——>B3和S——>B2——>B3，在S中产生的数据只会被其中一条路径处理。在并行度全为1的情况下，这个拓扑的吞吐量为2000TPS，而我单独测试S——>B1——>B3和S——>B2——>B3这个两个路径的性能为10000TPS和40000TPS。我预期是取较小的性能即10000TPS，这和实测的情况有很大差距，这是为什么？
   谢谢！

**Comment by longdafeng** [comment]
你worker 没有设好， 你把worker数调大就可以了
