### ISSUE TITLE
问下jstorm的异常处理的设计？

### ISSUE THREAD

**Issue by lcy362** [alibaba/jstorm#558]
看源码发现BasicBoltExecutor里会catch住FailedException,然后发一条fail消息；而其他异常会在BoltExecutors里catch,但是只做report,不做fail.
想问下这种设计是出于什么考虑呢？ 因为遇到其他异常的消息最终也只能等超时被fail掉，为什么不干脆设计成有异常就直接fail?

**Comment by longdafeng** [comment]
basicboltexecutor catch fail，后抛出FailedException， 就表示这个tuple处理失败， 他会告诉acker 这个tuple失败， 但不会让task直接挂掉。

boltexecutor catch一个exception后， 会做report， 这个report函数，首先report 错误到zookeeper，然后自杀进程， 如果这个错误和某个tuple 有关联， 这个tuple 后面会因为超时而自动fail
