### ISSUE TITLE
jstorm0.9的线上项目如何在新搭的2.1集群上运行

### ISSUE THREAD

**Issue by wjx199025** [alibaba/jstorm#563]
请问各位大牛，今天经理让我搭建了jstorm2.1的集群，然后给了我一个0.9版本的项目，让我运行出来，我需要做哪些更改啊？搞了半天，是真的没有思路，我刚入门的，麻烦各位指点迷津。

**Comment by sjq597** [comment]
这种跨大版本了，我建议你把项目的pom文件里面的jstorm-core换成jstorm 2.1重新编译打包，然后重新在新集群上提交，当然你得找个作业先在本地模式测试通过了再往线上提交
