### ISSUE TITLE
Jstorm 2.2.1 worker oom异常

### ISSUE THREAD

**Issue by vipsql** [alibaba/jstorm#566]
worker 内存在运行期间不断增长，GC后内存没有释放的迹象，用Heap Dump分析出来的总内存数目和UI显示及服务器常驻内存数量不一致；

**Comment by dengbo** [comment]
可以看下输出是否堵了，有没有设置反压，也有可能是你的消息大量没有被ack或者fail，存在内存里

**Comment by vipsql** [comment]
已经找到问题所在了，有Component使用资源较高，没有CPU时间处理GC和上报状态给supervisor
