### ISSUE TITLE
RefreshActive线程优先级似乎不应该是Thread.MIN_PRIORITY

### ISSUE THREAD

**Issue by yunfan123** [alibaba/jstorm#568]
RefreshActive这个类里面会设置task的状态。
而在RefreshActive这个类的构造函数里面调用run()方法完全没有用，因为这个时候workerData.getShutdownTasks 一定为NULL，此时还没有初始化，调用这个并没有加快初始化，反正多访问了一次zk.
这个类里面会改变task的TaskStatus，但是初始化这个线程的时候，将其线程优先级设置为最低(MIN_PRIORITY)，在load高的机器上面，似乎这个线程有概率永远都调度不到（实测几个小时都没有调度到, 不过物理机load 维持在200+ ...）。
造成的结果是：spout一直没有变为TaskStatus.RUN状态，一直卡在:
https://github.com/alibaba/jstorm/blob/2.2.1/jstorm-core/src/main/java/com/alibaba/jstorm/task/execute/spout/MultipleThreadSpoutExecutors.java#L84这个循环里面。

**Comment by unsleepy22** [comment]
这个优先级事实上应该都不会生效的，基本可以忽略

**Comment by yunfan123** [comment]
确实...我的问题似乎是连接没有完全建立引起的。
另外在RefreshActive这个类的构造函数里面去调用run确实没有什么用。
