### ISSUE TITLE
请问一下，为什么会用Netty替换zeromq

### ISSUE THREAD

**Issue by NorthWindTR** [alibaba/jstorm#569]
我们公司的jstorm是自己维护的版本，在现有版本使用的是zeromq，会出现如果之前消息堵住，即使流量高峰过了，内存也不释放的情况。我想请问一下，jstorm从zeromq切换netty是基于什么考虑？之前使用zeromq是不是有内存泄漏的问题？

**Comment by NorthWindTR** [comment]
补充一下，是堆外内存不释放

**Comment by FieldSoft-HelloClyde** [comment]
zeromq换到netty是因为zeromq的证书和apache的证书不兼容

**Comment by longdafeng** [comment]
zeromq 一堆坑， 性能也不行
