### ISSUE TITLE
使用fieldsGrouping 策略分发数据，数据会有部分丢失

### ISSUE THREAD

**Issue by michelle-q** [alibaba/jstorm#574]
boltA向boltC和boltB发送相同streamId 的数据，使用的分发策略不同，boltA->boltC 使用的是localOrShuffleGrouping， boltA->boltB使用的是fieldsGrouping，最后boltC接受到的数据是完整的，boltB会缺少部分数据，发送量都是相同的，而且指定字段的值都是相同。请问这是什么原因？

**Comment by longdafeng** [comment]
不会发生数据丢失，怀疑是你worker爆掉了
