### ISSUE TITLE
JSTORM 2.2.1与操作系统内核相关的问题

### ISSUE THREAD

**Issue by zhangkaka** [alibaba/jstorm#577]
CENTOS 7.2
3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

JSTORM 2.21 

两个一起使用时，会有一堆的ProcessLuncher(1000以上)，很多woker无法启动。

**Comment by longdafeng** [comment]
有这个bug， 不过，最新版已经fix了
