### ISSUE TITLE
jstorm 2.4发布以来国内无法下载问题

### ISSUE THREAD

**Issue by youngcle** [alibaba/jstorm#578]
我从2.1开始跟踪，在我的业务中更新jstorm
自从2017年5月2.4发布以来，便始终无法下载
貌似2.4的编译版本压缩包发布在亚马逊s3上，可能是有墙的缘故。
源代码包可以下载，但是mvn builid有包走不下去。
4个月过去了，我从没下载成功过。至今也没更新

能否请jstorm团队在一个便于国内网络获取的位置发布编译版本。

p.s我在北京。用公司网络、家里网络都不成功
谢谢

**Comment by sjq597** [comment]
这个自己编译发到你们公司的maven仓库也行的吧

**Comment by longdafeng** [comment]
你翻墙吧
