### ISSUE TITLE
jstorm开启反压之后，什么时候能够解除反压？观察任务状态，下游的bolt已经处于空闲了，但是spout的还是处于反压状态，一直不解除，这是什么原因？

### ISSUE THREAD

**Issue by zhangshaotao** [alibaba/jstorm#580]

**Comment by misslv** [comment]
你是通过web ui观察到的还是用日志观察到的？web ui有延迟的，你可以直接看日志。如果日志还在输出对task[id]的反压警告，那么反压还在继续，如果没有输出这个，那么就没有在反压了。

**Comment by longdafeng** [comment]
最新版是在通信层做反压， 因此是无法关闭的， 而且对用户是无感知的， 当下游发生堆积，仅仅他的上游进行限流， 是层层递进的
