### ISSUE TITLE
请问这个错是什么原因呢Report error to /ZK/taskerrors/5iketang-2-1508897116/6: No response from Task-6, last report time(sec) is 1508902623

### ISSUE THREAD

**Issue by kevin19931015** [alibaba/jstorm#584]
错误日志：
[ERROR 2017-10-25 11:41:23 c.a.j.t.e.TaskReportError:68 pool-6-thread-2] Report error to /ZK/taskerrors/5iketang-2-1508897116/6: No response from Task-6, last report time(sec) is 1508902623

**Comment by unsleepy22** [comment]
一般是指spout/bolt处理慢了，如果你的处理逻辑本来就慢，那可以忽略，不然要看一下是不是下游堆积了。

**Comment by kevin19931015** [comment]
谢谢！
