### ISSUE TITLE
jstorm2.4有下载地址吗

### ISSUE THREAD

**Issue by kevin19931015** [alibaba/jstorm#586]
请问有没有发布啊

**Comment by panguoqing** [comment]
https://github.com/alibaba/jstorm/releases/tag/2.4.0

**Comment by kevin19931015** [comment]
谢谢！

**Comment by kevin19931015** [comment]
不好意思，再打扰一下， maven构建项目的时候，2.4.0好像不可以。

这样写有问题吗。
        <dependency>
            <groupId>com.alibaba.jstorm</groupId>
            <artifactId>jstorm-core</artifactId>
            <version>2.4.0</version>
            <scope>provided</scope>
        </dependency>

**Comment by unsleepy22** [comment]
可能是没有发布到maven中央仓库。如果你们有内部的maven仓库的话，可以先distribute上去，然后依赖内部的maven仓库。

**Comment by panguoqing** [comment]
mvn install:install-file -Dfile=jar包路径 -DgroupId=com.alibaba.jstorm -DartifactId=jstorm-core -Dversion=2.4.0 -Dpackaging=jar

**Comment by kevin19931015** [comment]
@unsleepy22 @panguoqing 非常感谢 想问一下有没有热升级方面的资料
