### ISSUE TITLE
UI里增加显示当前系统配置的信息

### ISSUE THREAD

**Issue by Gvain** [alibaba/jstorm#59]
在UI里面增加显示当前系统配置的信息，例如
storm.local.dir, storm.zookeeper.root, task.heartbeat.frequency.secs等

**Comment by longdafeng** [comment]
fixed already

**Comment by wuchong** [comment]
集群的Configuration 里能看到这些信息

![image](https://cloud.githubusercontent.com/assets/5378924/11583404/524d8826-9a94-11e5-87a0-381a398a31be.png)
