### ISSUE TITLE
如果不在spout中的nextTuple发送数据，而是在open中启动一个线程发送，反压会启作用吗？

### ISSUE THREAD

**Issue by someorz** [alibaba/jstorm#590]
我现在使用spring-kafka，在open方法中初始化，然后没有在nextTuple发送数据，这样当下游处理跟不上时，反压会启作用吗？还是必须在nextTuple中发送数据才可以？

**Comment by longdafeng** [comment]
最新的jstorm 是在底层做反压，在通信层做， 因此都是产生效果
