### ISSUE TITLE
Flink和Storm的性能对比

### ISSUE THREAD

**Issue by vipsql** [alibaba/jstorm#591]
Flink和Storm的性能对比，大家有什么看法
https://mp.weixin.qq.com/s/dpZPwlj-h0s-rHjMgpwumg

**Comment by longdafeng** [comment]
对于这种wordcount测试例子来说，
在at-most-once 场景下， jstorm > flink > storm
在at-least-once 场景下， flink > jstorm > storm

但通常这种wordcount 没有多少意义。
不过，未来， flink 应该是会比storm 更好。
