### ISSUE TITLE
port数量开始设置过少，后期不够用时，可以配置自增port么？

### ISSUE THREAD

**Issue by mrgiser** [alibaba/jstorm#593]
如题，就是集群在运行后发现port不够用了，会报错
Fail to sumbit topology, Root cause:there's no enough worker. allocWorkerNum=5, availableWorkerNum=4

请问可以设置port自增么？

**Comment by kevin19931015** [comment]
应该是storm.yaml中supervisor.slots.ports.base: 6800这个参数吧

**Comment by mrgiser** [comment]
@kevin19931015 你好，你说的supervisor.slots.ports.base: 6800这个参数，我放开注释，然后supervisor.slots.ports这个参数下的port全部注释掉，运行时默认就只有一个port，而且不会自增。请问你说的这个参数怎么使用？需要配合supervisor.slots.port.cpu.weight、supervisor.slots.port.mem.weight这两个一起么？谢谢回复

**Comment by kevin19931015** [comment]
@mrgiser 不好意思啊 我之前也只是猜测 没有验证过 看来这个参数不是我想的那种意思

**Comment by kevin19931015** [comment]
https://github.com/alibaba/jstorm/issues/158
这个帖子似乎回答了你的困惑

**Comment by mrgiser** [comment]
@kevin19931015    非常感谢，知道怎么回事了
