### ISSUE TITLE
在jstorm-UI中,观察woker和task都active的状态下,nimbus自动kill掉topology进程

### ISSUE THREAD

**Issue by fangxia-** [alibaba/jstorm#624]
我的topology启动后在jstormUI里面可以看到各个woker和task都启动成功了,
但是两分钟左右就kill掉了,现在看nimbus的日志感觉像是心跳超时导致的,但是我已经设置了nimbus.task.launch.secs 为240,然而感觉并没有生效.使用官方的小demo仍然是这样,nimbus日志如下,时间间隔从开始启动到kill大概2分钟,但是最后一次心跳到kill时间很短,并没有两分钟
[INFO 2018-04-17 11:59:42 c.a.j.d.n.NimbusUtils:401 pool-7-thread-3] **Update task heartbeat** to nimbus cache  topology:ClientDataCountTopology-5-1523937544,task id:33
[INFO 2018-04-17 11:59:42 c.a.j.d.n.NimbusUtils:401 pool-7-thread-3] **Update task heartbeat** to nimbus cache  topology:ClientDataCountTopology-5-1523937544,task id:35

[INFO 2018-04-17 12:01:14 c.a.j.c.i.DelayStatusTransitionCallback:89 pool-9-thread-38] **Delaying event killed for 1 secs for** ClientDataCountTopology-5-1523937544
[INFO 2018-04-17 12:01:14 c.a.j.d.n.StatusTransition:113 pool-9-thread-38] Successfully updated ClientDataCountTopology-5-1523937544 to status **StormStatus[type=killed,killTimeSecs=1,delaySecs=1,oldStatus=<null>]**
[INFO 2018-04-17 12:01:14 c.a.j.d.n.StatusTransition:116 pool-9-thread-38] **Successfully apply event: changing status** ClientDataCountTopology-5-1523937544 -> **kill**
[INFO 2018-04-17 12:01:15 c.a.j.c.i.RemoveTransitionCallback:52 pool-7-thread-1] **Begin to remove topology**: ClientDataCountTopology-5-1523937544
[INFO 2018-04-17 12:01:16 c.a.j.d.n.ServiceHandler:1993 pool-9-thread-39] **notifyThisTopologyTasksIsDead** ClientDataCountTopology-5-1523937544

kill之后woker日志显示
Failed to reconnect ... [1], /192.168.1.36:6800, channel = [id: 0xf157e212], cause = {}
java.net.ConnectException: **Connection refused: /192.168.1.36:6800**

**Comment by vipsql** [comment]
服务器时间是否同步?

**Comment by fangxia-** [comment]
@vipsql 是在单机状态下运行,而且防火墙是完全关闭,我设置了心跳超时时间为480秒仍然没有作用

**Comment by fangxia-** [comment]
奇怪的是本地模式启动的话一切都很正常,只在放到服务器上面跑的时候起不来,假如是OOM或者线程阻塞的话,本地模式应该也起不来的吧?

**Comment by fangxia-** [comment]
好吧,并不是什么妖怪的问题,
我使用的启动方式是JStormHelper.runTopology,
使用这个在生产环境启动的话需要添加一个配置参数,conf.put("RUN_LONG_TIME",true);
否则会在120秒内把topology杀掉,加上这个参数就好啦
