### ISSUE TITLE
jstorm2.4版本的时间窗口统计每天的bolt总是在AM 8:00执行

### ISSUE THREAD

**Issue by fangxia-** [alibaba/jstorm#630]
按照example中的方法
`Time windowDay = Time.hours(24);`
`//这里设置为1day也是同样的效果Time windowDay = Time.day(1);`
`builder.setBolt("count",new WordCount().timeWindow(windowDay);`
此时count的时间窗口应该是每天24小时,也就是0:00-0:00的范围,但是每次窗口执行的时候都是第二天的早上8:00
怀疑是linux服务器的时区设置导致的,因为设置的中国时区为CST,刚好跟UTC相差8小时
但是看了我服务器的配置,执行hwclock显示正确的CST时间,我用java代码测试new Date()得到的也是正确的CST时间
执行timedatectl 之后显示RTC time 为UTC时间,难道jstorm取的是这个时间吗?
我尝试过让它跟CST时间同步,但是系统提示说这个最好保存UTC时间,查了一下确实也说这个时间最好别动,(而且也修改不成功,过几分钟又自动恢复了,应该有别的进程在同步这个时间)
我迷茫了...

**Comment by italycappuccino** [comment]
一句迷茫换来我的迷之微笑

**Comment by fangxia-** [comment]
修改了源码,把时间窗口的start时间修正到了CST的0:00,解决了这个问题
