### ISSUE TITLE
storm.yaml中的nimbus.host配置移除

### ISSUE THREAD

**Issue by yveschina** [alibaba/jstorm#69]
storm.yaml中的nimbus.host很容易误解成原来的含义，由于jstorm的nimbus master、slaves均在ZK上，用户容易迷惑此处nimbus.host的含义，进而不知如何配置。

通过start.sh脚本，此处nimbus.host的含义应该是为了集群批量部署时，在指定的几台机器上启动nimbus进程。

由于这是与集群部署相关的，与jstorm框架实现无关，是否可以单独放到stormctl.conf配置文件里，例如：
bin/jstormctl.conf
nimbus.nodes:"IP1 IP2 IP3"
supervisor.nodes:"IP1 IP2 IP3"

**Comment by longdafeng** [comment]
你这个思路是正确的，不过，我们不打算改了

因为，再增加一个配置文件，会增加运维工程师很大的工作量

**Comment by darionyaphet** [comment]
感觉尽量和Storm保持一致吧  这样迁移成本都会低一些

**Comment by wuchong** [comment]
嗯， 话说storm最近把 `nimbus.host` 改成了 `nimbus.seeds`， 因为nimbus可能不只一个。
