### ISSUE TITLE
web ui 显示集群信息

### ISSUE THREAD

**Issue by phb983128** [alibaba/jstorm#79]
jstorm 版本 0.9.3.1

Nimbus  host   server198
Supervisor host  server 198 ，node223
zookeeper   server198

集群方式启动显示如附件图

为什么Supervisors 显示的数目总是1，而且Supervisor Summary 列表中随着刷新页面server 198 ，node223交替显示，一会显示server198 一会显示node223

**Comment by longdafeng** [comment]
你这个问题的root cause是你安装第二台机器的时候，直接把第一台机器的本地目录也拷贝过去了，每个本地目录里面会带有supervisorID，导致第二台机器的supervisor使用的supervisorId和第一台是一样的


这个属于你安装不当问题
