### ISSUE TITLE
做一个bolt单元测试的框架如何

### ISSUE THREAD

**Issue by 7ai** [alibaba/jstorm#83]
一般的bolt都是输入tuple->处理->输出tuple的流程,在做单元测试的时候没有办法针对bolt测试,只能是实现一个逻辑类,在bolt和单元测试的时候分别调用这个类,这样实在不是很方便,能不能有一个测试框架呢

**Comment by longdafeng** [comment]
0.9.6.3  支持junit测试topology， 不知道满不满足你的需求

**Comment by 7ai** [comment]
0.9.6.3好的我去看看,thank you大牛
