### ISSUE TITLE
worker挂掉，提示stormconf.ser does not exist

### ISSUE THREAD

**Issue by deepeye** [alibaba/jstorm#94]
![qq 20150225144919](https://cloud.githubusercontent.com/assets/1631876/6366199/14ff604a-bcfd-11e4-80ee-53a4d85235cc.png)
这种情况如何避免？

**Comment by longdafeng** [comment]
可以解决， 问题的原因是supervisor下载不全。

你提一个issue到github上， 可以解决的。 0.9.6.4 解决

2015-02-25 14:48 GMT+08:00 deepeye <notifications@github.com>:

**Comment by neil4dong** [comment]
Hi  @longdafeng你好。 
我在本地测试的时候，在最新的jstorm-2.1.1还是出现了同样问题

一台机器上同时运行 nimbus 和 supervisor。

这里是运行的日志。
[SequenceTest-worker-6900.log.txt](https://github.com/alibaba/jstorm/files/329469/SequenceTest-worker-6900.log.txt)
