### ISSUE TITLE
Jstorm ConcurrentModificationException

### ISSUE THREAD

**Issue by liyinhgqw** [alibaba/jstorm#96]
0.9.6.2 版本， 偶尔有如下错误：

547975 [ERROR  2015-02-25 12:00:14 DisruptorQueueImpl:186 parser:162-TransferRunnable]
547976 java.util.ConcurrentModificationException
547977         at java.util.HashMap$HashIterator.nextEntry(HashMap.java:894)
547978         at java.util.HashMap$EntryIterator.next(HashMap.java:934)
547979         at java.util.HashMap$EntryIterator.next(HashMap.java:932)
547980         at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:73)
547981         at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:17)
547982         at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:554)
547983         at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:77)
547984         at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:18)
547985         at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:472)
547986         at backtype.storm.serialization.KryoValuesSerializer.serializeInto(KryoValuesSerializer.java:31)
547987         at backtype.storm.serialization.KryoTupleSerializer.serialize(KryoTupleSerializer.java:44)
547988         at com.alibaba.jstorm.task.TaskTransfer$TransferRunnable.onEvent(TaskTransfer.java:133)
547989         at backtype.storm.utils.DisruptorQueueImpl.consumeBatchToCursor(DisruptorQueueImpl.java:179)
547990         at backtype.storm.utils.DisruptorQueueImpl.consumeBatchWhenAvailable(DisruptorQueueImpl.java:146)
547991         at com.alibaba.jstorm.task.TaskTransfer$TransferRunnable.run(TaskTransfer.java:106)
547992         at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:51)
547993         at java.lang.Thread.run(Thread.java:722)
547994 [ERROR  2015-02-25 12:00:14 AsyncLoopRunnable:75 parser:162-TransferRunnable] Async loop died!
547995 java.lang.RuntimeException: java.util.ConcurrentModificationException
547996         at backtype.storm.utils.DisruptorQueueImpl.consumeBatchToCursor(DisruptorQueueImpl.java:187)
547997         at backtype.storm.utils.DisruptorQueueImpl.consumeBatchWhenAvailable(DisruptorQueueImpl.java:146)
547998         at com.alibaba.jstorm.task.TaskTransfer$TransferRunnable.run(TaskTransfer.java:106)
547999         at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:51)
548000         at java.lang.Thread.run(Thread.java:722)
548001 Caused by: java.util.ConcurrentModificationException
548002         at java.util.HashMap$HashIterator.nextEntry(HashMap.java:894)
548003         at java.util.HashMap$EntryIterator.next(HashMap.java:934)
548004         at java.util.HashMap$EntryIterator.next(HashMap.java:932)
548005         at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:73)
548006         at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:17)
548007         at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:554)
548008         at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:77)
548009         at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:18)
548010         at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:472)
548011         at backtype.storm.serialization.KryoValuesSerializer.serializeInto(KryoValuesSerializer.java:31)
548012         at backtype.storm.serialization.KryoTupleSerializer.serialize(KryoTupleSerializer.java:44)
548013         at com.alibaba.jstorm.task.TaskTransfer$TransferRunnable.onEvent(TaskTransfer.java:133)
548014         at backtype.storm.utils.DisruptorQueueImpl.consumeBatchToCursor(DisruptorQueueImpl.java:179)
548015         ... 4 more
548016 [INFO  2015-02-25 12:00:14 JStormUtils:145 parser:162-TransferRunnable] Halting process: Async loop died!

**Comment by longdafeng** [comment]
你换个新版本试一下， 如果没有问题， 我就关了这个issue

**Comment by hustfxj** [comment]
根本的原因是，消息在emit后，在序列化的过程中，我们又对消息进行了修改，所有出现了这个exception。如果我们的代码在spout或者bolt里又没有明显的，在emit后对消息进行修改的操作。那很有可能是因为下面这个场景。 消息源task(spout或者bolt)发送相同的消息对象给下游两个bolt，其中一个目标bolt和消息源task在同一个worker，另一个目标bolt和消息源task不在同一个worker。那么前者因为在一个worker内(同一个进程内)，拿到的是这个对象的引用，后者则需要在远端worker去接收序列化后的消息。这时如果前者的bolt在收到消息后对消息进行了修改，而恰好这时消息又在做序列化操作，准备发给后者的远端bolt，就同样会出现上述的exception。@liyinhgqw

**Comment by Ares1201** [comment]
@hustfxj 请问如何避免这种情况的发生？

**Comment by longdafeng** [comment]
不要modify 输入的tuple，就可以保证这个问题，如果需要修改，则deep copy／clone 出来一个新对象
